### ISSUE TITLE
OSのターミナルが表示されません。

### ISSUE THREAD

**Issue by BD-sheres** [uchan-nos/os-from-zero#101]
最終ページまで読み改造しようと思い`https://github.com/uchan-nos/mikanos/tree/osbook_day30e`のソースコードをダウンロードしました。そしてまず試しに実行しようと`APP_DIR=apps RESOURCE_DIR=resource ./build.sh run`のコマンドを実行しました。ですが
![Screenshot from 2021-08-21 09-19-50](https://user-images.githubusercontent.com/87950176/130304374-230a9a87-8a60-44b2-98d5-8ebde9e75174.png)
のようにでウィンドウが表示されませんでした。
なにかAPP_DIR=apps RESOURCE_DIR=resource ./build.sh run`のコマンド以外に入力しないと行けないコマンドがあるのでしょうか？それともなにか別の方法でやらないといけないのでしょうか？わかる方教えてください。

**Comment by uchan-nos** [comment]
同じコマンドで起動させてみたところ、ちゃんと起動しました。
一つ分かったのは、単に `./build.sh run` で起動させた場合、同じような表示のまま止まりました。
もしかして、コマンドラインを間違って打ち込んでいませんか？
コマンドラインをコピー＆ペーストで入力してみたら結果が違うかも。

ちなみに、APP_DIR は正しくは APPS_DIR です。
でも、APP_DIR のままでも、RESOURCE_DIR さえ間違っていなければターミナル画面の表示まで進みます。

もしかしたら resource ディレクトリの中身に必要なファイルが入ってないのかもしれません。
`ls resource` とするとこのような表示になりますか？

    $ ls resource/
    jpn.txt  mikanos.txt  nihongo.ttf

**Comment by BD-sheres** [comment]
ご指摘頂いたように`ls resource/`を確認するとご説明頂いたファイルができました。
コマンドは`APPS_DIR=apps RESOURCE_DIR=resource ./build.sh run`のように変更しましたが結果は変わりませんでした。
どうしたら良いでしょうか？

**Comment by uchan-nos** [comment]
うーん、難しいですね。
試しに osbook_day30f をチェックアウトして試しても同様になりますか？

その他に試せることとしては、main.cpp に書いてある `SetLogLevel(kWarn);` を `SetLogLevel(kDebug);` などとして、
どこまで進んでいるかを確認してみるとか、ですかね。

**Comment by BD-sheres** [comment]
osbook_day30fを実行しても同じ結果になりました。
SetLogLevel(kWarn); を SetLogLevel(kDebug);に変更しても結果は同じでした。

**Comment by uchan-nos** [comment]
> SetLogLevel(kWarn); を SetLogLevel(kDebug);に変更しても結果は同じでした。

同じ、というのは、画面の表示が「すべて全く同じ」ということですか？
画面の左側にメッセージがどばどばっと出てきませんか？
出てこないのであれば、 `SetLogLevel(kWarn);` を変更した後に上手くビルドができてないかもしれません。

**Comment by BD-sheres** [comment]
はい。全く同じでした。なのでprintk("a")を使ってプログラムがどこにあるか確認しました。ですが左側に文字はできてきませんでした。ビルドはprintk("a")が表示されたので問題ないとおもいます。

**Comment by uchan-nos** [comment]
言っていることがよく分かりません。
「プログラムがどこにあるか」って何のことですか？
どのディレクトリに入ってるかどうか、みたいな？

printk("a")は、結局、表示されなかったのか、表示されなかったのか、どっちですか？

**Comment by BD-sheres** [comment]
説明不足ですいません。
`
printk("a");
SetLogLevel(kWarn); 
printk("a");
`
のようにコードを設定しました。
そしたら
`welcome mikados
a
a `
のように出たと言うことです。

**Comment by uchan-nos** [comment]
なるほど。
であれば、その方法を用いて、どこまで処理が進んでいるか（= どこで処理が止まっているか）
を突き止めることができれば、問題解決の糸口となると思います。
すみませんが、私には原因が分からないので、これくらいしかアドバイスできません。

**Comment by BD-sheres** [comment]
自己解決しました。
c言語のビルドを行なっていなかったため出来なかったみたいです。
大変ご迷惑をおかけしまた。

**Comment by uchan-nos** [comment]
解決おめでとうございます。

もしよければ、このIssueを後で見た人の参考のために、
具体的に何をやって解決したかを教えていただけませんか？
「c言語のビルド」っていうのは、具体的には何をやったのですか？

**Comment by uchan-nos** [comment]
なるほど。参考になりました。解決してよかったです。
