### ISSUE TITLE
[質問]　P73.カーネルファイル作成中でのエラーについて

### ISSUE THREAD

**Issue by Oryzae-O** [uchan-nos/os-from-zero#102]
`$ clang++ -02 -Wall -g --target=x86_64-elf -ffreestanding -mno-red-zone -fno-exceptions -fno-rtti -std=c++17 -c  main.cpp`
このコード中の-02が「不明のオプション」,と返ってきます.
解決法をご教授願えないでしょうか.
補足といたしましては,MikanOSのソースコードはインストール済みです.
![2021-08-28](https://user-images.githubusercontent.com/82478436/131215364-b4b59b91-9fe1-43a9-8446-739abc1ab35d.png)

**Comment by takotakot** [comment]
ゼロではなく、オー、0 から O にするとどうなりますか？

**Comment by Oryzae-O** [comment]
ご指摘いただいたとおりにコマンド入力を行ったところうまくいきました.
ありがとうございました！
![2021-08-28 (1)](https://user-images.githubusercontent.com/82478436/131218564-f5f0914b-833d-4233-8ead-47804eebb9d0.png)
