### ISSUE TITLE
[質問]P.80　buildコマンドについて

### ISSUE THREAD

**Issue by Oryzae-O** [uchan-nos/os-from-zero#103]
これまで開発環境の準備からP80まで順番通りに操作してきたのですが,P.80でいきなり

`$ build `
上記のコマンドでコマンドが見つからないというエラーがでました.
(P.51でのMikanLoaderPkgのbuildは成功しました.)
指示以外の操作等は行っていないので原因が分かりません.
解決法と考えられる原因をご教授願えないでしょうか.
補足としましては, `edksetup.sh` は `$HOME edk2`にありました.
![2021-08-29](https://user-images.githubusercontent.com/82478436/131251880-afe83e49-4730-4ad9-9797-a5505ba1b82b.png)

**Comment by uchan-nos** [comment]
EDK IIで build コマンドを使うときは事前に `source edksetup.sh` が必要ですが、実行していますか？
（p.51 の脚注 5 を参照）

**Comment by Oryzae-O** [comment]
実行していませんでした.
改めて`$ source edksetup.sh`を実行してから`$build`してみるとビルドに成功しました.
![2021-08-31](https://user-images.githubusercontent.com/82478436/131489405-bc211119-25fa-4568-bc6b-546aac24047a.png)
ところで`$ source edksetup.sh`は`$build`を実行するときには毎回する必要があるのでしょうか？

**Comment by uchan-nos** [comment]
> ところで `$ source edksetup.sh` は `$build` を実行するときには毎回事前にしておく必要があるのでしょうか？

毎回というわけではありません。
正確にいうと、ターミナルを閉じて開いたら実行する必要があります。
ターミナルを閉じずに使い続ける間は `build` は実行しなくて大丈夫です。

**Comment by Oryzae-O** [comment]
お答えいただきありがとうございました！
