### ISSUE TITLE
[質問]P.83　図3.7の表示方法について

### ISSUE THREAD

**Issue by Oryzae-O** [uchan-nos/os-from-zero#104]
ここまでP.80のブートローダのビルド＆カーネルの起動までの作業は済ませたのですが,図3.7のようなウィンドウを出すことができません.
 P.80のブートローダのビルドのコマンドでリスト3.6のビルドは完了していると思うのですが,
`$ $HOME/osbook/devenv/run_qemu.sh Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi \ $HOME/workspace/mikanos/kernel.elf`
上記のコマンドを実行してもウィンドウは黒いままでした.
どうか解決法をご教授願えないでしょうか.
また,リスト3.1の表題についている（main.cpp)やリスト3.2についている（Main.c）というのは,それぞれカーネルとブートローダのプログラム内容という認識でよかったでしょうか.

**Comment by uchan-nos** [comment]
この情報だけでは何とも分からないので、run_qemu.sh 実行時のログを見せていただけますか？
それから、表示されるウィンドウ（黒いままのウィンドウ）のスクリーンショットも貼り付けてください。

> リスト3.1の表題についている（main.cpp)やリスト3.2についている（Main.c）というのは,それぞれカーネルとブートローダのプログラム内容という認識でよかったでしょうか.

はい。その通りです。
リストの表題にある「（ファイル名）」は、リストで示すソースコードがどのファイルに書かれたものであるかを示しています。

**Comment by Oryzae-O** [comment]
> はい。その通りです。
リストの表題にある「（ファイル名）」は、リストで示すソースコードがどのファイルに書かれたものであるかを示しています。
ありがとうございます.

それから画像はこちらになります.
![2021-09-02 (3)](https://user-images.githubusercontent.com/82478436/131817499-4d4b34f1-3671-48b5-9e69-69d72cac6e9c.png)
![2021-09-02 (4)](https://user-images.githubusercontent.com/82478436/131817511-d8284b46-e91d-4540-a9fb-61a4716b66ee.png)

**Comment by uchan-nos** [comment]
図 3.7 で画面が白くなっているのはブートローダーで塗りつぶしているからなので、
おそらくブートローダーのビルドが上手くできていないと思います。

まっさらな状態にするために、いったん Build/MikanLoaderX64 を削除してから build したらどうでしょうか。
こんな感じで。

```
$ cd $HOME/edk2
$ rm -r Build/MikanLoaderX64
$ build
```

**Comment by Oryzae-O** [comment]
指示通りにコマンド実行を行ったのですが,変化なしでした.
![2021-09-02 (5)](https://user-images.githubusercontent.com/82478436/131821634-758696da-ed7a-4305-8b40-fcb32861f06e.png)
それから現状でのMain.cppとMain.cの状態が気になりVisual Studio で閲覧してみたところ,それぞれリスト3.1とリスト3.5のところでストップしていたのですが,これに関しては問題には関係なかったでしょうか？
Main.cpp
![2021-09-02 (1)](https://user-images.githubusercontent.com/82478436/131822653-bfb9f4f5-926c-4113-8ca3-274db454ef80.png)
Main.c
![2021-09-02 (2)](https://user-images.githubusercontent.com/82478436/131822761-96786c37-ba17-4cbb-9530-001f7c6d7c17.png)

**Comment by uchan-nos** [comment]
図 3.7（osbook_day03b）では、main.cpp の方はリスト 3.1 から変化がありませんから問題ありません。
Main.c はリスト 3.6 で更新していますので、リスト 3.5 のままでは変化が無いのは当たり前ですね。
リスト 3.6 が「画面を白く塗りつぶす」ためのプログラムですから。

ブートローダーを build する前に、ちゃんと git checkout osbook_day03b してくださいね。

**Comment by Oryzae-O** [comment]
ご指摘どおりP.80の実行コマンドの`osbook_day03a`の部分を`osbook_day03b`に差し替えてみたところ無事図3.7を出すことができました.
ありがとうございます！
![2021-09-02 (6)](https://user-images.githubusercontent.com/82478436/131843486-b97739c3-cf2c-4d55-8f28-bbabe1e8545b.png)
それと,もしかしてなのですが,このあとも「3.4 ブートローダからピクセルを描く」のように実行コマンドを省略されているのでしょうか？

**Comment by uchan-nos** [comment]
> それと,もしかしてなのですが,このあとも「3.4 ブートローダからピクセルを描く」のように実行コマンドを省略されているのでしょうか？

はい。同じような開発の流れになっていくので、毎回同じコマンドを記載するのも無駄だと思い、省略してあります。
基本は「git checkoutでビルドしたいバージョンを取ってきて、カーネルとブートローダーをビルドする」という流れを毎回やってください。

**Comment by Oryzae-O** [comment]
承知いたしました！
ありがとうございます！！
