### ISSUE TITLE
[質問] P.85 図3.8の表示方法について

### ISSUE THREAD

**Issue by Oryzae-O** [uchan-nos/os-from-zero#105]
P.84、85のコマンドはすべて実行したのですが,カーネルの起動コマンドが分かりませんでした.
`$ $HOME/osbook/devenv/run_qemu.sh Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi \ $HOME/workspace/mikanos/kernel.elf`
一応P.80にあった上記のコマンドを実行してみたのですが,P.84、85のコマンド実行前と変化がなかったのでお手上げ状態です.
![2021-09-02](https://user-images.githubusercontent.com/82478436/131773189-ad7a8d8b-103a-4734-a7c4-f37c7cea89df.png)
どうか解決法をご教授願えないでしょうか.

**Comment by uchan-nos** [comment]
Oryzae-O さんは連続で質問を投稿されていますね。
混乱しそうなので、似たような質問は 1 つずつ解決してから次に進めて行きたいと思います。
まずは #104 から片付けましょうか。

**Comment by Oryzae-O** [comment]
承知いたしました!
