### ISSUE TITLE
[質問]makeコマンドとbuildコマンドの違いについて

### ISSUE THREAD

**Issue by Oryzae-O** [uchan-nos/os-from-zero#107]
「5.1文字を書いてみる」において
`$ cd $HOME/workspace/mikanos`
`$ git checkout osbook_day05a`
`$ cd $HOME/edk2`
`$ source edksetup.sh`
`$ build`
上記のコマンドを実行した後,QEMUを実行してカーネルを起動したのですが,
フォントが描画されませんでした.
そこで追加で以下のコマンドを実行してみました.
`$ source $HOME/osbook/devenv/buildenv.sh`
`$ cd $HOME/workspace/mikanos/kernel`
`$ make`
すると図5.2のようにフォントが描画されました.
今回の操作において`$ build`を実行する必要はありましたでしょうか？
また,`$ make`と`$ build`ではどのような違いがあるのでしょうか？
備考としましては,このような記事を見つけました.
[https://qiita.com/Rowing0914/items/588d3466f36f32bab0df](url)
[https://qiita.com/yizumi1012xxx/items/cc1fb7b21ead4d20dcef](url)
しかし,どちらの解説でも今回のように`$ build`ではできず,`$ make`で成功した理由を説明できなかったです.
どうかこのことについてご教授願えないでしょうか.

**Comment by uchan-nos** [comment]
> また,$ makeと$ buildではどのような違いがあるのでしょうか？

make は make という一般のコマンド呼び出しです。
make コマンドは Makefile を読み取って、その指示通りの作業を行います。
Makefile に書いてあることによって処理の内容が変わります。

今回のケースでは `$HOME/workspace/mikanos/kernel/Makefile` を使います。
この Makefile には MikanOS のカーネルをビルド（コンパイル & リンク）するように指示が書いてあります。

一方、build は一般のコマンド名ではなく、EDK II が提供するものです。
EDK II 内のプログラムをビルド（コンパイル & リンク）します。
MikanOS では、ブートローダーのビルドに使っています。

**Comment by uchan-nos** [comment]
> 「5.1文字を書いてみる」において
> 《中略》
> 上記のコマンドを実行した後,QEMUを実行してカーネルを起動したのですが,
> フォントが描画されませんでした.

そうですね。
EDK II の build コマンドを実行しただけではカーネル側が更新されませんから、当然そうなります。

**Comment by Oryzae-O** [comment]
ご返信ありがとうございます.

> `$ make`コマンドはMakefileに書かれている指示に従ってカーネルをビルドする.

> `$ build`コマンドはEDK Ⅱによってブートローダーをビルドする.
uchan-nos様のおかげで,これらのことは理解できたのですが
なぜカーネルとブートローダーではビルド方法を変えているのでしょうか？
出力先の違いでしょうか？オプションの違いでしょうか？
どうかご教授願えないでしょうか.

**Comment by uchan-nos** [comment]
EDK II を使ってアプリケーションを作る場合は EDK II が用意する仕組みを使うのが楽なので build を使っています。
EDK II と関係ないところでカーネルをビルドするには自前でやる必要があるため、私が使い慣れている make を使いました。

**Comment by Oryzae-O** [comment]
つまり,
カーネルのビルドはEDK Ⅱ内ではビルドすることができない,
もしくは,
ユーザーが予め設定したソースコードⅠ種類しかビルドできない,
ということでしょうか？

**Comment by Oryzae-O** [comment]
承知いたしまいした.
ありがとうございました！
