### ISSUE TITLE
[質問]重ね合わせ処理導入以降に発生したバグについて

### ISSUE THREAD

**Issue by Oryzae-O** [uchan-nos/os-from-zero#108]
`$ git checkout osbook_day09a`
`$ make`
P204までの操作では問題なかったのですが
上記のコマンドを実行してからQEMUを起動した時の挙動がおかしくなりました.
とりあえず説明がしづらいので以下の動画をご覧ください.
https://user-images.githubusercontent.com/82478436/132497021-5733c69c-0cbe-4acd-82e2-1498f35acc05.mp4
補足としまして,
こちらの動画はosbook_day09cまでを`$make`したものです.
しかしosbook_day09aを`$make`したときから同じ状態になりました.
起動してから約7秒ほどで再起動？を繰り返しております.
そしてそれまではあった大きめの白色カーソルも消滅しております.
また,黒色カーソルでスタートメニューや文字の上を通過した場合はこれまでのようには崩れませんでした.
どうか解決法をご教授願えないでしょうか.
[追記]
osbook_day09dを`$make`したときのQEMUの挙動です.
https://user-images.githubusercontent.com/82478436/132509803-7333b613-f890-49c2-a598-e89a8519d7b3.mp4
osbook_day09eを`$make`したあとに`$ build`したときの挙動です.
https://user-images.githubusercontent.com/82478436/132519044-b4bf75ef-6b83-415f-a50e-de5828eb2088.mp4
問題は解決しました.
しかし,
なぜこのようなバグが発生した理由が分かりません.
考えられる要因をご教授願えないでしょうか.

**Comment by Oryzae-O** [comment]
ご指摘いただいたことから改めてカーネルの挙動がおかしくなったときのソースコードの拡張子を確認したところ
`.c`・`.cpp`・`hpp`でしたが,それぞれブートローダー・カーネル・.cppの一部という認識でよろしかったでしょうか？
だとすると,osbook_day09aのビルド時には`$ build`コマンドは実行しなかったのでおそらく原因は uchan-nos様の推察通りだと思われます.
今後の作業の助けになります.ありがとうございます.
しかしまだいくつか分からないことがあるので質問させてください.
`.asm`・`.h`これらの拡張子のソースコードをビルドするときは`$ build`または`$ make`どちらでビルドすればいいでしょうか？
また,これらの拡張子のファイルは何を表しているのでしょうか？

**Comment by uchan-nos** [comment]
> .c・.cpp・hppでしたが,それぞれブートローダー・カーネル・.cppの一部という認識でよろしかったでしょうか？

まあその通りなのですが、正確にはファイルの拡張子ではなく、ファイルがどのディレクトリに入っているかで判断してください。
MikanLoaderPkg に入っているファイルはブートローダー、kernel に入っているファイルはカーネルです。

> .asm・.hこれらの拡張子のソースコードをビルドするときは$ buildまたは$ makeどちらでビルドすればいいでしょうか？

.h および .hpp については、.h/.hpp を利用している .c/.cpp をコンパイルする際に自動的にコンパイルされます。
.h/.hpp は、.c/.cpp をコンパイルする際に .c/.cpp と結合され、その一部となってコンパイルされるのです。
.h/.hpp のことを「ヘッダファイル」と呼びます。結合する機能を「インクルード」と言います。
この辺がよく分からないのでしたら、C 言語や C++ 言語の教科書を読んで勉強してください。

.asm は kernel に含まれるファイルです。したがって make でビルドします。
アセンブラ用のソースコードです。

**Comment by Oryzae-O** [comment]
丁寧に教えていただきありがとうございました！

> この辺がよく分からないのでしたら、C 言語や C++ 言語の教科書を読んで勉強してください。

今後とも精進して学んでいきます！！！
