### ISSUE TITLE
[質問]　P422　Gitエラーへの対処について

### ISSUE THREAD

**Issue by Oryzae-O** [uchan-nos/os-from-zero#109]
`$ source $HOME/osbook/devenv/buildenv.sh`
`$ cd $HOME/workspace/mikanos/apps/onlyhlt`
`$ git checkout osbook_day18b`
上記のコマンドを実行したのですが
`error: The following untracked working tree files would be overwritten by checkout:
        build.sh
Please move or remove them before you switch branches.
Aborting`
このようなエラーが発生しました.
![2021-09-21](https://user-images.githubusercontent.com/82478436/134168624-4fdd99bf-2051-4c6e-886f-4cec096c2bec.png)
この場合`$ rm build.sh`を実行してもいいでしょうか？
build.shが何のファイルかわからないため実行できずにいます.
ちなみにディレクトリで確認したところbuild.shファイルは
`$HOME\workspace\mikanos\build.sh`（347バイト）
`$HOME\edk2\OvmfPkg\build.sh`（5.92KB）
`$HOME\edk2\EmulatorPkg\build.sh`（5.99KB）
`$HOME\osbook\devenv_src\stdlib\build.sh`（1.12KB）
が存在していました.

**Comment by uchan-nos** [comment]
build.sh は $HOME/workspace/mikanos/build.sh のことじゃないかと思います。
なぜなら osbook_day18a → osbook_day18b でそのファイルが追加されているためです。

上記の Git エラーメッセージは「Git の管理下にない build.sh というファイルがあるが、
今実行しようとした git checkout によって同名のファイルが作成されようとしており、
上書きされてしまいますよ、だから git checkout を中止します」と言っています。

そのエラーがなぜ表示されているのかは分かりません。
偶然、そういう名前のファイルを作ってしまったか、どこかからコピーしてきたか、
そういう事故が起きたんじゃないかと思います。

そのファイルを消して良いかどうかは Oryzae-O さんしか判断できません。
中身を確認していただき、消して良いなら rm で消し、ダメなら mv でどこか他の場所に移動するなどしてください。

**Comment by Oryzae-O** [comment]
返信が遅れてしまい申し訳ございません.
確認してみたところ削除しても問題なさそうだったので,
`$rm build.sh`を実行してから,
指示通りにコマンドを実行していったところ,
うまくいきました,
ありがとうございます.
ところで,ターミナルでonlyhltを実行したときに起きる動作は,
カーネルがhltの無限ループをしていることが原因でしょうか？

**Comment by uchan-nos** [comment]
解決して良かったです

> ところで,ターミナルでonlyhltを実行したときに起きる動作は,
> カーネルがhltの無限ループをしていることが原因でしょうか？

はい、その通りです。
元々の質問は解決しているので Close します。
さらに質問があれば別の Issue にしてください。

**Comment by Oryzae-O** [comment]
ありがとうございました.
