### ISSUE TITLE
誤植：初版第1刷 p.399

### ISSUE THREAD

**Issue by kamecha** [uchan-nos/os-from-zero#110]
p.399 ４つコマンドが並んでいる箇所

上から３番目
誤：`$ sudo cp HelloWorld.data mnt/HeloWorld.data`

正：`$ sudo cp HelloWorld.data mnt/HelloWorld.data`

Helloのlがあったほうが適切だと思います。

勘違いだったらすみません

**Comment by uchan-nos** [comment]
ご報告ありがとうございます。

そうなんですよ。私もそこに気付いて HelloWorld.data に直したかったのです。可能であれば。
しかし、その後ろの hexdump の結果にも HeloWorld.data のまま実験したデータが載ってますし、
その他の箇所も軒並み l 抜きでデータを作ってしまっていたので、修正しないことにしました。

ということで、これは誤植ではなく仕様です。
