### ISSUE TITLE
付録A　開発環境のインストールについて

### ISSUE THREAD

**Issue by hentaihusinsya** [uchan-nos/os-from-zero#112]
環境：OS : Ubuntu 18.04.6LTS
　　　Processor : Intel® Core™ i7-9750H CPU @ 2.60GHz × 12 
          Grapthics : Intel® UHD Graphics 630 (CFL GT2)

下記URLで開発ツールを導入していた時にエラーを吐いてしまいました
https://github.com/uchan-nos/mikanos-build#%E9%96%8B%E7%99%BA%E3%83%84%E3%83%BC%E3%83%AB%E3%81%AE%E5%B0%8E%E5%85%A5

エラー内容**↓**
![Screenshot from 2021-10-04 15-26-06](https://user-images.githubusercontent.com/88319444/135803742-634d32e0-e79f-4d48-b44e-6b50f26b8f1f.png)

自分以外にも似たようなところで詰まっている方々はいましたが環境が違ったり、エラーの内容が微妙に違ってよくわかりません。足りない情報があれば言ってください。

**Comment by MunehiroYoshida** [comment]
私の場合は、最後の最後、”ansible-playbook -ｋ -i ansible_inventory ansible_provision.yml”のコマンドを打ち込んだあと
SSHのパスワード入力を求められて、パスワードがわからず、行き詰まってます。パスワードは何でしょう？

**Comment by uchan-nos** [comment]
ちょっと分からないですが、エラーメッセージにある通り「sudo apt-get update」を先に実行してみたらどうなりますか？

**Comment by uchan-nos** [comment]
何か進展して、また質問がありましたらリオープンするか、新規にIssueを投稿していただければと思います。
