### ISSUE TITLE
(質問)ブートローダーのビルドでbuildを実行したらエラーが出ました

### ISSUE THREAD

**Issue by nittako1414** [uchan-nos/os-from-zero#114]
ubuntuでbuildを実行したら以下のエラーが出てしまいました。
色々と調べてみたのですが解決方法がわかりません。

(エラー内容)
<img width="1432" alt="スクリーンショット 2021-10-16 18 24 48" src="https://user-images.githubusercontent.com/88404807/137582854-f57e33c6-58f0-4928-b28b-37bdfd7a0a9e.png">
<img width="1435" alt="スクリーンショット 2021-10-16 18 25 21" src="https://user-images.githubusercontent.com/88404807/137582856-5a4d6a23-d34a-433e-bdad-13d2374fdd99.png">

**Comment by uchan-nos** [comment]
@nittako1414 すみません。投稿に気付いていませんでした。
edk2 は手動で git clone したものでしょうか？
その場合、--recursive オプションを付けて clone する必要があるかもしれません。
一旦 edk2 ディレクトリを削除し、https://github.com/uchan-nos/os-from-zero/issues/45#issuecomment-819952506
で紹介されているコマンドで clone してみてもらえますか。

**Comment by nittako1414** [comment]
@uchan-nos 
ありがとうございます。buildできました！

**Comment by uchan-nos** [comment]
良かったです。ではIssueはクローズします

**Comment by yuzu-krs** [comment]
![スクリーンショット 2023-03-20 205616](https://user-images.githubusercontent.com/89998242/226332436-9525745d-457d-400d-9198-92474f35ae2b.png)

P.51のbuildはできているのですが，Loader.efiが生成されません．

ubuntu 20.04です
