### ISSUE TITLE
QEMUで、意図した通りに出力できない

### ISSUE THREAD

**Issue by snegishi** [uchan-nos/os-from-zero#115]
環境
・Windows 10 Pro
・WSL2
・（WSL上の）Ubuntu 20.04 
・VcXsrv

の下で、以下の画像内のように、
`run_qemu.sh hello.efi`
を実行したところ
`Guest has not initialized the display (yet).`
と表示されます。

どのようにしたら、正しく出力できるようになるでしょうか？

![無題2](https://user-images.githubusercontent.com/5731384/140595614-5c86dc87-e36a-4eb4-9011-b4ae9fd9eef1.png)

**Comment by uchan-nos** [comment]
WSL から VcXsrv への通信、および QEMU の起動は上手くいっているようなので、
考えられる可能性はこんな感じでしょうか。

1. hello.efi が実は何もしない（画面に何も表示しない）プログラムなので、これが正しい実行結果である
2. hello.efi のプログラミングが間違えている
3. その他、私が思いつかない原因がある

1, 2 についての可能性はありますか？

**Comment by snegishi** [comment]
返信コメント、ありがとうございます。

$HOME/osbook/day01/c/hello.cを元に作成したhello.efiであり、
1,2の可能性は低いと考えています。

なお、
`$ ~/osbook/devenv/run_qemu.sh BOOTX64.EFI`
を実行しても同じ出力となります。

**Comment by uchan-nos** [comment]
不思議ですね。

他の人の環境で実験することで snegishi さんの環境固有の現象かどうかを切り分けできると思いますので、
hello.efi を添付していただくと良いかと思います。

**Comment by snegishi** [comment]
zipで固めて、添付させていただきました。
[hello.zip](https://github.com/uchan-nos/os-from-zero/files/7533637/hello.zip)

**Comment by snegishi** [comment]
合わせて、BOOTX64.EFIも添付させていただきます。
[BOOTX64.zip](https://github.com/uchan-nos/os-from-zero/files/7533641/BOOTX64.zip)

**Comment by uchan-nos** [comment]
手元の WSL2 で起動させてみたところ、ちゃんと hello world が表示されました。

![hello.efiの起動画面](https://user-images.githubusercontent.com/1825663/141710966-ecca0387-06e8-4826-a34a-4ad3cc3f49e3.png)

環境は以下の通り
- Windows 11
- WSL2 + Ubuntu 20.04

X 環境は WSL2 付属のもの（WSLg）なので、VcXsrv を用いたものと差異はありますが、
あくまで QEMU の画面表示に関する部分が多少違うだけなので、QEMU の動作には差が無いはずです。

**Comment by uchan-nos** [comment]
@snegishi 
snegishi さんの環境固有の問題が何か起きているのだろうと思います。
何が原因なのかさっぱり分かりませんが。

試しに QEMU モニタのプロンプトで info register コマンドを実行し、RIP の値を見てみますか。
私の環境では、"Guest has not initialized the display (yet)" が表示されているときは次のような結果になり、

```
(qemu) info registers
《中略》
RIP=000000003fb778e1 RFL=00000206 [-----P-] CPL=0 II=0 A20=1 SMM=0 HLT=1
```

hello world が表示された後は次のような結果になりました。

```
(qemu) info registers
《中略》
RIP=000000003e66103f RFL=00000206 [-----P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
```

info registers を複数回打ってみて、RIP の値がずっと変わり続けていたらプログラムが暴走していることが分かります。
RIP の値が上記の値とずれた場所で安定するようなら、意図しない場所でフリーズしてることが分かります。

**Comment by snegishi** [comment]
info registers を複数回打ってみたところ、以下の場所で安定していました。
```
(qemu) info registers
《中略》
RIP=000000003feae60f RFL=00000246 [---Z-P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
```

**Comment by uchan-nos** [comment]
私の結果とは異なる RIP で止まってるようですね。
これはかなり根深い原因がある予感がします。腰を据えた検証が必要かも……

ということで、本格的な検証の第一歩として 3feae60f がどこなのかを特定してみたいですね。
hello.efi に含まれるプログラムなのか、その外側なのか。

QEMU モニタで `x /20i 0x3feae60f` を実行した結果を知りたいです。

**Comment by tenpoku1000** [comment]
QEMU で利用している OVMF に問題がある場合もあるかと思います。OVMF のビルド手順の Qiita 記事も書いておきます。

第592回　QEMUでGPUの3Dアクセラレーションを利用する：Ubuntu Weekly Recipe｜gihyo.jp … 技術評論社 
https://gihyo.jp/admin/serial/01/ubuntu-recipe/0592
```
OVMFを利用したUEFIモードで起動した場合も，3D GPUを利用可能です。
ただし，Ubuntu 19.10のOVMFイメージはVGAを利用できない問題が存在します。
具体的には起動時にディスプレイ画面に「Guest has not initialized the display (yet).」と表示されるのです。
問題となるのは「/usr/share/ovmf/OVMF.fd」だけです。「⁠/usr/share/OVMF/OVMF_CODE.fd」
と「/usr/share/OVMF/OVMF_VARS.fd」は問題ありませんので，そちらを使うようにしてください。
2020年4月にリリース予定のUbuntu 20.04 LTSでは修正されている見込みです。
```
Ubuntu Desktop で OVMF と QEMU をソースコードからビルドする - Qiita
https://qiita.com/tenpoku1000/items/603e97b0ee8b75d69f0e

**Comment by snegishi** [comment]
実行してみました。
```
(qemu) x /20i 0x3feae60f
0x3feae60f:  48 83 7c 24 38 00        cmpq     $0, 0x38(%rsp)
0x3feae615:  74 f8                    je       0x3feae60f
0x3feae617:  48 81 c4 48 01 00 00     addq     $0x148, %rsp
0x3feae61e:  c3                       retq
0x3feae61f:  56                       pushq    %rsi
0x3feae620:  57                       pushq    %rdi
0x3feae621:  48 83 ec 28              subq     $0x28, %rsp
0x3feae625:  48 89 d6                 movq     %rdx, %rsi
0x3feae628:  48 89 cf                 movq     %rcx, %rdi
0x3feae62b:  48 85 ff                 testq    %rdi, %rdi
0x3feae62e:  75 74                    jne      0x3feae6a4
0x3feae630:  f8                       clc
0x3feae631:  48 81 c4 48 48 81 c3     addq     $-0x3c7eb7b8, %rsp
0x3feae638:  56                       pushq    %rsi
0x3feae639:  57                       pushq    %rdi
0x3feae63a:  48 83 ec 28              subq     $0x28, %rsp
0x3feae63e:  56                       pushq    %rsi
0x3feae63f:  57                       pushq    %rdi
0x3feae640:  48 48 89 d6              movq     %rdx, %rsi
0x3feae644:  48 48 89 cf              movq     %rcx, %rdi
```

**Comment by uchan-nos** [comment]
これは、hello.efi にはない機械語なので、やはり hello.efi に処理が行く前で止まってるんだと思います。

hello.efi の機械語はこうなってます。
```
$ objdump -d hello.efi

hello.efi:     file format pei-x86-64


Disassembly of section .text:

0000000140001000 <.text>:
   140001000:   48 83 ec 48             sub    $0x48,%rsp
   140001004:   48 89 54 24 38          mov    %rdx,0x38(%rsp)
   140001009:   48 89 4c 24 30          mov    %rcx,0x30(%rsp)
   14000100e:   48 8b 4c 24 38          mov    0x38(%rsp),%rcx
   140001013:   48 8b 49 40             mov    0x40(%rcx),%rcx
   140001017:   48 8b 49 08             mov    0x8(%rcx),%rcx
   14000101b:   48 8b 54 24 38          mov    0x38(%rsp),%rdx
   140001020:   48 8b 52 40             mov    0x40(%rdx),%rdx
   140001024:   48 89 4c 24 28          mov    %rcx,0x28(%rsp)
   140001029:   48 89 d1                mov    %rdx,%rcx
   14000102c:   48 8d 15 cd 0f 00 00    lea    0xfcd(%rip),%rdx        # 0x140002000
   140001033:   48 8b 44 24 28          mov    0x28(%rsp),%rax
   140001038:   ff d0                   callq  *%rax
   14000103a:   48 89 44 24 20          mov    %rax,0x20(%rsp)
   14000103f:   e9 fb ff ff ff          jmpq   0x14000103f
```

アセンブリ命令（`mov` など）が QEMU の表示と一致していないので、hello.efi の中で止まっているのではない、と判断しました。左列にあるアドレスはとりあえず無視してます。

さて、なぜこうなるかはよく分かりません。tenpoku さんが指摘するような OVMF に問題がある説は、今回は当てはまらないと思います。なぜなら mikanos-build で配布している OVMF をちゃんと使っているように見えるからです。

今のところ、私はお手上げ状態です。

**Comment by rkarsnk** [comment]
このissueはもう解決したのかな？

```
Guest has not initialized the display (yet).
```

この表示が出た後に、TianoCoreというロゴマークが表示されると思うのですが、そこまで到達していませんか？

**Comment by tenpoku1000** [comment]
もし、デスクトップ PC で GPU カードを使っていて 内蔵 GPU があるなら、
内蔵 GPU で PC を動かしてみると改善するかもしれません。

**Comment by miyataka** [comment]
類似事象が起きたので報告だけしておきます．
自分の場合は，`$HOME/osbook/devenv/OVMF*` に意図していない差分が発生していたため，それをgit checkoutで戻すことにより解決しました．

https://github.com/miyataka/zero_os/issues/2

**Comment by koyo-snow** [comment]
同じ画面が出ましたが、
emu-system-x86_64 -drive if=pflash,format=raw,file=bios.bin -enable-kvm
としたら、起動できました。
-enable-kvmが重要だったみたいです。

本はまだ最後まで確認していません。

**Comment by koyo-snow** [comment]
下記忘れていました。
公式チュートリアルをもとにした話で、さらにLinux Mintの話です。。。
VirtualBoxのUbuntu22.04では、kvmをインストールしたあとに
設定>システム>プロセッサー>ネステッドVT-x/AMD-Vを有効化
で表示されました。
ここの議題のWSLについては、Windowsを持っていないのでわかりません。。。

本の話ではありませんが、私と同じケースで動かない人の参考になれば。
