### ISSUE TITLE
付録ＥのiPXEのmakeでエラー

### ISSUE THREAD

**Issue by AkiraKano** [uchan-nos/os-from-zero#116]
書籍に沿った開発環境の作成で次のisolinux.binが見付からない旨のエラーが発生しました
できればiPXEを使った形での開発をしたいと考えています
  [GENFSIMG] bin/ipxe.iso
util/genfsimg: could not find isolinux.bin
make: *** [arch/x86/Makefile.pcbios:61: bin/ipxe.iso] Error 1

開発環境はWSL2＋ubuntu20.043 LTSです
対処方法をご教示下さい

**Comment by uchan-nos** [comment]
ちょっと情報が少なくて分からないので追加で情報をください。

1. 実行したコマンド
2. 使用した Git のコミット ID（`git log | head -1` で出せます）

**Comment by AkiraKano** [comment]
ご返事が遅れて申し訳ありません
実行したコマンドが誤っていた事が判明し、付録Ｅの手順に沿って再度実行したところ正常に実行ファイルを作成できました
お手数をおかけしてしまった事お詫びしますと共にご対応いただき有難うございました

**Comment by uchan-nos** [comment]
解決したようなのでクローズします
