### ISSUE TITLE
2章，edk2を用いたビルドにおけるエラー 

### ISSUE THREAD

**Issue by gondoumasayuki** [uchan-nos/os-from-zero#117]
実行環境
virtualbox
kali linux 202103

当初，以下の結果のようにエラー4000が出ていたが，あるサイトにedkのバージョンを古くすると
上手くいくということでバージョンを変更しました．

![step1_new](https://user-images.githubusercontent.com/42734692/145225932-5d50bf9b-8aee-410d-8b2f-e225146038c0.PNG)

すると，以下のようなエラーに変わりました．
![step2_new](https://user-images.githubusercontent.com/42734692/145225881-a1e7d3b3-93b7-4571-a340-da71599ca0ad.PNG)

さらにansibleも使うようなことを書かれていたのでそちらについても実行したところ，これもまたエラーが発生し，
python-aptが必要と言うことであったがそもそもインストールできず代わりにpython3-aptをインストールしたが，
これでもエラー表記が変わリませんでした．

![step3_new](https://user-images.githubusercontent.com/42734692/145226622-f6fc0faf-016c-4d40-a447-a4514d09744b.PNG)

このような状況で全く先に進めておりません．

**Comment by rkarsnk** [comment]
Loader.infに
```

[LibraryClasses]
  UefiLib
  UefiApplicationEntryPoint
  RegisterFilterLib   <-追記

[Guids]
  gEfiFileInfoGuid

```
LoderPkg.dscに
```
#@range_end(library_classes)

  BaseLib|MdePkg/Library/BaseLib/BaseLib.inf
  BaseMemoryLib|MdePkg/Library/BaseMemoryLib/BaseMemoryLib.inf
  DebugLib|MdePkg/Library/BaseDebugLibNull/BaseDebugLibNull.inf
  DevicePathLib|MdePkg/Library/UefiDevicePathLib/UefiDevicePathLib.inf
  MemoryAllocationLib|MdePkg/Library/UefiMemoryAllocationLib/UefiMemoryAllocationLib.inf
  PcdLib|MdePkg/Library/BasePcdLibNull/BasePcdLibNull.inf
  PrintLib|MdePkg/Library/BasePrintLib/BasePrintLib.inf
  UefiBootServicesTableLib|MdePkg/Library/UefiBootServicesTableLib/UefiBootServicesTableLib.inf
  UefiRuntimeServicesTableLib|MdePkg/Library/UefiRuntimeServicesTableLib/UefiRuntimeServicesTableLib.inf
  RegisterFilterLib|MdePkg/Library/RegisterFilterLibNull/RegisterFilterLibNull.inf  <-追記

#@range_begin(components)
[Components]

```
のように追記して、試してみてください。

**Comment by gondoumasayuki** [comment]
すみません，現在確認したところ以下のようなエラーが発生しました．

<img width="470" alt="キャプチャ" src="https://user-images.githubusercontent.com/42734692/145586494-d237e078-66c1-475b-9c6e-0246ef8d03b5.png">

ansibleをインストールできていないことに起因するのでしょうか

**Comment by gondoumasayuki** [comment]
buildについてはmake -C　~~/C ができないことが最大の原因のようだったので，これが動くバージョンで[114の記事](https://github.com/uchan-nos/os-from-zero/issues/114#issuecomment-963722667)があったため，ひとまずこの方法でmakeした後，バージョンを4ac0296に戻し，buildした結果，無事に実行できました．

makefileの詳細を見れてはいないのですが，これはbuildした結果がクローンしたディレクトリ外に置かれる為これで通ったのでしょうか．加えてansibleについてはこれを使えばセットアップが楽という存在だったので，現在インストールは保留しています．

**Comment by rkarsnk** [comment]
>makefileの詳細を見れてはいないのですが，これはbuildした結果がクローンしたディレクトリ外に置かれる為これで通ったのでしょうか．
質問の意図がよくわからないので、もうすこし詳しく書いてください。
「何の」Makefileのことで、「何を」buildした結果が「どの」ディレクトリ外に置かれたのか



>加えてansibleについてはこれを使えばセットアップが楽という存在だったので，現在インストールは保留しています．

Kali Linuxについては知識がないので、なんとも言えませんが、リポジトリで配布されているansibleのファイルは、Ubuntu 18.04で動作確認済みのものだそうです。

Ubuntu 20.04や、Debian 11などで利用するときは、自分の利用するOSに合わせて、ansible_provision.ymlの修正が必要です。

**Comment by gondoumasayuki** [comment]
メモ書きみたいに使っていてすみません．

>「何の」Makefileのことで、「何を」buildした結果が「どの」ディレクトリ外に置かれたのか
makefileはedk2/BaseTools/Source/C/にあるものですね．
なのでedk2ツールのものです．

buildについてはmakeのミスですね．makeした結果がedk2以下のディレクトリに配置されているのではなく，
edk2ディレクトリとは別に配置されているのかと思いました．checkoutによって別のバージョンに乗り換えてしまうため
(バージョン管理についてそこまで理解していないのでこうした差分(makeの結果)はそのまま残るのであれば，これは見当違いです)

> 自分の利用するOSに合わせて、ansible_provision.ymlの修正が必要です。
修正が必要そうなのですが，これがないと演習ができないということはなさそうなのでスキップしようとしています．

**Comment by uchan-nos** [comment]
ansible_provision.yml は開発環境のインストールや EDK II の git clone などを行うスクリプトになっています。
同等の開発環境を Ansible を使わずに構築することは可能ですので、ansible_provision.yml を必ずしも使う必要はありません。

**Comment by gondoumasayuki** [comment]
わかりました．ありがとうございます．

今後同じ状況の人が見やすいように一度まとめます．

最大の問題
edk2を用いたbuildができない
- ansible-playbookで実行エラー出るため実際の環境と異なる
- それに伴って生じるedk2を用いたbuildエラーの原因
   - 指定したライブラリクラスが存在しない
   - edk2/BaseTools/Source/C/ をビルドできない．(ライブラリが存在しない)

解決策
1. これが動く(ライブラリが存在する)バージョンで[114の記事](https://github.com/uchan-nos/os-from-zero/issues/114#issuecomment-963722667)make
→原因2を解決
2. ここで成功すればedk2のバージョンを4ac0296に戻し，build
→原因1を解決
