### ISSUE TITLE
ls コマンド (osbook_day17b) について

### ISSUE THREAD

**Issue by tanaken0528** [uchan-nos/os-from-zero#119]
初めてIssuesに投稿します。

専門学校でC,C#,Javaなどを学習しています。

lsコマンドを実行すると、何も表示されずに次のプロンプトが表示されるというエラーになる問題で困っています。
原因または解決策をご存知の方はいらっしゃいませんか。

P396~P409は成功しました。

私の行った手順は以下です。
(1) `$ cd ~/mikanos` 
(2) `$ git checkout osbook_day17b`
(3) `$ cd kernel`
(4) `$ source ~/osbook/devenv/buildenv.sh`
(5) `$ make`
(6) `$ cd ~/edk2`
(7) `$ source edksetup.sh`
(8) `$ ~/osbook/devenv/run_qemu.sh ~/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi $HOME/mikanos/kernel/kernel.elf`

原因を確かめるため、以下のようなテストを行ってみましたが、
問題の解決には至りませんでした。

(a) MIKAN OS をマウントしてから実行した
→上記と同じ結果になった

なお、私の環境は以下の通りです。
 ・ Windows10  VMware 上の Ubuntu
 ・ QEMU

検索エンジンで検索しましたが、解決に役立つ情報は見つかりませんでした。
このメーリングリストの過去ログも調べましたが、lsコマンドに関する話題は見つかりませんでした。

**Comment by uchan-nos** [comment]
手順7と8の間でMikanLoaderPkgのビルドをしてみてください。
ファイル読み込みに対応するために17.4節でブートローダーが更新されています。

**Comment by tanaken0528** [comment]
@uchan-nos 様

ありがとうございました。
無事、実行できました。

どこからか`$ build`を忘れていたみたいです。
