### ISSUE TITLE
日本語表示 (osbook_day28a) で「??」が表示されない件について

### ISSUE THREAD

**Issue by tanaken0528** [uchan-nos/os-from-zero#120]
Mikan OSで`cat jpn.txt`で「??」が表示されず英字のみ表示されるエラーで困っています。

![osbook_day28a-error](https://user-images.githubusercontent.com/96215977/147178789-8023c9b4-05c8-4596-abf3-bc3304654690.JPG)

原因または解決策をご存知の方はいらっしゃいませんか。

第27章までは成功しました。

私の行った手順は以下です。
(1) `$ cd ~/mikanos` 
(2) `$ git checkout osbook_day28a`
(3) `$ APPS_DIR=apps RESOURCE_DIR=resource ./build.sh run`

なお、私の環境は以下の通りです。
 ・ Windows10  VMware 上の Ubuntu
 ・ QEMU

検索エンジンで検索しましたが、解決に役立つ情報は見つかりませんでした。
過去ログも調べましたが、関係する話題は見つかりませんでした。

**Comment by uchan-nos** [comment]
@tanaken0528
うーん、謎ですね。

デバッグの方針として思いつくのは、こんな感じでしょうか
- `WriteUnicode()` の中の「?」を出力している箇所で無限ループさせてみる
- `WriteUnicode()` の中の「?」を出力している箇所で他の文字（「A」とか「_」とか）を表示してみる

無限ループする場合、処理は確実にそこを通っていることが判明します。
「?」以外の文字なら出るのなら「?」固有の問題ですね。（といっても、さらに深い謎に包まれるだけですが……）

**Comment by tanaken0528** [comment]
@uchan-nos 様

ご返信いただき誠にありがとうございます。

`WriteUnicode()` がどこに格納されているか見当たらないので教えていただきたいです。

**Comment by uchan-nos** [comment]
@tanaken0528 
書籍の p.651 リスト 28.1 に載ってます！

**Comment by tanaken0528** [comment]
@uchan-nos 様

こちらの環境でfont.cppのソースを見てみたのですが、`WriteUnicode()`に関するものが見当たりません。

以下にfont.cppのソースを掲載いたします。

/**
 * @file font.cpp
 *
 * フォント描画のプログラムを集めたファイル.
 */

#include "font.hpp"

extern const uint8_t _binary_hankaku_bin_start;
extern const uint8_t _binary_hankaku_bin_end;
extern const uint8_t _binary_hankaku_bin_size;

const uint8_t* GetFont(char c) {
  auto index = 16 * static_cast<unsigned int>(c);
  if (index >= reinterpret_cast<uintptr_t>(&_binary_hankaku_bin_size)) {
    return nullptr;
  }
  return &_binary_hankaku_bin_start + index;
}

void WriteAscii(PixelWriter& writer, Vector2D<int> pos, char c, const PixelColor& color) {
  const uint8_t* font = GetFont(c);
  if (font == nullptr) {
    return;
  }
  for (int dy = 0; dy < 16; ++dy) {
    for (int dx = 0; dx < 8; ++dx) {
      if ((font[dy] << dx) & 0x80u) {
        writer.Write(pos + Vector2D<int>{dx, dy}, color);
      }
    }
  }
}

void WriteString(PixelWriter& writer, Vector2D<int> pos, const char* s, const PixelColor& color) {
  for (int i = 0; s[i] != '\0'; ++i) {
    WriteAscii(writer, pos + Vector2D<int>{8 * i, 0}, s[i], color);
  }
}

**Comment by uchan-nos** [comment]
バージョンが古いので、osbook_day28aがcheckoutできてないと思います。
もう一度git checkoutを実施いただき、エラーなど表示されないことを確認ください。

**Comment by tanaken0528** [comment]
@uchan-nos 様

ご返信いただき誠にありがとうございます。

git checkoutしたところ以下のエラーが表示されました。

error: The following untracked working tree files would be overwritten by checkout:
	resource/jpn.txt
Please move or remove them before you switch branches.
Aborting

この場合どのようにすればよいでしょうか。

**Comment by uchan-nos** [comment]
そのエラーはこういう意味です：
「git の管理下にない resource/jpn.txt というファイルが、git checkout することにより上書きされちゃいますよ」

resource/jpn.txt をこの場所から無くせば git checkout ができるようになります。
単に消すか、消して困るファイルであればどこか別の場所に退避させてください。

**Comment by tanaken0528** [comment]
@uchan-nos 様

ありがとうございました。無事「??」表示できました。

![osbook_day28a](https://user-images.githubusercontent.com/96215977/149068860-079d5fe6-6aa3-45ec-aa98-fbe0fba62a42.JPG)

その後、osbook_day28bで日本語表示も出来るようになりました。

jpn.txtやnihongo.ttfを他へ移動させましたが、Mikan OS では どのようにファイルを取得しているのでしょうか。

**Comment by uchan-nos** [comment]
> jpn.txtやnihongo.ttfを他へ移動させましたが、Mikan OS では どのようにファイルを取得しているのでしょうか。

`git checkout osbook_day28a` によってこれらのファイルが生成されるのです。
でも、既に存在していたので上書きを防止するために生成されず、git checkout がエラーになっていた、ということです。

**Comment by tanaken0528** [comment]
@uchan-nos 様

ご返信いただき誠にありがとうございます。

現在、resourcesフォルダに fujisan.jpg,mikanos.txt,night.bmp,tokyost.jpg が存在していますが、今後の進めていく上でこれらのファイルも他へ移動しなければならないのでしょうか。

**Comment by tanaken0528** [comment]
@uchan-nos 様

お忙しい中、ご返信いただき誠にありがとうございました。
