### ISSUE TITLE
付録A 開発環境の導入について

### ISSUE THREAD

**Issue by Apo-2008** [uchan-nos/os-from-zero#121]
はじめまして
僕はLinuxをはじめて数ヶ月とたたない初心者です
本の付録Aに記載されていたurlを参考にしながら、環境構築をしていたのですが、
ansible-playbook -K -i ansible_inventory ansible_provision.yml
のところで
BECOME PASSWORD:
表示され、自分のユーザーのパスワードを入力したところエラーが出てしまいました
become passwordとはどのようなパスワードで、またどのように設定すればいいか、教えていただけると幸いです

**Comment by rkarsnk** [comment]
@Apo-2008 
自分自身のパスワードを入力するのが正です。

ansibleは、aptでパッケージをインストールするために権限昇格を行います。
その権限昇格を許可するために求められるのが、become passwordです。
権限昇格方法はデフォルトではsudoを利用するので、sudoを実行するユーザのパスワードを入力します。

パスワード入力後のエラーがどのようなものか記載がないので詳細が不明ですが、
仮にsudoに失敗しているのであれば、利用中のユーザが`sudo`グループに所属していないのかもしれません。

以下のコマンドで確認し、所属していない場合は、rootユーザで`vigr`, `vigr -s`で自分自身を`sudo`グループに追加してください。
```
$ id
uid=1000(rkarsnk) gid=1000(rkarsnk) groups=1000(rkarsnk),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),109(netdev),113(bluetooth),118(scanner)

gid=27のsudoグループに所属していることが確認できます。
```

**Comment by Apo-2008** [comment]
済みません
確認したのですが、sudoグループには所属しているようです。
打ったコマンドの内容とエラーメッセージを貼り付けておきます。

[my user name]:~/osbook/devenv$ ansible-playbook -K -i ansible_inventory ansible_provision.yml
BECOME password: 

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
[DEPRECATION WARNING]: Distribution ubuntu 21.10 on host localhost should use 
/usr/bin/python3, but is using /usr/bin/python for backward compatibility with 
prior Ansible releases. A future Ansible release will default to using the 
discovered platform python for this host. See https://docs.ansible.com/ansible/
2.10/reference_appendices/interpreter_discovery.html for more information. This
 feature will be removed in version 2.12. Deprecation warnings can be disabled 
by setting deprecation_warnings=False in ansible.cfg.
ok: [localhost]

TASK [ensure development tools are at the latest version] **********************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'llvm-7-dev' is available"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

パスワードは、aptなどで使うsudoを実行するときと同じパスワードです。
ちなみに、root化も行っていて、（セキュリティーの観点からすると問題ですが）自分が普通に使っている一般ユーザーのパスワードと同じパスワードです。

**Comment by uchan-nos** [comment]
ログを貼り付けていただいてありがとうございます。
これを見る限り、パスワード関連の問題ではなく、タスクが1つ FAILED になっているのが問題のようですね。

> No package matching 'llvm-7-dev' is available

llvm-7-dev というパッケージが無いためにセットアップがエラーになっています。

良く見ると「Distribution ubuntu 21.10」という表示があり、もしかして Ubuntu 21.10 をお使いでしょうか？
本書の開発環境は Ubuntu 18.04 と 20.04 で動作確認しているのですが、21.10 では確認していません。
LLVM 7 は割と古めのコンパイラなので、21.10 には標準では含まれないのでしょうね。

次のような解決策があります

- Ubuntu 20.04 をお使いいただく
- ansible_provision.yml を編集して LLVM 13 あたりをお使いいただく
- 開発環境が Ubuntu 21.10 に対応するのを待つ

**Comment by Apo-2008** [comment]
お返事ありがとうございます
ご指摘にあった通りubuntu20.04をインストールし構築を行ったところ問題なくできました
おさわがせして

**Comment by Apo-2008** [comment]
お返事ありがとうございます
ご指摘にあった通りubuntu20.04をインストールし構築を行ったところ問題なくできました
お騒がせし申し訳ありませんでした
返信が遅くなりましたこと、同時に謝らせていただきます #
