### ISSUE TITLE
osbook_day03c以降で利用でするインクルードファイルについて

### ISSUE THREAD

**Issue by gondoumasayuki** [uchan-nos/os-from-zero#122]
作業環境の関係でansibleがうまく動かずedk2などを自分で作成できたのですが、
osbook_day03c以降で利用でするインクルードファイルについて
どこからダウンロードしてくれば良いものかわかりませんでした。

＞このディレクトリに含まれるファイルは [Newlib](https://sourceware.org/newlib/)，[libc++](https://libcxx.llvm.org/)，[FreeType](https://www.freetype.org/) をビルドしたものです。 

とのことでしたが、ソースコードとそのビルド方法を教えていただけませんか。

**Comment by uchan-nos** [comment]
ここにビルドスクリプトがございます。
https://github.com/uchan-nos/mikanos-build/blob/master/devenv_src/stdlib/build-stdlib.sh

インクルードファイルだけではなく、ライブラリのビルドも必要です。

**Comment by gondoumasayuki** [comment]
ありがとうございます．
ライブラリもビルドしないといけないのですね．
明日試してみます．

**Comment by gondoumasayuki** [comment]
本質と離れそうだったためビルド済みのバイナリを使わせていただきます。
ありがとうございます。
時間があったら戻ってきてビルドからやってみます。

無事にファイル群を取得し、パスも正しいはずなのにfatal errorが発生したため、
改めてまた考えて出直してきます。
