### ISSUE TITLE
p51のブートローダーのビルドでエラーが出ました

### ISSUE THREAD

**Issue by romeiR** [uchan-nos/os-from-zero#123]
p51のEDK2でブートローダーをビルドしたところ以下のエラーが出てしまいました。
環境構築はansibleでやらせていただきました。
raspberrypi にubuntu20.04をつかってやっているのでそれが原因でしょうか？

![スクリーンショット 2022-02-16 8 33 54](https://user-images.githubusercontent.com/77832723/154168578-0b7b2b81-defb-45c7-a4cb-3eb9ff103ad0.png)
![スクリーンショット 2022-02-16 8 34 03](https://user-images.githubusercontent.com/77832723/154168588-142703a9-1dea-4466-9048-c84d012f343b.png)

**Comment by uchan-nos** [comment]
ご推察のとおり Raspberry Pi であることが原因です。

参考 https://zero.osdev.jp/faq.html#raspberry-pi-%E3%81%A7%E3%82%82%E5%8B%95%E4%BD%9C%E3%81%99%E3%82%8B
