### ISSUE TITLE
[質問]LocalAPICタイマについて

### ISSUE THREAD

**Issue by kawasaki384** [uchan-nos/os-from-zero#124]
9章4節(osbook_day09b)の「重ね合わせ処理の時間計測」の
timer.cppで

> lvt_timer = (0b001 << 16)  |  32;  //masked, one-shot

というコードを読んだのですがなぜ32をor演算するのか気になりました。
なぜ32をor演算するか教えていただけますでしょうか。

**Comment by uchan-nos** [comment]
「32」は割り込みベクタ番号です。
当時の経緯は覚えていませんが、手元での実験時に割り込みを起こしたくて設定した名残が削除されず残ってしまったのかもしれません。

ということで、深い意図はなく、32 を OR しなくても動くと思います。

**Comment by kawasaki384** [comment]
ご返信ありがとうございました！
