### ISSUE TITLE
【質問】2章：EDK2のビルドでのエラー

### ISSUE THREAD

**Issue by daiki-skm** [uchan-nos/os-from-zero#125]
実行環境
- UTM
- Ubuntu 20.04.4

参考記事

- https://github.com/uchan-nos/os-from-zero/issues/117
- https://github.com/uchan-nos/os-from-zero/issues/114
- https://github.com/uchan-nos/os-from-zero/issues/45

上記記事を参考にビルドエラーの解決を試みたのですが、新たなエラーが出てしまい、イシューを立てさせていただきました。

![スクリーンショット 2022-03-01 17 33 12](https://user-images.githubusercontent.com/69021549/156133580-c25ef5d9-b86f-4476-92a1-996370603758.png)

ソースコードの現状
- https://github.com/uchan-nos/os-from-zero/issues/117#issuecomment-990733219
- https://github.com/uchan-nos/os-from-zero/issues/117#issuecomment-991043378
- https://github.com/uchan-nos/os-from-zero/issues/114#issuecomment-963722667

上記コメントを実行済みです。

**Comment by 777shuang** [comment]
つい最近ゼロ~を購入し, 読んでいる者です。
同じようなエラーが私も出ています。

**Comment by 777shuang** [comment]
[こちら](https://roytch.net/2021/04/30/%E3%80%8E%E3%82%BC%E3%83%AD%E3%81%8B%E3%82%89%E3%81%AEos%E8%87%AA%E4%BD%9C%E5%85%A5%E9%96%80%E3%80%8F%E7%AC%AC2%E7%AB%A0%E3%81%BE%E3%81%A7/)が参考になりました。

**Comment by uchan-nos** [comment]
@daiki328
UTM って何でしょうか？

あと、エラーログを見る限り最終的なエラーの部分しかスクリーンショットに映っておらず、真のエラーがよくわかりませんでした。
ビルド時のログを、省略せずに貼ってください。
（画像でもいいですが、文字列のまま貼っていただけると検索も出来て嬉しいです）

**Comment by daiki328** [comment]
@777shuang 
記事の記載ありがとうございます。
参考にさせていただきます。

**Comment by daiki328** [comment]
@uchan-nos 
> UTM って何でしょうか？

すみません。UTM（https://mac.getutm.app/）とは、VM上でOSを動かすアプリケーションです。

> あと、エラーログを見る限り最終的なエラーの部分しかスクリーンショットに映っておらず、真のエラーがよくわかりませんでした。
ビルド時のログを、省略せずに貼ってください。
（画像でもいいですが、文字列のまま貼っていただけると検索も出来て嬉しいです）

了解いたしました。以後、気をつけます。

**Comment by daiki328** [comment]
@uchan-nos 
```
Build environment: Linux-5.4.0-100-generic-aarch64-with-glibc2.29
Build start time: 04:55:54, Mar.07 2022

WORKSPACE    	= /home/daiki_skm/edk2
EDK_TOOLS_PATH   = /home/daiki_skm/edk2/BaseTools
CONF_PATH    	= /home/daiki_skm/edk2/Conf
PYTHON_COMMAND   = /usr/bin/python3.8


Processing meta-data .
Architecture(s)  = X64
Build target 	= DEBUG
Toolchain    	= CLANG38

Active Platform      	= /home/daiki_skm/edk2/MikanLoaderPkg/MikanLoaderPkg.dsc


build.py...
/home/daiki_skm/edk2/MikanLoaderPkg/MikanLoaderPkg.dsc(27): error 000E: File/directory not found in workspace
    /home/daiki_skm/edk2/MdePkg/Library/RegisterFilterLibNull/RegisterFilterLibNull.inf
 

- Failed -
Build end time: 04:55:54, Mar.07 2022
Build total time: 00:00:00
```
再度buildしたところ、上記のように、RegisterFilterLibNull.infが見つからないとエラーが出てしまいました。
アドバイスをいただけますと幸いです。

**Comment by uchan-nos** [comment]
すみません。こちら反応を忘れていました。

https://twitter.com/dmystk/status/1419117279325736960?s=20&t=n59eq-wn8CLemT0s769hXQ
このあたりが参考になるでしょうか。
