### ISSUE TITLE
【質問】Hello,world!が表示されない

### ISSUE THREAD

**Issue by zairuoukoku** [uchan-nos/os-from-zero#126]
ゼロからのOS自作入門を購入した初心者の者です。
基本的な質問で申し訳ありませんが困っています。

p.31に記載されている「Hello, world!」の文字が表示されませんでした。

環境
・Windows 11
・WSL2

実行したこと
・p.30に記載されている"BOOTX64.EFI"のチェックサムの値を確認し、"12430    2"と表示されることを確認した。
・p.31に記載されているセキュアブートの無効化を実施した。
・p.33,34に記載されている内容に従い、usbメモリをフォーマットした。（ドライブレターは環境に合わせて"D:"で実施）

この「Hello, world!」という表示はパソコンを起動してBIOSが起動するタイミングに一瞬表示され、その後OSが通常通り起動するのでしょうか？
それとも、BIOS起動後、ずっと「Hello, world!」と表示され続けるのでしょうか？
BIOSのBOOT設定が悪いのか、それともそれ以外の設定が何か悪いのか原因がわからずにいます。

**Comment by uchan-nos** [comment]
Hello, world の表示は、ずっと表示されることを期待しています。

zairuoukoku さんの環境では、Hello, world が表示されず、通常通り Windows が起動してしまっていますか？
そうであれば、起動デバイスとして USB メモリより内蔵ストレージが優先されてしまっているか、
そもそも USB メモリが起動デバイスとして認識されていないか、という可能性が思いつきますね。

もしかしたら USB メモリを exFAT でフォーマットしていますか？
FAT32 が選べたらそちらでも試してみてください。
参考： https://zero.osdev.jp/faq.html#fat32-%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%8F-exfat-%E3%81%A7%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88%E3%81%99%E3%82%8B%E7%90%86%E7%94%B1%E3%81%AF

**Comment by zairuoukoku** [comment]
＞uchan-nos　さん
早速ご返信いただきありがとうございます。一度FAT32で試してみたいと思います。

**Comment by zairuoukoku** [comment]
＞uchan-nos　さん
FAT32でフォーマットして実行してみたところ、無事「Hello, world!」と表示されるようになりました。
"USB メモリが起動デバイスとして認識されていない"ことが原因だったと思われます。
ご対応頂きありがとうございました。
