### ISSUE TITLE
osbook_day04c リンク処理でエラーが出てしまう

### ISSUE THREAD

**Issue by zairuoukoku** [uchan-nos/os-from-zero#128]
初歩的な質問で申し訳ありません。

osbook_day04cの内容を記載している箇所で
"git checkout osbook_day04c"
を実行した後、
"clang++ $CPPFLAGS -O2 --target=x86_64-elf -fno-exceptions -ffreestanding -c main.cpp"
でコンパイルし、
"ld.lld $LDFLAGS --entry KernelMain -z norelro --image-base 0x100000 --static -o kernel.elf main.o"
でリンクをしたのですが、リンク時に
"ld.lld: error: undefined symbol: vtable for __cxxabiv1::__class_type_info
>>> referenced by main.cpp
>>>               main.o:(typeinfo for PixelWriter)

ld.lld: error: undefined symbol: vtable for __cxxabiv1::__si_class_type_info
>>> referenced by main.cpp
>>>               main.o:(typeinfo for RGBResv8BitPerColorPixelWriter)

ld.lld: error: undefined symbol: vtable for __cxxabiv1::__si_class_type_info
>>> referenced by main.cpp
>>>               main.o:(typeinfo for BGRResv8BitPerColorPixelWriter)"

とエラーが表示されてしまいます。
vtableのところが上手くいっていないように感じるのですが対処方法を教えて頂けないでしょうか？

**Comment by uchan-nos** [comment]
未定義シンボルの名前からして、動的型情報の関連だと思います。
コンパイルオプションに `-fno-rtti` を足したら上手く行くでしょうか？

**Comment by uchan-nos** [comment]
ちなみに MikanOS をビルドする際の設定は
https://github.com/uchan-nos/mikanos/blob/master/kernel/Makefile#L14-L15
に書かれていますので参考にしてください。

**Comment by zairuoukoku** [comment]
早速のご回答ありがとうございます。

ご指摘の通り
"clang++ $CPPFLAGS -O2 --target=x86_64-elf -fno-exceptions -ffreestanding -fno-rtti -c main.cpp"
でコンパイルした後にリンクするとエラーなく動作しました。

上記リンク先勉強させていただきます。
ありがとうございました。

**Comment by uchan-nos** [comment]
良かったです。クローズします
