### ISSUE TITLE
付録A 開発環境のインストールについての質問

### ISSUE THREAD

**Issue by numakachan** [uchan-nos/os-from-zero#132]
はじめまして。
以下の環境で開発ツールの導入を行っておりますが、
「ansible-playbook -K -i ansible_inventory ansible_provision.yml」を実行後に
TASK [clone EDK II repository] *************************************************で止まってしまいます。
何度か試しましたが改善は見られませんでした。

TASK [install qemu gui package if exists] **************************************
skipping: [localhost]
少し前の処理でスキップになっているようなのですが、これが原因なのでしょうか？
原因や改善策など教えていただけるとありがたいです。
よろしくお願いします。

〜実行環境〜
os：Ubuntu 18.04.6 LTS
cpu：Intel® Core™ i5-2415M CPU @ 2.30GHz × 4 

〜実行ログ〜
n@Hampen:~$ sudo apt install ansible
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ansible is already the newest version (2.5.1+dfsg-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

n@Hampen:~$ cd $HOME/osbook/devenv
n@Hampen:~/osbook/devenv$ ansible-playbook -K -i ansible_inventory ansible_provision.yml
SUDO password: 

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [ensure development tools are at the latest version] **********************
ok: [localhost]

TASK [check whether qemu-system-gui exists] ************************************
ok: [localhost]

TASK [install qemu gui package if exists] **************************************
skipping: [localhost]

TASK [set llvm 7 as default] ***************************************************
ok: [localhost] => (item=llvm-PerfectShuffle)
ok: [localhost] => (item=llvm-ar)
ok: [localhost] => (item=llvm-as)
ok: [localhost] => (item=llvm-bcanalyzer)
ok: [localhost] => (item=llvm-cat)
ok: [localhost] => (item=llvm-cfi-verify)
ok: [localhost] => (item=llvm-config)
ok: [localhost] => (item=llvm-cov)
ok: [localhost] => (item=llvm-c-test)
ok: [localhost] => (item=llvm-cvtres)
ok: [localhost] => (item=llvm-cxxdump)
ok: [localhost] => (item=llvm-cxxfilt)
ok: [localhost] => (item=llvm-diff)
ok: [localhost] => (item=llvm-dis)
ok: [localhost] => (item=llvm-dlltool)
ok: [localhost] => (item=llvm-dwarfdump)
ok: [localhost] => (item=llvm-dwp)
ok: [localhost] => (item=llvm-exegesis)
ok: [localhost] => (item=llvm-extract)
ok: [localhost] => (item=llvm-lib)
ok: [localhost] => (item=llvm-link)
ok: [localhost] => (item=llvm-lto)
ok: [localhost] => (item=llvm-lto2)
ok: [localhost] => (item=llvm-mc)
ok: [localhost] => (item=llvm-mca)
ok: [localhost] => (item=llvm-modextract)
ok: [localhost] => (item=llvm-mt)
ok: [localhost] => (item=llvm-nm)
ok: [localhost] => (item=llvm-objcopy)
ok: [localhost] => (item=llvm-objdump)
ok: [localhost] => (item=llvm-opt-report)
ok: [localhost] => (item=llvm-pdbutil)
ok: [localhost] => (item=llvm-profdata)
ok: [localhost] => (item=llvm-ranlib)
ok: [localhost] => (item=llvm-rc)
ok: [localhost] => (item=llvm-readelf)
ok: [localhost] => (item=llvm-readobj)
ok: [localhost] => (item=llvm-rtdyld)
ok: [localhost] => (item=llvm-size)
ok: [localhost] => (item=llvm-split)
ok: [localhost] => (item=llvm-stress)
ok: [localhost] => (item=llvm-strings)
ok: [localhost] => (item=llvm-strip)
ok: [localhost] => (item=llvm-symbolizer)
ok: [localhost] => (item=llvm-tblgen)
ok: [localhost] => (item=llvm-undname)
ok: [localhost] => (item=llvm-xray)
ok: [localhost] => (item=ld.lld)
ok: [localhost] => (item=lld-link)
ok: [localhost] => (item=clang)
ok: [localhost] => (item=clang++)
ok: [localhost] => (item=clang-cpp)

TASK [clone EDK II repository] *************************************************

**Comment by numakachan** [comment]
追記です。
再度、「ansible-playbook -K -i ansible_inventory ansible_provision.yml」を実行してみたら、
今度は以下エラーが出力されました。

そのため、to retry useの通り、「ansible-playbook -K -i ansible_inventory ansible_prosion.yml --limit @/home/n/osbook/devenv/ansible_provision.retry」を実行してみましたが、特に変化はなく以下エラーが出るのみです。

〜実行ログ〜
n@Hampen:~/osbook/devenv$ ansible-playbook -K -i ansible_inventory ansible_provision.yml
SUDO password: 

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [ensure development tools are at the latest version] **********************
ok: [localhost]

TASK [check whether qemu-system-gui exists] ************************************
ok: [localhost]

TASK [install qemu gui package if exists] **************************************
skipping: [localhost]

TASK [set llvm 7 as default] ***************************************************
ok: [localhost] => (item=llvm-PerfectShuffle)
ok: [localhost] => (item=llvm-ar)
ok: [localhost] => (item=llvm-as)
ok: [localhost] => (item=llvm-bcanalyzer)
ok: [localhost] => (item=llvm-cat)
ok: [localhost] => (item=llvm-cfi-verify)
ok: [localhost] => (item=llvm-config)
ok: [localhost] => (item=llvm-cov)
ok: [localhost] => (item=llvm-c-test)
ok: [localhost] => (item=llvm-cvtres)
ok: [localhost] => (item=llvm-cxxdump)
ok: [localhost] => (item=llvm-cxxfilt)
ok: [localhost] => (item=llvm-diff)
ok: [localhost] => (item=llvm-dis)
ok: [localhost] => (item=llvm-dlltool)
ok: [localhost] => (item=llvm-dwarfdump)
ok: [localhost] => (item=llvm-dwp)
ok: [localhost] => (item=llvm-exegesis)
ok: [localhost] => (item=llvm-extract)
ok: [localhost] => (item=llvm-lib)
ok: [localhost] => (item=llvm-link)
ok: [localhost] => (item=llvm-lto)
ok: [localhost] => (item=llvm-lto2)
ok: [localhost] => (item=llvm-mc)
ok: [localhost] => (item=llvm-mca)
ok: [localhost] => (item=llvm-modextract)
ok: [localhost] => (item=llvm-mt)
ok: [localhost] => (item=llvm-nm)
ok: [localhost] => (item=llvm-objcopy)
ok: [localhost] => (item=llvm-objdump)
ok: [localhost] => (item=llvm-opt-report)
ok: [localhost] => (item=llvm-pdbutil)
ok: [localhost] => (item=llvm-profdata)
ok: [localhost] => (item=llvm-ranlib)
ok: [localhost] => (item=llvm-rc)
ok: [localhost] => (item=llvm-readelf)
ok: [localhost] => (item=llvm-readobj)
ok: [localhost] => (item=llvm-rtdyld)
ok: [localhost] => (item=llvm-size)
ok: [localhost] => (item=llvm-split)
ok: [localhost] => (item=llvm-stress)
ok: [localhost] => (item=llvm-strings)
ok: [localhost] => (item=llvm-strip)
ok: [localhost] => (item=llvm-symbolizer)
ok: [localhost] => (item=llvm-tblgen)
ok: [localhost] => (item=llvm-undname)
ok: [localhost] => (item=llvm-xray)
ok: [localhost] => (item=ld.lld)
ok: [localhost] => (item=lld-link)
ok: [localhost] => (item=clang)
ok: [localhost] => (item=clang++)
ok: [localhost] => (item=clang-cpp)

TASK [clone EDK II repository] *************************************************
fatal: [localhost]: FAILED! => {"before": "38c8be123aced4cc8ad5c7e0da9121a181b94251", "changed": false, "msg": "Local modifications exist in repository (force=no)."}
	to retry, use: --limit @/home/n/osbook/devenv/ansible_provision.retry

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1   

n@Hampen:~/osbook/devenv$ ansible-playbook -K -i ansible_inventory ansible_provision.yml --limit @/home/n/osbook/devenv/ansible_provision.retry
SUDO password: 

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [ensure development tools are at the latest version] **********************
ok: [localhost]

TASK [check whether qemu-system-gui exists] ************************************
ok: [localhost]

TASK [install qemu gui package if exists] **************************************
skipping: [localhost]

TASK [set llvm 7 as default] ***************************************************
ok: [localhost] => (item=llvm-PerfectShuffle)
ok: [localhost] => (item=llvm-ar)
ok: [localhost] => (item=llvm-as)
ok: [localhost] => (item=llvm-bcanalyzer)
ok: [localhost] => (item=llvm-cat)
ok: [localhost] => (item=llvm-cfi-verify)
ok: [localhost] => (item=llvm-config)
ok: [localhost] => (item=llvm-cov)
ok: [localhost] => (item=llvm-c-test)
ok: [localhost] => (item=llvm-cvtres)
ok: [localhost] => (item=llvm-cxxdump)
ok: [localhost] => (item=llvm-cxxfilt)
ok: [localhost] => (item=llvm-diff)
ok: [localhost] => (item=llvm-dis)
ok: [localhost] => (item=llvm-dlltool)
ok: [localhost] => (item=llvm-dwarfdump)
ok: [localhost] => (item=llvm-dwp)
ok: [localhost] => (item=llvm-exegesis)
ok: [localhost] => (item=llvm-extract)
ok: [localhost] => (item=llvm-lib)
ok: [localhost] => (item=llvm-link)
ok: [localhost] => (item=llvm-lto)
ok: [localhost] => (item=llvm-lto2)
ok: [localhost] => (item=llvm-mc)
ok: [localhost] => (item=llvm-mca)
ok: [localhost] => (item=llvm-modextract)
ok: [localhost] => (item=llvm-mt)
ok: [localhost] => (item=llvm-nm)
ok: [localhost] => (item=llvm-objcopy)
ok: [localhost] => (item=llvm-objdump)
ok: [localhost] => (item=llvm-opt-report)
ok: [localhost] => (item=llvm-pdbutil)
ok: [localhost] => (item=llvm-profdata)
ok: [localhost] => (item=llvm-ranlib)
ok: [localhost] => (item=llvm-rc)
ok: [localhost] => (item=llvm-readelf)
ok: [localhost] => (item=llvm-readobj)
ok: [localhost] => (item=llvm-rtdyld)
ok: [localhost] => (item=llvm-size)
ok: [localhost] => (item=llvm-split)
ok: [localhost] => (item=llvm-stress)
ok: [localhost] => (item=llvm-strings)
ok: [localhost] => (item=llvm-strip)
ok: [localhost] => (item=llvm-symbolizer)
ok: [localhost] => (item=llvm-tblgen)
ok: [localhost] => (item=llvm-undname)
ok: [localhost] => (item=llvm-xray)
ok: [localhost] => (item=ld.lld)
ok: [localhost] => (item=lld-link)
ok: [localhost] => (item=clang)
ok: [localhost] => (item=clang++)
ok: [localhost] => (item=clang-cpp)

TASK [clone EDK II repository] *************************************************
fatal: [localhost]: FAILED! => {"before": "38c8be123aced4cc8ad5c7e0da9121a181b94251", "changed": false, "msg": "Local modifications exist in repository (force=no)."}
	to retry, use: --limit @/home/n/osbook/devenv/ansible_provision.retry

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1   

n@Hampen:~/osbook/devenv$

**Comment by uchan-nos** [comment]
@numakachan 
エラーメッセージに
Local modifications exist in repository (force=no).
とある通り、edk2 ディレクトリの中に変更された部分があり、
Git clone ができずにエラーになっていると思われます。
edk2 ディレクトリを削除してから ansible を再実行すると上手くいくかもしれません。
