### ISSUE TITLE
パイプの実装に関する質問

### ISSUE THREAD

**Issue by inadera-rantaro** [uchan-nos/os-from-zero#135]
パイプの実装で以下のコードについて質問させてください。

   auto& subtask = task_manager->NewTask();
   pipe_fd = std::make_shared<PipeDescriptor>(subtask);

subtaskはTaskクラスのオブジェクトだと思うのですが、PipDescriptorクラスのスマートポインタを使用しています。
関連性のないクラスだと思うのですが、このコードが成立する理由がよく分かりません。ご教授お願い致します。

shard_ptrの説明サイト等を見てみたのですが、よく分からなかった・・・

**Comment by uchan-nos** [comment]
この部分でしょうか？ https://github.com/uchan-nos/mikanos/blob/c344eaa8e66eed2d4c69a609d5747e182591cc78/kernel/terminal.cpp#L456-L457

正確に引用するとこの 2 行ですね。

```
    auto& subtask = task_manager->NewTask();
    pipe_fd = std::make_shared<PipeDescriptor>(subtask);
```

> subtaskはTaskクラスのオブジェクトだと思う
その通りです。

`std::make_shared<PipeDescriptor>(subtask)` は、PipeDescriptor クラスのコンストラクタが呼び出されていて、その引数に subtask が渡されています。

コンストラクタの実装はこれですね https://github.com/uchan-nos/mikanos/blob/c344eaa8e66eed2d4c69a609d5747e182591cc78/kernel/terminal.cpp#L1099
