### ISSUE TITLE
please help me solve it

### ISSUE THREAD

**Issue by producer-mintry** [uchan-nos/os-from-zero#136]
I want 'ansible-playbook -K -i ansible_inventory ansible_provision.yml' to work, but it doesn't.
It's just that 'fatal: [localhost]: FAILED! => it only gives me the error {"changed": false, "msg": "No package matching 'llvm-7-dev' is available"}'.
how can i fix it?
this is a log:
$ ansible-playbook -K -i ansible_inventory ansible_provision.yml
BECOME password:

PLAY [all] *************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [ensure development tools are at the latest version] **************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'llvm-7-dev' is available"}

PLAY RECAP *************************************************************************************************************
localhost : ok=1 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0

please help me

**Comment by uchan-nos** [comment]
llvm-7-dev exists on Ubuntu 18.04 and 20.04, but Ubuntu 22.04 has no such package.
Try to use Ubuntu 20.04.

Cf: https://github.com/uchan-nos/mikanos-build/commit/182902d66b1151ee8aacf34ff71d6b052d4cf363
