### ISSUE TITLE
osbook_day02bのLoader.infの変更点について

### ISSUE THREAD

**Issue by saitenntaisei** [uchan-nos/os-from-zero#139]
osbook_day02bのLoader.infについて
```
[Protocols]
  gEfiLoadedImageProtocolGuid
  gEfiLoadFileProtocolGuid
  gEfiSimpleFileSystemProtocolGuid

```
が追加されていると思うのですが, これらはMdepkg/include/protocolに定義がありわざわざ追記しなくてもbuildできると思いbuildしてみたところ` hidden symbol 'gEfiLoadedImageProtocolGuid' isn't defined`　というエラーが出ました.  これを追加しないとbuild が通らない理由は何ですか? またこれについてのリファレンスの参考箇所などがあれば教えていただきたいです.

**Comment by uchan-nos** [comment]
EDK II の Inf ファイルの Protocols セクションに関するドキュメントはこちらです。
https://edk2-docs.gitbook.io/edk-ii-inf-specification/2_inf_overview/29_-protocols-_section

このドキュメントによれば、依存パッケージの Protocols が参照されますよーというような記述は無いため、
必要な GUID については全てこちらに列挙する必要があるのだと思います。
