### ISSUE TITLE
wsl2でのqemuについて

### ISSUE THREAD

**Issue by matuhei** [uchan-nos/os-from-zero#141]
p35ページの上部のようにsudo cp BOOTX64.EFI mnt/EFI/BOOT/BOOTX64.EFIとwsl2で入力しても「cp: 'BOOTX64.EFI' を stat できません: そのようなファイルやディレクトリはありません」と表示されます。どうしたらよいでしょうか。

**Comment by uchan-nos** [comment]
BOOTX64.EFI があるディレクトリに移動してからそのコマンドを実行してください。

**Comment by matuhei** [comment]
ありがとうございます。やってみます！

**Comment by matuhei** [comment]
「そのようなファイルやディレクトリはありません」と表示されるのですがどうしたらよいでしょうか。

**Comment by uchan-nos** [comment]
もう少し情報をいただけないと、何が起こっているのか分かりません。
何をしたのか、一連のコマンド列と、その出力を省略せずに投稿してください。

Linux のコマンドは初めて使うのでしょうか。
であれば、質問を続ける前に、こちらを一読してみてください。
https://github.com/uchan-nos/os-from-zero/wiki/Basic-Linux-Commands

**Comment by matuhei** [comment]
実は万年windowsでして。てっきりコマンドプロンプトと同じかと思って、「cd C:\Users\ユーザーネーム\Desktop\BzEditor」と打ったのですが、具体的にはどのように打てばよかったのでしょうか。

**Comment by uchan-nos** [comment]
`/home/uchan/workspace` のように / 区切りで打ちます。
WSL2 で Windows のディレクトリを見るには `/mnt/c/Users/...` のようになります。

**Comment by matuhei** [comment]
ありがとうございます。やってみます。
