### ISSUE TITLE
Ubuntu 20.04 でブートローダーのファイル Loader.efi が生成されない

### ISSUE THREAD

**Issue by uchan-nos** [uchan-nos/os-from-zero#144]
> ![スクリーンショット 2023-03-20 205616](https://user-images.githubusercontent.com/89998242/226332436-9525745d-457d-400d-9198-92474f35ae2b.png)
> 
> P.51のbuildはできているのですが，Loader.efiが生成されません．
> 
> ubuntu 20.04です

_Originally posted by @yuzu-krs in https://github.com/uchan-nos/os-from-zero/issues/114#issuecomment-1476093976_

**Comment by yuzu-krs** [comment]
> 質問の続きが私の Discord サーバーに投稿されたので、こちらに転記。 （ @yuzu-krs さん、画像などの転載がまずければ教えてください。）
> 
> ![image](https://user-images.githubusercontent.com/1825663/227396839-26124fab-37ed-418e-baf9-ccf6c9c95095.png)
> 
> /home/yuzu/edk2/MikanLoaderPkg/MikanLoaderPkg.dsc の内容が正しいのか気になるので、 `cat /home/yuzu/edk2/MikanLoaderPkg/MikanLoaderPkg.dsc` して出力された結果を全部貼ってもらえますか？

![image](https://user-images.githubusercontent.com/89998242/227401494-9c78cd15-6f4d-4ccf-b99b-62a60b74eacc.png)

**Comment by yuzu-krs** [comment]
> > 質問の続きが私の Discord サーバーに投稿されたので、こちらに転記。 （ @yuzu-krs さん、画像などの転載がまずければ教えてください。）
> > ![image](https://user-images.githubusercontent.com/1825663/227396839-26124fab-37ed-418e-baf9-ccf6c9c95095.png)
> > /home/yuzu/edk2/MikanLoaderPkg/MikanLoaderPkg.dsc の内容が正しいのか気になるので、 `cat /home/yuzu/edk2/MikanLoaderPkg/MikanLoaderPkg.dsc` して出力された結果を全部貼ってもらえますか？
> 
> ![image](https://user-images.githubusercontent.com/89998242/227401494-9c78cd15-6f4d-4ccf-b99b-62a60b74eacc.png)

このような感じになりました

**Comment by uchan-nos** [comment]
@yuzu-krs 
ありがとうございます。
その画像が MikanLoaderPkg.dsc の全体なのでしょうか？
そうなのであれば、ファイルが中途半端な内容になっていそうです。

本来は `[LibraryClasses]` や `[Components]` といった項目も .dsc ファイルに含まれているはずです。
試しに、手元のファイルでそれらの行をコメントアウトしてみました。こんなふうに。

```
[Defines]
  PLATFORM_NAME                  = MikanLoaderPkg
  PLATFORM_GUID                  = d3f11f4e-71e9-11e8-a7e1-33fd4f7d5a3e
  PLATFORM_VERSION               = 0.1
  DSC_SPECIFICATION              = 0x00010005
  OUTPUT_DIRECTORY               = Build/MikanLoader$(ARCH)
  SUPPORTED_ARCHITECTURES        = X64
  BUILD_TARGETS                  = DEBUG|RELEASE|NOOPT

#[LibraryClasses]
#  UefiApplicationEntryPoint|MdePkg/Library/UefiApplicationEntryPoint/UefiApplicationEntryPoint.inf
#  UefiLib|MdePkg/Library/UefiLib/UefiLib.inf
#
#  BaseLib|MdePkg/Library/BaseLib/BaseLib.inf
#  BaseMemoryLib|MdePkg/Library/BaseMemoryLib/BaseMemoryLib.inf
#  DebugLib|MdePkg/Library/BaseDebugLibNull/BaseDebugLibNull.inf
#  DevicePathLib|MdePkg/Library/UefiDevicePathLib/UefiDevicePathLib.inf
#  MemoryAllocationLib|MdePkg/Library/UefiMemoryAllocationLib/UefiMemoryAllocationLib.inf
#  PcdLib|MdePkg/Library/BasePcdLibNull/BasePcdLibNull.inf
#  PrintLib|MdePkg/Library/BasePrintLib/BasePrintLib.inf
#  RegisterFilterLib|MdePkg/Library/RegisterFilterLibNull/RegisterFilterLibNull.inf
#  UefiBootServicesTableLib|MdePkg/Library/UefiBootServicesTableLib/UefiBootServicesTableLib.inf
#  UefiRuntimeServicesTableLib|MdePkg/Library/UefiRuntimeServicesTableLib/UefiRuntimeServicesTableLib.inf
#
#[Components]
#  MikanLoaderPkg/Loader.inf
```

この状態で build コマンドを実行すると、確かに yuzu さんが貼っていただいたスクリーンショットのように、何も実行せず「done!」とだけ表示される状態になりました。

**Comment by yuzu-krs** [comment]
> @yuzu-krs ありがとうございます。 その画像が MikanLoaderPkg.dsc の全体なのでしょうか？ そうなのであれば、ファイルが中途半端な内容になっていそうです。
> 
> 本来は `[LibraryClasses]` や `[Components]` といった項目も .dsc ファイルに含まれているはずです。 試しに、手元のファイルでそれらの行をコメントアウトしてみました。こんなふうに。
> 
> ```
> [Defines]
>   PLATFORM_NAME                  = MikanLoaderPkg
>   PLATFORM_GUID                  = d3f11f4e-71e9-11e8-a7e1-33fd4f7d5a3e
>   PLATFORM_VERSION               = 0.1
>   DSC_SPECIFICATION              = 0x00010005
>   OUTPUT_DIRECTORY               = Build/MikanLoader$(ARCH)
>   SUPPORTED_ARCHITECTURES        = X64
>   BUILD_TARGETS                  = DEBUG|RELEASE|NOOPT
> 
> #[LibraryClasses]
> #  UefiApplicationEntryPoint|MdePkg/Library/UefiApplicationEntryPoint/UefiApplicationEntryPoint.inf
> #  UefiLib|MdePkg/Library/UefiLib/UefiLib.inf
> #
> #  BaseLib|MdePkg/Library/BaseLib/BaseLib.inf
> #  BaseMemoryLib|MdePkg/Library/BaseMemoryLib/BaseMemoryLib.inf
> #  DebugLib|MdePkg/Library/BaseDebugLibNull/BaseDebugLibNull.inf
> #  DevicePathLib|MdePkg/Library/UefiDevicePathLib/UefiDevicePathLib.inf
> #  MemoryAllocationLib|MdePkg/Library/UefiMemoryAllocationLib/UefiMemoryAllocationLib.inf
> #  PcdLib|MdePkg/Library/BasePcdLibNull/BasePcdLibNull.inf
> #  PrintLib|MdePkg/Library/BasePrintLib/BasePrintLib.inf
> #  RegisterFilterLib|MdePkg/Library/RegisterFilterLibNull/RegisterFilterLibNull.inf
> #  UefiBootServicesTableLib|MdePkg/Library/UefiBootServicesTableLib/UefiBootServicesTableLib.inf
> #  UefiRuntimeServicesTableLib|MdePkg/Library/UefiRuntimeServicesTableLib/UefiRuntimeServicesTableLib.inf
> #
> #[Components]
> #  MikanLoaderPkg/Loader.inf
> ```
> 
> この状態で build コマンドを実行すると、確かに yuzu さんが貼っていただいたスクリーンショットのように、何も実行せず「done!」とだけ表示される状態になりました。

![image](https://user-images.githubusercontent.com/89998242/227556633-ec759df4-ffb9-45e3-af9b-2cba472832c0.png)

MikanLoaderPkg.dscの内容を変えたのですが特に変わりませんでした．

**Comment by uchan-nos** [comment]
先頭行に `#` を付けたままでは、コメント行という意味になりますので、書かなかったのと同じことです。
`#` を取り除いてください。

**Comment by yuzu-krs** [comment]
> 

できました．ありがとうございます！

**Comment by uchan-nos** [comment]
そのエラーメッセージは、現在位置が workspace ですので、git コマンドが使えないという意味です。
workspace は git リポジトリが存在しませんので。

workspace/mikanos ディレクトリは手動（mkdir コマンド）で作るのではなく、
git clone コマンドによって生成される想定です。
したがって、まずは workspace/mikanos ディレクトリを消した後、workspace ディレクトリに移動し、
`git clone https://github.com/uchan-nos/mikanos.git` を実行してください。

**Comment by yuzu-krs** [comment]
できました．ありがとうございます．
