### ISSUE TITLE
p30-32「1.1 ハローワールド」の内容が再現できない

### ISSUE THREAD

**Issue by yamaextra** [uchan-nos/os-from-zero#156]
素人質問失礼いたします。

p30-32の通りBOOTX64.EFIを開発用パソコンで作成後、KIOXIA製USBメモリに書き込み（p30の通りのコマンドを入力）、試験用パソコン①②および開発用パソコンでp31に図示されているような「Hello world!」を実行させようとしたところ、
・①ではUSBメモリを挿した状態での起動が出来なかった
・②ではUSBメモリがUEFI上で認識されなくなった（Windows上でも）
・開発用パソコンでは「Missing Operating System」と表示された
となり、いずれも本書の内容を再現できませんでした。

現状自分で確認したことは、
・全てのパソコンでセキュアブートが無効となっていたこと
・BOOTX64.EFIのチェックサムは12430 2と正しく表示されたこと
・USBメモリは開発用パソコン上でdmesgによってsdb1と認識され、かつp30のフォーマットが出来ていたこと（少なくともコマンド入力中にエラー文のようなものは出ていなかった）
・開発用パソコン上でUSBメモリ内に/EFI/BOOT/BOOTX64.EFIがちゃんと存在していること
・さらにその中に.rdataと.textが存在していること
これらを確認しています。

3種類のパソコン全てで別々の症状（？）が出て正しく再現できていないことから、試験パソコン本体の設定よりもBOOTX64.EFIの作成もしくはフォーマットが正しくできていないような気がしているのですが、素人の私ではどこを疑って何を改善すればよいか分かりません。何かアドバイスいただければと思います。

以下、私の環境です。
・開発用パソコン：Panasonic CF-NX3→OS: Debian 11.1
・試験用パソコン：①TOSHIBA dynabook R734/M, ②自作PC→マザーボード：MSI X470 GAMING PRO (MS-7B79) 1.0, CPU: AMD Ryzen 7 2700 eight core processor
・書籍：2023年8月8日　第5版

開発環境の情報が不足しているようでしたら追記いたします。

ちなみに、書籍ではUbuntuを開発環境と想定していますが、そもそもDebianでは同様の操作では不都合がある、といったことはあるのでしょうか…？

以上、よろしくお願いいたします。

**Comment by uchan-nos** [comment]
> ・①ではUSBメモリを挿した状態での起動が出来なかった

起動できない、にも色々な種類があるので、詳しい状況を書いていただけるとヒントが増えます。
画面上のメッセージとか。

私なら、まず①が UEFI に対応しているのか、対応していても、ちゃんと UEFI モードに設定されているか、を確認すると思います。

[TOSHIBA dynabook R734/M](https://www.pc-master.jp/blog/toshiba-r734m.html) というページを見つけました。ここにはレガシー BIOS モード（CSM Boot）と UEFI モードの切り替え方法が載っています。つまり、この機種は UEFI 対応ではあるものの、初期設定ではレガシー BIOS モードになっていると思います。

> ・②ではUSBメモリがUEFI上で認識されなくなった（Windows上でも）

この表現もちょっとよく分からないです。認識「されなくなった」ということは、最初は認識されていて、何か操作をしたら認識されなくなった、ということでしょうか。

> ・開発用パソコンでは「Missing Operating System」と表示された

これも、開発用パソコンが UEFI 対応なのかどうかを確認したいところです。2014 年の機種なので、Dynabook と同様の事情になっているような気がします。

**Comment by uchan-nos** [comment]
> そもそもDebianでは同様の操作では不都合がある、といったことはあるのでしょうか…？

Debian の事情は分かりません。（特に不都合がある話を聞いたことはありません）
