### ISSUE TITLE
p,34 WSL起動してUSBのマウント後のファイルのコピー方法について

### ISSUE THREAD

**Issue by YzT1131** [uchan-nos/os-from-zero#16]
p,34『WSLが起動したら、USBメモリを/mnt/usbmemにマウントし、ファイルをコピーします。』の記述の後のコマンドですが、
ファイルコピーのコマンド
$sudo cp BOOTX64.EFI /mnt/usbmem/EFI/BOOT 
について、現在のディレクトリに存在するBOOTX64.EFIファイルを/mnt/usbmem/EFI/BOOT ディレクトリにコピーするものと
理解しています。
BOOTX64.EFIはp,33にある「Binary Editor Bz」で作製し、ひとまずデスクトップに置いたのですが、これは上記で言うところの「現在のディレクトリ」ではないと思います。案の定コマンド実行してみるとそのファイルは存在しない、と怒られます。

本題ですが、まずBOOTX64.EFIを「現在のディレクトリ」に置きたいのですが、これはどこに置くべきなのでしょうか。

**Comment by kimonohanger** [comment]
こんにちは。
p.34の手順に従うと、「現在のディレクトリ」はWSLユーザのホームディレクトリになると思います。スタートメニューからWSLを起動したら、`pwd`コマンドで確認してみてください。`/home/ユーザ名`のような出力が得られると思います。次に以下のコマンドを実行すると、WSL上のカレントディレクトリをエクスプローラで開くことができます。上手く行ったでしょうか？

```
$ explorer.exe .
```

**Comment by YzT1131** [comment]
試してみたところ無事にWSL上のカレントディレクトリにたどり着くことができました！
ご回答ありがとうございます。

**Comment by uchan-nos** [comment]
@kimonohanger さん、回答ありがとうございました！
解決したようなのでクローズします。
