### ISSUE TITLE
【USBドライバー実装】MSI割込みを登録しても割込みが発生しない

### ISSUE THREAD

**Issue by paulsohn** [uchan-nos/os-from-zero#161]
あけましておめでとうございます。

Rust移植のため、写経ではなくロジックだけ沿って実装しています。
MSI割り込みを有効にするところで、入力は合っているはずなのに割り込みが有効にならず、デバッグに多少手こずっています。
#73 と同じところかなと思います。

以下詳細となりますが、何かMSI割り込み登録で見落としたことがあるのでしょうか？

*****
## PCI入出力の確認

QEMUの`-trace "pci_cfg_write" -trace "pci_cfg_read"`オプションでPCI入出力のデバッグしています。
まず私の実装からは、MSI割り込み登録時のPCIログは以下の通りです。書き込みは合計4件です。
```
100456@1704014684.710340:pci_cfg_read nec-usb-xhci 04:0 @0x70 -> 0x880005
100456@1704014684.710737:pci_cfg_read nec-usb-xhci 04:0 @0x70 -> 0x880005
100456@1704014684.711151:pci_cfg_read nec-usb-xhci 04:0 @0x74 -> 0x0
100456@1704014684.711312:pci_cfg_read nec-usb-xhci 04:0 @0x78 -> 0x0
100456@1704014684.711554:pci_cfg_read nec-usb-xhci 04:0 @0x7c -> 0x0
100456@1704014684.711717:pci_cfg_read nec-usb-xhci 04:0 @0x80 -> 0x0
100456@1704014684.711820:pci_cfg_read nec-usb-xhci 04:0 @0x84 -> 0x0
100456@1704014684.712522:pci_cfg_read nec-usb-xhci 04:0 @0x70 -> 0x880005
100456@1704014684.712867:pci_cfg_read nec-usb-xhci 04:0 @0x70 -> 0x880005
100456@1704014684.713386:pci_cfg_write nec-usb-xhci 04:0 @0x70 <- 0x890005
100456@1704014684.713602:pci_cfg_read nec-usb-xhci 04:0 @0x74 -> 0x0
100456@1704014684.713731:pci_cfg_write nec-usb-xhci 04:0 @0x74 <- 0xfee00000
100456@1704014684.713834:pci_cfg_read nec-usb-xhci 04:0 @0x78 -> 0x0
100456@1704014684.713867:pci_cfg_write nec-usb-xhci 04:0 @0x78 <- 0x0
100456@1704014684.714069:pci_cfg_read nec-usb-xhci 04:0 @0x7c -> 0x0
100456@1704014684.714195:pci_cfg_write nec-usb-xhci 04:0 @0x7c <- 0xc040
100456@1704014684.714364:pci_cfg_read nec-usb-xhci 04:0 @0x10 -> 0x4
100456@1704014684.714748:pci_cfg_read nec-usb-xhci 04:0 @0x14 -> 0x8
```

次に、まったく同じオプションでMikanOSを起動させた場合、MSI割り込み登録時のPCIログは以下の通りです。
```
102273@1704015717.122653:pci_cfg_read nec-usb-xhci 04:0 @0x0 -> 0x1941033
102273@1704015717.122691:pci_cfg_read nec-usb-xhci 04:0 @0x8 -> 0xc033003
102273@1704015717.122756:pci_cfg_read nec-usb-xhci 04:0 @0x0 -> 0x1941033
102273@1704015717.122939:pci_cfg_read nec-usb-xhci 04:0 @0x34 -> 0x90
102273@1704015717.123013:pci_cfg_read nec-usb-xhci 04:0 @0x90 -> 0xf7011
102273@1704015717.123347:pci_cfg_read nec-usb-xhci 04:0 @0x70 -> 0x880005
102273@1704015717.123480:pci_cfg_read nec-usb-xhci 04:0 @0x70 -> 0x880005
102273@1704015717.123523:pci_cfg_read nec-usb-xhci 04:0 @0x74 -> 0x0
102273@1704015717.123551:pci_cfg_read nec-usb-xhci 04:0 @0x78 -> 0x0
102273@1704015717.123619:pci_cfg_read nec-usb-xhci 04:0 @0x7c -> 0x0
102273@1704015717.123698:pci_cfg_write nec-usb-xhci 04:0 @0x70 <- 0x890005
102273@1704015717.123738:pci_cfg_write nec-usb-xhci 04:0 @0x74 <- 0xfee00000
102273@1704015717.123795:pci_cfg_write nec-usb-xhci 04:0 @0x78 <- 0x0
102273@1704015717.123864:pci_cfg_write nec-usb-xhci 04:0 @0x7c <- 0xc040
102273@1704015717.123914:pci_cfg_read nec-usb-xhci 04:0 @0x10 -> 0x4
102273@1704015717.123936:pci_cfg_read nec-usb-xhci 04:0 @0x14 -> 0x8
102273@1704015717.124033:pci_cfg_read nec-usb-xhci 04:0 @0x0 -> 0x1941033
```

どちらも書き込みは4件で、同じ値を書き込んでいます。

```
pci_cfg_write nec-usb-xhci 04:0 @0x70 <- 0x890005
pci_cfg_write nec-usb-xhci 04:0 @0x74 <- 0xfee00000
pci_cfg_write nec-usb-xhci 04:0 @0x78 <- 0x0
pci_cfg_write nec-usb-xhci 04:0 @0x7c <- 0xc040
```

同じオプションで起動させた同じ（仮想）デバイスのため、デバイス設定や諸アドレス等は一致しているはずです。

（追記）書き込みのパターンが悪いのかと思い、4件のdwordを一挙に書き込むように修正しましたが割り込みが発生しないのは同じです。

## IDT登録とEvent Ringの確認
次に、IDT登録が間違ってはいないか確認してみました。
`int3`命令でBP例外を発生させ、対応するBPハンドラが起動することを確認しました。

（追記）`int 0x40`命令で直接xHCI割り込みを発生させたところ、割り込みハンドラに進入することが確認できました。xHCI割り込みを発生させない場合、ハンドラには進入しません（ハンドラの冒頭のログ出力で確認）のでとりあえずIDTの登録には異常はなさそうです。ぶっちゃけ、IDTを登録してメイン関数を`int 0x40`の無限ループだけにするとDay06と同様にカーソルの移動が確認できます。

以上のことから、Event TRBが積もる際に割り込みが正しく発生すれば問題解決という認識ですが、どこが間違っているのか思い当たらない状況です。

**Comment by uchan-nos** [comment]
INT 命令で割り込みが起きているなら、おっしゃる通り IDT の設定は大丈夫だと思います。
後は、次の 3 点が確認すべきことでしょうか。
- Event Ring の設定が正しいか
- Event TRB 受信で割り込みが発生するように設定できているか
- MSI 割り込みの設定が正しいか

MikanOS で MSI 設定をしているところは https://github.com/uchan-nos/mikanos/blob/b5f7740c04002e67a95af16a5c6e073b664bf3f5/kernel/pci.cpp#L314-L318 です。
Paul Sohn さんの OS で msg_addr と msg_data の値を生成しているコードを見てみたいです。

**Comment by uchan-nos** [comment]
https://github.com/uchan-nos/os-from-zero/issues/158 で Event Ring の設定を直したと思うので、「Event Ring の設定が正しいか」は大丈夫でしょう。

「Event TRB 受信で割り込みが発生するように設定」は MikanOS では https://github.com/uchan-nos/mikanos/blob/b5f7740c04002e67a95af16a5c6e073b664bf3f5/kernel/usb/xhci/xhci.cpp#L441-L450 のあたりです。
Paul Sohn さんの OS ではどうなっているでしょうか。

**Comment by paulsohn** [comment]
追記です。
ログ出力として`-trace "usb_xhci_irq_msi"`も追加してみたところ、IRQが発生することまでは確認できました。
```
2904784@1705804798.087175:usb_xhci_irq_msi nr 0
```
当ログはMSI登録をコメントアウトすると出ないので、MSI登録はとりあえずできているように見えますが、
IRQが来たのになぜ割り込みが発生しないかがわかりません。

**Comment by paulsohn** [comment]
大変お騒がせ致しました。
IRQは発生しているのに割り込みに繋がらないことから逆追跡したら、アセンブリの`sti`命令を入れ忘れていたのが原因でした。
