### ISSUE TITLE
実機でHelloWorld!が表示されない

### ISSUE THREAD

**Issue by kntt32** [uchan-nos/os-from-zero#163]
実機でのHelloWorld!がうまくいきません

本書を参考にWSL2を使い、[mikanos-build](https://github.com/uchan-nos/mikanos-build)のhello.efiをFAT32でフォーマットしたbuffalo製usbメモリの/EFI/BOOTへBOOTX64.EFIとしてコピー、そしてパソコンに挿し起動ドライブとして起動させましたが、起動時のロゴのまま文字が表示されませんでした。

環境は、
　TOSHIBA dynabook R634/M
　Windows10
　WSL2のUbuntu
を使用しています。

以下が確認したことや気づいたことです
　・ブートモードはuefi bootに、secure bootはオフに設定済み
　・usbメモリのパーティション形式はMBR/GPT両方で試したが、うまくいかず
　・フォーマットにはクイックフォーマットを使用した
　・qemuではうまくいった
　・実機で起動させた時に、画面に表示されていたのは起動時のロゴのみ
　・実機で起動させると、途中からファンが激しくなった
　・1.9の「C言語でハローワールド」でも同様だった

初心者の私ではどうしてもこれで限界で、原因も何もわからない状態です。
よろしくお願いします。

ーー追記ーー
二章の、EDK2でのメモリマップの取得では、画面表示はできなかったもののusbメモリに「memmap」というファイルが生成されていて、プログラム自体は実行されているようです

**Comment by rkarsnk** [comment]
お使いになっている実機は2014年に販売された製品のようですが，もしかすると実機に搭載されているUEFIの規格が，本書で扱っているUEFIの規格より古い可能性があり，それが原因かもしれません．

UEFIのバージョンを確認する方法は以下
https://blog.goo.ne.jp/limited_terra/e/ae603872ec993e850c33901abfb6f149 

とりあえず，3.4のフレームバッファを操作するところまでQEMUですすめてみてから再度確認されてみてはどうでしょう．

**Comment by kntt32** [comment]
ありがとうございます。
試しにMikanOSのお手軽パックで実機で起動させてみたところ、背景にいくつかエラーと思われるメッセージは表示されてましたが、ちゃんと起動できました。
フレームバッファの操作までQEMUでやってみます。
