### ISSUE TITLE
exFATでは動かなかったがFAT32では動いた

### ISSUE THREAD

**Issue by tauplus** [uchan-nos/os-from-zero#17]
1章のUSBメモリのフォーマットで本の通りにexFATにするとUEFIでの起動ができませんでしたが、FAT32にしたら起動してHello worldの表示をすることができました。（Windows10でフォーマット、WSL1でコピー）

私の環境が少し古いためかもしれません。（マザーボード：ASUS H97M-PLUS　2014年発売）

FAT32の方が動作する環境が多いのではと思うのですが、exFATを指定した理由は何かありますか？

**Comment by uchan-nos** [comment]
図1.8に関する質問でよろしいでしょうか。

ここでexFATを選んでいるのは、私の環境ではFAT32が選択肢に無かったからです。

ここでの要旨は「NTFSを選ばない」ということであって、
「FAT32ではなくexFATを選べ」ということではありません。
FAT32で動くのでしたら、それで実験を続けていただいて構いません。
