### ISSUE TITLE
マルチコアの場合について

### ISSUE THREAD

**Issue by nonononoka** [uchan-nos/os-from-zero#171]
13章あたりまでmikanOSを実装しました。参考にさせていただいております。ありがとうございます。
本書を読んでいて疑問が生じたのですが、現代のPCはほとんどがマルチコアとなっていて各コアにつき別々のレジスタ群を持っていると思います。本書ではアセンブリで直接レジスタの値をいじったりする場面が多々生じると思いますが、どのコアのレジスタを書き換えているのでしょうか？どこかで指定していましたでしょうか？

**Comment by uchan-nos** [comment]
MikanOS ではマルチコアを有効にしていないため、1 つのコアだけが動いた状態になり、他のコアは動作開始の指令を待つ状態になっています。
最初から動作するコアのことを BSP: Bootstrap Processor と呼びます。
MikanOS が使っているのは BSP のレジスタということになります。
