### ISSUE TITLE
QEMUの立ち上げに関して

### ISSUE THREAD

**Issue by kumanotani** [uchan-nos/os-from-zero#18]
第一章でc言語でHelloWorldを出すところでの質問です。
p43でhello.efiを作成した後

`$HOME/osbook/devenv/run_qemu.sh hello.efi`

でQEMUを立ち上げようと試みたのですが、以下のようなエラーメッセージが表示されうまく立ち上がりません。

```
(qemu) qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
Could not initialize SDL(No available video device) - exiting
```
WSL2+vscodeを使用しています。
1.4エミュレータでのやり方の手順に沿って、A.2 WSLでQEMUを使う準備は終えています。

**Comment by uchan-nos** [comment]
ちょっとよく分からないので、追加で情報をいただきたいです。
とりあえず、DISPLAY変数がきちんと設定されているか教えてください。
以下のコマンドで表示できます。

```
$ echo $DISPLAY
```

**Comment by kumanotani** [comment]
ご対応有難うございます。情報不足で申し訳ありません。

```
$ echo $DISPLAY
>>localhost:0.0
```

と表示されました。

**Comment by uchan-nos** [comment]
おっと、それは想定外の値ですね。

Ansibleによりセットアップすると、WSL2の場合には次の行が実行され、
https://github.com/uchan-nos/mikanos-build/blob/c78c13b1b86ec30e57412736683ef7c2c1984ab9/devenv/ansible_provision.yml#L118

結果としてDISPLAYには
WindowsのIPアドレス:0.0
という値が入るはずなのです。

試しに、Windows側のIPアドレスを調べてDISPLAY変数を手動で設定してみてもらえますか？
設定するコマンドは次の通りです。

```
export DISPLAY="IPアドレス:0.0"
```

**Comment by kumanotani** [comment]
`$ export DISPLAY="IPアドレス:0.0"`

上のコマンドを打ち込んだ後、もう一度

`$ $HOME/osbook/devenv/run_qemu.sh hello.efi`

を実行したところ、無事にQEMUが立ち上がりました。有難うございます。

**Comment by uchan-nos** [comment]
良かったです。

exportコマンドを用いた環境変数の設定は、シェルを再起動するたびに初期化されてしまいますので、
永続的に設定するためには $HOME/.profile というファイルに設定を書き込んでください。

.profileには既に `export DISPLAY=>>localhost:0.0` というような行があると思いますので、
設定値を変更していただければ大丈夫かと思います。

Ansibleでの自動設定が上手くいかないケースがあるということで、改善できるかもしれませんので、
もしよろしければ、WSLの /etc/resolv.conf ファイルの中身をいただけないでしょうか？
（このissueに添付するか、中身を貼り付けていただければ）

**Comment by kumanotani** [comment]
~/.profile では

`export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0`

となっていました。これはQEMUの立ちあがりが上手くいかなかった時点においても、この記述があったことを確認しております。


/etc/resolv.conf ファイルの中身ですが、以下に貼らせていただきます。

```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver IPアドレス(WSL)
```

**Comment by uchan-nos** [comment]
ありがとうございます！

うーん、~/.profileと/etc/resolv.confは全然壊れてないようです。
なぜこれでDISPLAYに `>>localhost:0.0` などという値が
設定されてしまうのかまったく謎です……

kumanotaniさんの手元ではDISPLAY変数の再設定で上手くいくということで、
根本的な原因は未解決ですが質問クローズさせていただきます。
