### ISSUE TITLE
P.52 リスト2.3の表記について

### ISSUE THREAD

**Issue by nokute78** [uchan-nos/os-from-zero#19]
P.52 の記載が
 `リスト2.3 EDK II の Uefi.h 体`
となっており、最後の`体`が気になりました。

その下にあるリスト2.4については、
`リスト2.4 EDK II の UefiBaseType.h` となっていたので、体が過剰に記載されているのでしょうか。

**Comment by nokute78** [comment]
加えて、同ページの `リスト2.4 EDK II の UefiBaseType.h` もBold処理がかかっていないように見えます。

**Comment by uchan-nos** [comment]
報告ありがとうございます
