### ISSUE TITLE
P.55 表2.3 の Type 4 について

### ISSUE THREAD

**Issue by nokute78** [uchan-nos/os-from-zero#20]
Type 3 および 4ともに `EfiBootServicesCode` となっていますが、
Type 4 は `EfiBootSerivicesData` ではないでしょうか。
https://github.com/tianocore/edk2/blob/c640186ec8aae6164123ee38de6409aed69eab12/BaseTools/Source/C/Include/Common/UefiMultiPhase.h#L23

**Comment by uchan-nos** [comment]
そのとおりです。報告ありがとうございます
