### ISSUE TITLE
P.80 図3.6 のジャンプ先アドレスの説明について

### ISSUE THREAD

**Issue by south37** [uchan-nos/os-from-zero#23]
## 観測した内容
P.80 の図3.6の説明文は以下のようなものになっています。

> 実際にメインメモリの内容を確認した様子を**図3.6**に示します。<中略>次にそのジャンプ先アドレス 0x669f028 が指すメモリ領域を表示してみました。

## 意図と反した部分
図3.6の中では `jmp 0x101010` と表記されており、ジャンプ先アドレスは 0x101010 に見えます。

## 期待した内容
図3.6に合わせて、説明文としても「ジャンプ先アドレス 0x101010 が指すメモリ領域」と記載されることを期待しました。

## その他、細かい部分で気がついたこと
「観測した内容」に記載した P.80 の以下の文章中で、「`jmp` 命令」という単語の左側の空白が大きいように見えます。組版システムに起因するものかもしれませんが、もしかすると「全角空白文字が入ってしまっているかもしれない」と思い、追記いたしました。

> 実際にメインメモリの内容を確認した様子を**図3.6**に示します。まずは RIP が指すメモリ領域を表示したところ　`jmp` 命令がありました。次にそのジャンプ先アドレス 0x669f028 が指すメモリ領域を表示してみました。

**Comment by uchan-nos** [comment]
ご報告ありがとうございます。

ご認識の通り（ジャンプ先は0x101010）で合っています。
プログラムを改造してスクリーンショットを取って差し替えたときに、本文を直し忘れてこうなってしまいました。

`jmp` 命令の左の余白についても発見していただきありがとうございます。
