### ISSUE TITLE
gitの環境構築のところで

### ISSUE THREAD

**Issue by zootaka** [uchan-nos/os-from-zero#24]
$ansible-playbook -K -i ansible_inventory ansible_provision.yml
上記のコマンドを打ったところで

fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["dpkg-query", "--show", "qemu-system-gui"], "delta": "0:00:00.036334", "end": "2021-03-27 18:06:28.188888", "msg": "non-zero return code", "rc": 1, "start": "2021-03-27 18:06:28.152554", "stderr": "dpkg-query: no packages found matching qemu-system-gui", "stderr_lines": ["dpkg-query: no packages found matching qemu-system-gui"], "stdout": "", "stdout_lines": []}
...ignoring
というエラーが出ました

このエラーに気づかずmikannOSのビルドのところの
$ ./build.sh run
このコマンドを打ったところ
+ mkdir -p ./mnt
+ sudo mount -o loop ./disk.img ./mnt
[sudo] password for zootaka:
mount: ./mnt: mount failed: Operation not permitted.

とでてquemで起動できずに終了してしまいました。

**Comment by uchan-nos** [comment]
まず、Ansible のエラーに見える表示は、エラーはエラーでも無視して良いエラーです。
最終行に「...ignoring」とあるのが、無視して良いエラーである証拠です。

このエラーは qemu-system-gui パッケージの存在が存在しない場合に dpkg-query コマンドが失敗したエラーです。

build.sh run のエラーは、見たところ Ansible の（無視してよい）エラーとは無関係だと思います。
sudo で mount を実行しているのに Operation not permitted と出るのは想定外です。

ちょっと調べてみると、以下の記事に、Docker 上で sudo mount コマンドを実行した際に
そのようなエラーが出るという情報がありました。参考になりますでしょうか？

https://qiita.com/yuyakato/items/dee9a6f17cf0b49e6579#5-%E8%A3%9C%E8%B6%B3---privileged%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by zootaka** [comment]
対応ありがとうございます。
私の環境はwsl2のubuntu18.04なのでこの記事のコマンドは使えなさそうです。

**Comment by zootaka** [comment]
ubuntu入れなおしてもう一度最初から環境構築したらできました。

**Comment by uchan-nos** [comment]
お役に立てずすみません。解決したとのことで、クローズさせていただきます
