### ISSUE TITLE
p,51 表2.1について

### ISSUE THREAD

**Issue by YzT1131** [uchan-nos/os-from-zero#26]
EDK IIでMikanLoaderPkgをビルドする設定を行うところについて(p,51 第一パラグラフ～表2.1)の質問です。

ここでやろうとしているのはConf/target.txtのファイルを開いて、
ACTIVE_PLATFORM = xxxx
などとなっている部分のxxxxを書き換えていく、ということだと思っておりますが、
ACTIVE_PLATFORM、TARGET、TARGET_ARC、TOOL_CHAIN_TAGという項目は見つかったのですが
一番最後の「3」という項目が見当たりません。

どこを書き換えればいいのでしょうか。

**Comment by YzT1131** [comment]
すみません、改めて過去のissueを確認したら既出だったのを発見しました。
本来表2.1は以下の図の通りであると了解しました。
![image](https://user-images.githubusercontent.com/62990195/112739274-de805a80-8fad-11eb-9aff-78ca037efcc9.png)

**Comment by uchan-nos** [comment]
本書の表が間違っておりすみません。
お示しのissueで合っております。
