### ISSUE TITLE
【誤植】表2.1の1行目の網掛けは無いほうが良いです

### ISSUE THREAD

**Issue by hnakamur** [uchan-nos/os-from-zero#3]
まず最初に素晴らしい本をありがとうございます！

本題ですが、p.51の表2.1の1行目が網掛けになっていて表のヘッダ行なのかなと勘違いして設定を入れ忘れたので網掛けは無いほうが良いと思います。

また最後の行の 3 0x3 というのは 3 = 0x3 という設定を追加して書くという意味でしょうか？
それでビルドは出来たのですが、設定項目名が3というのは違和感があり正しいのか気になります。

**Comment by uchan-nos** [comment]
報告ありがとうございます。

表2.1は画像のようになることを意図していました。
完全なる作業ミスです。すみません。

![正しい表2.1](https://user-images.githubusercontent.com/1825663/111935080-08e19c00-8b06-11eb-8646-222bccefb0c2.png)

この issue は私が対処したら閉じますので、open のままにしておいていただけると幸いです。

**Comment by uchan-nos** [comment]
報告いただいた他の issues も含めて、正誤情報へ記載させていただきました！
