### ISSUE TITLE
p.154 SwitchEhci2Xhciのコード

### ISSUE THREAD

**Issue by lemoncmd** [uchan-nos/os-from-zero#31]
```c
Log(kDebug, "SwitchEhci2Xhci: SS = %02, xHCI = %02x\n",
```
の`%02x`で前者、xが抜けています

**Comment by uchan-nos** [comment]
ご報告ありがとうございます。

プログラムの修正なので、本書はそのままにして、mikanosリポジトリの方を更新しようと思います。
リスト6.22は、バグがあるまま残します。

もしよかったら、mikanosリポジトリの方にプルリクをいただけませんか？
