### ISSUE TITLE
P.50 4行目 "Main.c では #nclude でそれを取り込むだけで良くなったからです。"

### ISSUE THREAD

**Issue by muramasa64** [uchan-nos/os-from-zero#32]
初版第 1刷 電子版ver 1.00
2.2 EDK IIでハローワールド（osbook_day02a）
P.50
4行目

"Main.c では `#nclude` でそれを取り込むだけで良くなったからです。" とありますが、
"Main.c では `#include` でそれを取り込むだけで良くなったからです。" の誤記かと思います。

**Comment by uchan-nos** [comment]
ありがとうございます。既に正誤情報にて対応済みなのでクローズします。
