### ISSUE TITLE
環境構築（mikanos-buildの方）でつまづいています

### ISSUE THREAD

**Issue by nosochang** [uchan-nos/os-from-zero#34]
WindowsのWSL、Ubuntu、Linux、githubとも初めてさわる業務系プログラマです（DOSコマンドは多少わかる程度ですが、VBやC#、SQLなどは使えます）

手元のPCはWindows10 Homeです

まず、付録A 開発環境のインストールのA.01とA.02を何度かやり直しながら進めました。Ubuntuは18.04、QEMUは最新にしました。

次に、https://github.com/uchan-nos/mikanos-buildに 従って進めています。
1.ビルド環境の構築
・「リポジトリのダウンロード」上手くいってそう
・「開発ツールの導入」上手くいってそう
・「標準ライブラリのライセンスについて」のところは読んだだけ
　　→もしかして何かしないといけませんか？
２.MikanOS のソースコードの入手
　　→上手くいってそう
3.ブートローダーのビルド
　　→上手くいってない

「ln -s /path/to/mikanos/MikanLoaderPkg ./」を実行すると、
「ln: failed to create symbolic link './MikanLoaderPkg': File exists」
（ただし何度かたたいているのでちゃんとできているかも）

「ls MikanLoaderPkg/Main.c」を実行すると
「ls: cannot access 'MikanLoaderPkg/Main.c': No such file or directory」

という状況です。進めるために何をしてよいかが分からずにいます。
よろしくお願いします。

**Comment by char-khan** [comment]
こんにちは。

「ln -s /path/to/mikanos/MikanLoaderPkg ./」コマンドをコピーしてそのまま使っていないでしょうか？

> `/path/to/mikanos` は先ほど `git clone` でダウンロードした mikanos ディレクトリへのパスを指定します。

とある通り、自分の環境に合わせて変更する必要があります。

また、上記のコマンドはリンクを上書きできないため
「ln: failed to create symbolic link './MikanLoaderPkg': File exists」
というエラーが出ています。

`ln -nfs /path/to/mikanos/MikanLoaderPkg ./` のように上書きオプションをつけて試してみてください。

**Comment by nosochang** [comment]
ありがとうございます。
はい、「ln -s /path/to/mikanos/MikanLoaderPkg ./」コマンドをコピーしてそのまま使っています…。他のも全部。

では私はどこにダウンロードしたのだろうかという…（恥ずかしい！）
１つずつコピーして実行しているので、
「git clone https://github.com/uchan-nos/mikanos.git」の前で最後に実行したcdは「cd $HOME/osbook/devenv」です。

いま気が付いたのですが、MikanOSのソースコードの入手については書籍の付録Bをみればよかったですね…。

土曜くらいまでに落ち着いてやってみます。結果はまたご報告いたします。

**Comment by nosochang** [comment]
mikanosディレクトリを移動しようとするも迷子になり断念しました…

結局Ubuntuのリセットをして、付録Aの手順を途中からやり直し、https://github.com/uchan-nos/mikanos-build の手順を完了する事ができました。ありがとうございました。


以下は詳細です（もし私と同レベルの方がおられましたらご参照ください）

【Ubuntuのリセット】
　スタート > 設定 > アプリ > アプリと機能 の Ubuntu のところの「詳細オプション」をクリックし、画面下の方の「リセット」 というボタンを押す。
　そうすると、書籍の付録Aの「A.01 WSLのインストール」の手順8（初版p717の3行目）まで実行した状態に戻る。

【MikanOSのソースコードの入手】
書籍の付録Bを参考に、$HOME/workspace にダウンロード。
以降、
「ブートローダーのビルド」の
「ln -s /path/to/mikanos/MikanLoaderPkg ./」は「ln -s $HOME/workspace/mikanos/MikanLoaderPkg ./」
「MikanOS のビルド」の
「$ cd /path/to/mikanos」は「$ cd $HOME/workspace/mikanos」
と読みかえました。

途中、「ファイルをエディタで開き」については「ubuntu テキストエディタ」で検索して解決しました。
