### ISSUE TITLE
mount: ./mnt: mount failed: Operation not permitted.が出る

### ISSUE THREAD

**Issue by ohfujimasa73** [uchan-nos/os-from-zero#35]
/osbook/devenv$ ./run_qemu.sh hello.efiを実行すると下記エラーが出る

+ [ 1 -lt 1 ]
+ dirname ./run_qemu.sh
+ DEVENV_DIR=.
+ EFI_FILE=hello.efi
+ ANOTHER_FILE=
+ DISK_IMG=./disk.img
+ MOUNT_POINT=./mnt
+ ./make_image.sh ./disk.img ./mnt hello.efi
+ [ 3 -lt 3 ]
+ dirname ./make_image.sh
+ DEVENV_DIR=.
+ DISK_IMG=./disk.img
+ MOUNT_POINT=./mnt
+ EFI_FILE=hello.efi
+ ANOTHER_FILE=
+ [ ! -f hello.efi ]
+ rm -f ./disk.img
+ qemu-img create -f raw ./disk.img 200M
Formatting './disk.img', fmt=raw size=209715200
+ mkfs.fat -n MIKAN OS -s 2 -f 2 -R 32 -F 32 ./disk.img
mkfs.fat 4.1 (2017-01-24)
+ ./mount_image.sh ./disk.img ./mnt
+ [ 2 -lt 2 ]
+ dirname ./mount_image.sh
+ DEVENV_DIR=.
+ DISK_IMG=./disk.img
+ MOUNT_POINT=./mnt
+ [ ! -f ./disk.img ]
+ mkdir -p ./mnt
+ sudo mount -o loop ./disk.img ./mnt
mount: ./mnt: mount failed: Operation not permitted.

**Comment by rkarsnk** [comment]
@ohfujimasa73 
`/osbook/devenv/`にhello.efi、disk.img、mntディレクトリは作成されています？

気になる点があるので、補足してもらえますか？
- 開発環境について(WSL2＋Ubuntu18.04とか、Ubuntu 18.04とか)
- `./run_qemu.sh`を実行している場所が`/osbook/devenv`になっていますが、`$HOME/osbook/devenv`の間違い？

**Comment by ohfujimasa73** [comment]
最初から入れなおしたら起動しました。
