### ISSUE TITLE
P. 215 ページ途中の "リスト 9.11 にレイヤを描画するためのメソッド~" という部分の文字の太さについて

### ISSUE THREAD

**Issue by south37** [uchan-nos/os-from-zero#37]
## 観測した内容
P. 215 ページ途中の "リスト 9.11 にレイヤを描画するためのメソッド~" という以下の文章中で、`リスト9.1` だけが太字になっているように見えます。

> **リスト 9.1**1 にレイヤを描画するためのメソッド DrawTo() を示します。

## 期待した内容
`リスト 9.11` までが太字であることを期待しました。

ng: **リスト 9.1**1 
ok: **リスト 9.11**

**Comment by uchan-nos** [comment]
ご報告ありがとうございます！

**Comment by south37** [comment]
ありがとうございます！ 😄
