### ISSUE TITLE
P186の図8.1について

### ISSUE THREAD

**Issue by kokihonda** [uchan-nos/os-from-zero#38]
図8.1(a)のRIPは0x12345670を指しているように見えますが、図8.1(b)ではRIPの値として0x12345672を保存しています。
これは正しいのでしょうか?

**Comment by uchan-nos** [comment]
はい。正しいです。

なぜなら、CPU は call rax 命令を実行する直前に、次の命令を指すように RIP を更新するからです。
call rax は 0xff 0xd0 という 2 バイト命令なので、call rax を実行している最中には、RIP は 2 バイト先を指していることになります。
