### ISSUE TITLE
WSL1でmountできない

### ISSUE THREAD

**Issue by shimizus** [uchan-nos/os-from-zero#39]
はじめまして

WSL1でmountによるdisk.imgのマウントを実施しようとしているのですが

mount: ./mnt: mount failed: Operation not permitted.

となりマウントできません

WSL1では不可のような情報をみかけるのですができないのでしょうか。WSL2や他のLinux環境にする必要がありますか

よろしくお願いします

**Comment by gorira-tatsu** [comment]
参照しているページはp61ですか？

**Comment by shimizus** [comment]
開発環境構築の章(WSL)や環境に含まれるスクリプト実行で発生します

**Comment by uchan-nos** [comment]
今手元で試せる環境が無いため実験はしていませんが、調べてみると、おっしゃる通り WSL1 ではマウント操作は出来ないかもしれません。
WSL2 を使うか、Hyper-V や VirtualBox 等で起動した Linux でならマウント操作が可能です。

あるいは、WSL1 のままでも Mtool（ https://www.gnu.org/software/mtools/ ）のようなものを使うことで、マウント操作をすること無くディスクイメージの読み書きができます。

Mtool は Ubuntu にもともとインストールされていると思います。次のコマンドを試してみてください。

```
$ mdir -i disk.img ::/
```

ディスクイメージ disk.img に保存されたファイルの一覧が表示されるはずです。

Mtool のコマンドには共通で `-i ディスクイメージ` というオプションを渡すことができ、操作対象を実際のディスクではなくディスクイメージにすることが可能です。

第 3 引数の `::/` の先頭の `:` は、ディスクイメージを指す特殊なドライブレターです。ドライブレータとは、Windows で絶対パスを表記する際の先頭の文字（`C:\ファイル名` の「C」）です。2 文字目の `:` はドライブレターとパスを区切る記号、3 文字目の `/` はパス（ルートディレクトリを表す絶対パス）ですね。

ディスクイメージに保存された /EFI/BOOT/BOOTX64.EFI を取り出し、hello.efi という名前で保存するには、次のコマンドを使います。

```
$ mcopy -i disk.img ::/EFI/BOOT/BOOTX64.EFI hello.efi
```

逆に、手元のファイル（例えば kernel.elf）をディスクイメージに保存するには次のようなコマンドで可能です。

```
$ mcopy -i disk.img kernel.elf ::/KERNEL.ELF
```

**Comment by shimizus** [comment]
アドバイスありがとうございます。試してみます。

今は、以下のコマンドで起動させています。
qemu-system-x86_64 \
        -bios /usr/share/ovmf/OVMF.fd -drive format=raw,file=fat:rw:$DIR_ \

しかしながら、スクリプトの他のオプションを適用することができていない状況です。
(適用すると起動しなくなる)

**Comment by uchan-nos** [comment]
なるほど。ディレクトリ以下を FAT ファイルシステムとして認識させる機能を使っているのですね。それも良いと思います。ただ、本書でその機能を使わなかったのは、動作が少し不安定だったからです。ディスクイメージだと安定して動作したので、そちらを採用しました。ですので、もし `fat:rw:` でうまく実行できるのであれば、それでも構いません。

本書の起動用スクリプトの中で指定しているオプションのいくつかと、shimizus さんが示されたオプションが競合するため、本書のオプションをすべて追加するとダメになってしまうと思います。

run_image.sh で指定してるオプションは次の通りです。

```
qemu-system-x86_64 \
    -m 1G \
    -drive if=pflash,format=raw,readonly,file=$DEVENV_DIR/OVMF_CODE.fd \
    -drive if=pflash,format=raw,file=$DEVENV_DIR/OVMF_VARS.fd \
    -drive if=ide,index=0,media=disk,format=raw,file=$DISK_IMG \
    -device nec-usb-xhci,id=xhci \
    -device usb-mouse -device usb-kbd \
    -monitor stdio
```

これらのオプションのうち、`-m 1G`、`-device nec-usb-xhci,id=xhci`、`-device usb-mouse -device usb-kbd`、`-monitor stdio` shimizus さんのオプションと競合しないのではないかと思います。

**Comment by uchan-nos** [comment]
特に追加質問がなさそうなので、issue を閉じますね
