### ISSUE TITLE
P35　1.4エミュレータでのやり方あたりについて

### ISSUE THREAD

**Issue by nakkinn** [uchan-nos/os-from-zero#40]
・WSL、エミュレータを使う場合はP28～P32の作業はすべて不要ですか？
・WSLを使うのでBinary Editor Bzを用いてP29の数列を入力しました。しかしこのファイルをどうするかが分かりません。BOOTX64.EFIと名前を付けてUSBメモリにいれるのでしょうか？

P34の$sudo cp BOOTX64.EFI /mnt/usbmem/EFI/BOOTのところでcannot stat 'BOOTX64.EFI' : No such file or directoryと出る原因が分からず困っています

**Comment by Sorakime** [comment]
後者の問題について回答させてもらいます。
そちらのファイルは、USBメモリの`/EFI/BOOT/BOOTX64.EFI`として保存して、いずれかのPCでそちらのUSBから起動すればOKです。

**Comment by gorira-tatsu** [comment]
>回答ありがとうございます。BOOTX64.EFIがEFI、BOOTフォルダの外にあったのでBOOTの中に入れておきました。USBから起動するというのはエミュレータを使うやりかたでも必要ですか？

WSLを使用して、USBに書き込み実機で起動する場合＞
実機で指して、起動しなければいけない

WSLからWindows側に転送してlinuxの画面（エミュレーター）をWindowsで表示する方法＞
USBでなくても大丈夫。エミュレーターなどを使用したやり方については、付録Aの02(p717)に詳しく書いています。

**Comment by nakkinn** [comment]
後者のWSLからエミュレータを表示する方法ではUSBメモリを一切使わない、p33，34のフォーマット、マウントする作業もしないということで合ってますか？

**Comment by gorira-tatsu** [comment]
はい（間違ってたら本当にごめんなさい）
