### ISSUE TITLE
osbook_day15b で実行後すぐにTaskBウィンドウが消える

### ISSUE THREAD

**Issue by char-khan** [uchan-nos/os-from-zero#42]
### 環境
WSL2 
Ubuntu18.04

### 現象
タグ osbook_day15b をビルドして実行すると、TaskBウィンドウが一瞬表示された後消えてしまう。
TaskB関連のコードがなくなる osbook_day16f までのタグ全てで同様の事象を確認しました。

### 原因　と思われるもの
main.cpp にてマウスを初期化する前に TaskBウィンドウをアクティブ化してしまっている。（[参考](https://github.com/uchan-nos/mikanos/blob/02e2095944a41b5973a980a326a183cdd4b1820c/kernel/main.cpp#L199-L218)）

Activate メソッドでは対象のレイヤをマウスレイヤの1つ下に[移動させる](https://github.com/uchan-nos/mikanos/blob/02e2095944a41b5973a980a326a183cdd4b1820c/kernel/layer.cpp#L212)が
マウスレイヤは[マウス初期化処理](https://github.com/uchan-nos/mikanos/blob/02e2095944a41b5973a980a326a183cdd4b1820c/kernel/mouse.cpp#L113)にて登録されるため、
マウス初期化前に Activate メソッドを呼び出すとマウスレイヤの位置を検索する処理で未発見の「-1」が[返され](  https://github.com/uchan-nos/mikanos/blob/02e2095944a41b5973a980a326a183cdd4b1820c/kernel/layer.cpp#L178)、
そこから 1 を引いた位置「‐2」へレイヤを移動しようとして負数なので[非表示になる](https://github.com/uchan-nos/mikanos/blob/02e2095944a41b5973a980a326a183cdd4b1820c/kernel/layer.cpp#L108-L111)。

### 対処法
TaskBウィンドウのアクティブ化処理をマウス初期化処理より下に持ってくる。

**Comment by uchan-nos** [comment]
報告ありがとうございます。MikanOSのバグは基本的に修正しない方針を取っていますので、このIssueはメモだけして閉じてしまいますね。
