### ISSUE TITLE
[質問]osbook_day06cでのPCI一覧取得について

### ISSUE THREAD

**Issue by CrabPunch** [uchan-nos/os-from-zero#44]
●問題現象
xhc.Initializeでsuccessまでいっていますが、マウスカーソルが動きません。

●確認したこと
PCIデバイス一覧を取得の後、
classがclass_code.Match(0x0cu, 0x03u, 0x30u)にてフィルタされ
VendorIdがIntel(0x8086)のものが優先されるかと思うのですが。

classのMatchが書籍だと0c033011
私の環境下ですと0330030cがMatchします。
またVendorIdが0x8086ではありません。

Logを出力して確認したところ
xhc.Initialize:kSuccess
xHC startingまでは流れています。
![06c](https://user-images.githubusercontent.com/35165742/114299260-3f06b000-9af5-11eb-9b00-450092215942.png)

●質問
この場合Matchの値に関しては順不同でも問題ないものでしょうか？

**Comment by uchan-nos** [comment]
すみません。質問の意味が正確には分かりませんでした。

> この場合Matchの値に関しては順不同でも問題ないものでしょうか？

順不同、とは何を指しているのでしょうか。

書籍の図6.5ではデバイス0.20.0のクラスコードが「0c033011」であることに対して、CrabPunchさんの環境では「0330030c」となっていて左右が逆に見える、という現象を指して「順不同」と言っているのでしょうか？
ということであれば、質問の直接的な答えは「Matchは順不同ではなく、順序を考慮した比較を行います」となります。

----
さて、ここからは質問への直接的な回答ではありませんが、問題解消に向けて参考になるかもしれない情報を書きます。

CrabPunchさんの環境で「0330030c」と表示されていることが不可解です。osbook_day06bの内容を私の手元のQEMUで実行したら「0c033003」と、図6.5と同様の順序で表示されました。なぜ、CrabPunchさんのQEMUでは順序が逆なのか不明です。

osbook_day06bでコンソールに表示しているクラスコード（8桁の16進数）は、本書の図6.3の0B-08hにある32ビットの値です。この32ビットはベースクラス、サブクラス、インタフェース、リビジョンを含みます。したがって、想定されているのはベース=0c、サブ=03、インタフェース=30、リビジョン=03です。

CrabPunchさんのQEMUの出力結果がなぜそうなっているのか。一つ考えられるのはエンディアンの違いです。もし、PCIコンフィギュレーション空間を読む際にビッグエンディアンとして読み取ってしまうと、添付画像のような出力結果になるかもしれません。

しかし、ベンダID（8086など）は正しい順序で表示されているため、クラスコードを読み取るときだけエンディアンが違う、というのも考えづらいのですが。ということで、原因は他のところにあるかもしれませんが、今ある情報だけでは何とも言えません。

**Comment by CrabPunch** [comment]
ご回答ありがとうございます。
>>Matchは順不同ではなく、順序を考慮した比較を行います
承知いたしました。

またclassコードの表示がおかしい件もありがとうごいます。
まずスキャンででてきているバスの候補がおかしいか、
そのあとのポートなりの候補がおかしいのか切り分けたかったので助かります。
一旦ScanAllBusの結果まわりを調べ直したいと思います。

また私のほうの環境ですとwindowsのamdcpuでのwls2からの起動となっています。
まずは一旦widowsのほうにてホストコントローラーとusbポートなど確認してから
同一ものが存在してるかなど踏まえてから、表示確認にはいろうかと思います。

**Comment by uchan-nos** [comment]
[Twitter で指摘](https://twitter.com/ngtkd/status/1382306032823664642?s=20) があり、気付きました。

osbook_day06c では、`ReadClassCode()` が `ClassCode` を返すようになっているので、
それをそのまま `%08x` で表示すると左右反転して表示されるかもしれません。

`ClassCode` 構造体は 1 バイトの変数が base, sub, interface の順で並んでいます。
メモリ上でこの順番ということは、この構造体を `%08x` で無理矢理表示しますと、
確かに反転して表示されると思います。

表示が左右反転しているのはそのような原因だとして、依然としてマウスが動かない原因は分かりませんけどね……

**Comment by CrabPunch** [comment]
追加情報ありがとうございます。
おっしゃる通りの問題でした、
構造体要素ごとに表示したら以下のようになりました。
ありがとうございます。
![6c-2](https://user-images.githubusercontent.com/35165742/114796365-b8d7bb80-9dcb-11eb-8a4c-62614f1144f2.png)






マウス認識に関してはデバイスマネージャーのほうから確認しても
複合デバイス扱いのマウスしか現在手持ちがないので
土日あたりにでもシンプルなものを買って来てから
原因を追ってみようかと思います。

**Comment by CrabPunch** [comment]
お世話になっております。

完全に原因が理解できた訳ではないのですが、
その後Logを追加しながら動作確認していたのですが
xHC starting以降の部分をみていたのですが、

`
   Log(kInfo, "xHC starting[%d]\n", xhc.MaxPorts() );
  xhc.Run();
  // #@@range_end(init_xhc)
  Log(kDebug, "xhc  port check1: \n");

  // #@@range_begin(configure_port)
  usb::HIDMouseDriver::default_observer = MouseObserver;

  Log(kDebug, "xhc  port check2: \n");

`

![6c-3](https://user-images.githubusercontent.com/35165742/115107032-605b1680-9fa3-11eb-8a64-d6ce929f296a.png)


という結果になり、
  usb::HIDMouseDriver::default_observer = MouseObserver;
の所で停止しているようです。

この行をコメントアウトすると以降のLogは流れます。

なぜstd::functionの設定の部分で停止しているかは
理解が追い付いていません。

**Comment by uchan-nos** [comment]
うーん。なんですかね。よく分からないです。

私がデバッグするとしたら、usb::HIDMouseDriver::default_observer の配置アドレスを確認したり、
std::function が内部で動的メモリ確保をしようとして死んでいる可能性を探ったり、
といったことをすると思います。

**Comment by CrabPunch** [comment]
お世話になっております。
std::functionに関しては
静的領域のものが止まり。
ローカルの場合はstd::functionへのセットは動作しておりました。

![6c-4](https://user-images.githubusercontent.com/35165742/115146214-7f83a200-a090-11eb-87a2-9f3754c42155.png)
![6c-5](https://user-images.githubusercontent.com/35165742/115146217-83172900-a090-11eb-9d57-5ed1e004a4e9.png)

いったん
HIDMouseDriver内のstd::function関連の制御を関数ポインタに
全て書き換えた場合、マウスの座標取得と更新がうまく動きました。

**Comment by CrabPunch** [comment]
マウスの座標関連は動いたので

一旦、こちらの質問は最初の投稿からはずれてきそうなので
closeしてstd::functionの件を別途issueとして投稿したほうがいいでしょうか？
それともこのまま、残しておいたほうがよいでしょうか？

**Comment by mituha** [comment]
@CrabPunch 同じところで引っかかって困ってました。  
差し支えなければどのように修正されたか教えていただけませんでしょうか？  

`usb::HIDMouseDriver::default_observer = MouseObserver;` の設定時点で動作しなくなる模様。

**Comment by CrabPunch** [comment]
@mituha さん
こちらでやった修正内容としては以下のようになります。  


・main.cpp
  usb::HIDMouseDriver::default_observerFP = MouseObserver; //add
//  usb::HIDMouseDriver::default_observer = MouseObserver; //sub

・usb-classdriver-mouse.h
![mouseh](https://user-images.githubusercontent.com/35165742/116801579-40e8ef80-ab46-11eb-9248-caae869c943a.png)


・usb-classdriver-mouse.cpp
![mousecpp](https://user-images.githubusercontent.com/35165742/116801582-43e3e000-ab46-11eb-9d2a-f0d60cf27bc2.png)

・usb-device.cpp
![usbdevice](https://user-images.githubusercontent.com/35165742/116801585-46ded080-ab46-11eb-8b98-134149599a16.png)

**Comment by mituha** [comment]
@CrabPunch ありがとうごさいます。

最終的に、コードの書き換え自体を最小として、変数名とかそのままに、
```
    //using ObserverType = void (int8_t displacement_x, int8_t displacement_y);
    using ObserverType = void (*)(int8_t, int8_t);

    //static std::function<ObserverType> default_observer;
    static ObserverType default_observer
;
    //std::array<std::function<ObserverType>, 4> observers_;
    ObserverType observers_[4];
```
上記のように関数ポインタに変更、`std::function` 、`std::array` を使用しないように変更、関連部分も調整して進むようになりました。  
std関連がうまく行っていないのかもしれません。

**Comment by CrabPunch** [comment]
std::functionに関しては私の環境下ですと
staticをやめれば動きはするとこは確認できたのですが、
staticで確保されている位置の問題かもしれませんね、、
現状はこちらのワークアラウンドにて先に進めることにしています。

**Comment by uchan-nos** [comment]
@CrabPunch 
> マウスの座標関連は動いたので
> 
> 一旦、こちらの質問は最初の投稿からはずれてきそうなので
> closeしてstd::functionの件を別途issueとして投稿したほうがいいでしょうか？
> それともこのまま、残しておいたほうがよいでしょうか？

はい。この件はcloseが望ましいです。std::functionが動かない件は今のissueのタイトルと乖離が激しいので。

std::functionの件は私の環境では（当然）動いており、CrabPunchさんが主体となってデバッグを進めることになります。
私からの支援はあまり望めないと思いますが、それでもよければデバッグの過程をメモするなどの目的でissueをご利用ください。

**Comment by CrabPunch** [comment]
@uchan-nos 
承知しました。
別途issueは作成しましたので
[https://github.com/uchan-nos/os-from-zero/issues/57](url)

こちらはcloseさせていただきます。

ありがとうございます。
