### ISSUE TITLE
Macでのビルドについて

### ISSUE THREAD

**Issue by nyandau5648** [uchan-nos/os-from-zero#45]
Mac で始める「ゼロからのOS自作入門」(https://qiita.com/yamoridon/items/4905765cc6e4f320c9b5)にて
git clone https://github.com/tianocore/edk2.git
でインストールしたのですが、最後のビルドで失敗し、edk2-stable202011ならビルドできるとTwitterで聞いたので
edk2-edk2-stable202011.zip
を先ほどのedk2.gitでインストールしたものを削除してから再度ビルドしてみました。
しかし、Loader.infは作れるのですが、Loader.efiが作られません。
何度も試してもできないのですが、何かインストールしていないのでしょうか？
![スクリーンショット 2021-04-13 11 02 41](https://user-images.githubusercontent.com/72236055/114485934-c6643880-9c47-11eb-9fc7-a42acd68abd5.jpg)

**Comment by uchan-nos** [comment]
エラーメッセージを見ると

> BaseTOols C Tool binary was not found (GenFw)
> You may need to run:
>   make -C /Users/Newton/edk2/BaseTools/Source/C

となりますね。このコマンドを実行してみてください。

mikanos-build のセットアップスクリプトでは、それをやってるんですよね。
https://github.com/uchan-nos/mikanos-build/blob/8452658934f4572012b95e6db12f0f0456ae777c/devenv/ansible_provision.yml#L98-L100

ちなみに

> Loader.infは作れるのですが

とありますが、Loader.inf は build コマンドによって生成されるものではなく、MikanOS のソースコードとして最初から存在するものですね。

**Comment by rkarsnk** [comment]
> git clone tianocore/edk2.git
でインストールしたのですが、最後のビルドで失敗し、edk2-stable202011ならビルドできるとTwitterで聞いたので

単純にgit cloneした場合だと、submoduleがダウンロードできてないと思います。

```
git clone --recursive tianocore/edk2.git
```
で、edk2を取得してみてください。

**Comment by uchan-nos** [comment]
特に質問者さんから返答が無いので、クローズします。
