### ISSUE TITLE
P. 429 ページ末尾の rpn.cpp コードに重なる形で記載された `*1 RPN: Reverse Polish Notation` という注釈について

### ISSUE THREAD

**Issue by south37** [uchan-nos/os-from-zero#47]
## 観測した内容
P. 429 ページ末尾の rpn.cpp コード中で、`*1 RPN: Reverse Polish Notation` という注釈が以下のコードに重なる形で記載されているように見えます。

`v = v * 10 + (s[i] - '0');`

## 期待した内容
`*1 RPN: Reverse Polish Notation` が rpn.cpp のコードに重ならないことを期待しました。

**Comment by uchan-nos** [comment]
ご報告ありがとうございます。
既出なので閉じます。
https://github.com/uchan-nos/os-from-zero/blob/main/errata/first_1suri.md
