### ISSUE TITLE
P. 442 の図 19.2 と P.443 の図 19.3 における page directory のエントリの表記に `PDP[511]` が含まれる

### ISSUE THREAD

**Issue by south37** [uchan-nos/os-from-zero#48]
## 観測した内容
P. 442 の図 19.2 と P.443 の図 19.3 における page direcotry のエントリの表記が、一番上は `PD[0]` であるのに対して、一番下は `PDP[511]` と記載されているように見えます。

## 期待した内容
一番下のエントリは `PD[511]` と記載されることを期待しました（おそらく `PD` は page directory の頭文字であろう、という類推からの期待です）。

**Comment by uchan-nos** [comment]
ご報告ありがとうございます
