### ISSUE TITLE
サポートサイトの正誤情報のリンクについて

### ISSUE THREAD

**Issue by rkarsnk** [uchan-nos/os-from-zero#49]
サポートサイト( https://zero.osdev.jp ) では現在、初版２刷の正誤情報のみリンクしていますが、
初版１刷の正誤情報もリンクした方がいいのではと考えます。

初版１刷の人が正誤情報を見るためには、サポートサイトのリポジトリを開いて、errataディレクトリにアクセスするという手間がかかるので、リンク追加お願いします。

必要であればプルリク出します。

**Comment by uchan-nos** [comment]
第1刷の読者の方はずっと第1刷の正誤が必要なため、ご指摘の通りにリンクを復活させました。
