### ISSUE TITLE
【誤植】P.50 4行目について

### ISSUE THREAD

**Issue by yohane** [uchan-nos/os-from-zero#5]
> Main.c では #nclude でそれを取り込むだけでよくなったからです。

上記「#nclude」は「#include」かと思います。

**Comment by uchan-nos** [comment]
すみません。間違えてクローズしてしまいました。

**Comment by uchan-nos** [comment]
間違えてリオープンしてしまったのでクローズ。

**Comment by uchan-nos** [comment]
ご報告ありがとうございました。正誤情報へ記載させていただきました！
