### ISSUE TITLE
USBメモリからの起動ができないときに確認すべき事項について

### ISSUE THREAD

**Issue by nosochang** [uchan-nos/os-from-zero#54]
第1章p28～34あたり
BOOTX64.EFI をUSBメモリにコピーし、別のPCにさして起動したところ、
Remove disks or other media.
Press any key to resrart
と表示され、Enterキーを押すとそのPCのWindowsが起動します。

USBメモリからの起動になっていると思っているのですが、
これから何を確認したらよいのかが分かりません。

p30のようにBOOTX64.EFIのチェックサムを得るべくsumコマンドを実行したところ、
書籍の例では「12430     2」とありますが、手元では「12430     1」です。
検索してみるとこの2つ目の数字はブロック数とありましたが、これは違っていてよいのでしょうか？

p31のBIOSのセキュアブートは元々「DISABLED」となっていました。

USBメモリはSONYの64MBのもの（当初はexFAT、今はFAT32でフォーマット）
確認用PCは、2013年くらいのCore i3
開発環境は、Windows10・WSL2・Ubuntu 18.04 LTS・Binary Editor Bzです。

よろしくお願いします。

**Comment by rkarsnk** [comment]
@nosochang 
以下を確認してみて下さい。
- [ ] DVD-ROMドライブにディスクがはいっていないか
- [ ] SDカードなどが差さってないか
- [ ] BOOTX64.EFIはUSBメモリの`EFI/BOOT/`以下に置いてありますか
- [ ] BIOSの起動順序はUSBメモリが優先になっているか

チェックサムについては、`mikanos-build/osbook/day01/bin/hello.efi` と比較してみてください。

**Comment by nosochang** [comment]
ありがとうございます！
`mikanos-build/osbook/day01/bin/hello.efi` をダウンロード、リネームしてUSBにコピーするとHello Worldが表示できました。
（とてもくやしい）

以下4点はOKでした。
> * [ ]  DVD-ROMドライブにディスクがはいっていないか
> * [ ]  SDカードなどが差さってないか
> * [ ]  BOOTX64.EFIはUSBメモリの`EFI/BOOT/`以下に置いてありますか
> * [ ]  BIOSの起動順序はUSBメモリが優先になっているか

sumすると、やはりチェックサム12430は同じものの、その後の数字が違いました。
> チェックサムについては、`mikanos-build/osbook/day01/bin/hello.efi` と比較してみてください。

`noso@DESKTOP-7CM1CD0:~$ sum /mnt/c/Users/noso/Desktop/BOOTX64.EFI`
`12430     1`
`noso@DESKTOP-7CM1CD0:~$ sum /mnt/c/Users/noso/Desktop/hello.EFI`
`12430     2`

Binary Editor Bzでhello.EFIを開くと、私の入力したのよりだいぶ行が多いなあ…と。
ようやくp28の下から2行目「**1行すべてが0となる区間は「*」で省略しています。**」という記述に気が付きました。
（書籍に載っている行番号がどこか不思議だとは思っていたものの、バイナリエディタってそうなのかなと無邪気に考えていました…そんな訳なかった）

行数が全然足りてないのにチェックサムが合うのは釈然としませんが、原因は私の読み込み不足からの入力ミスという事で、この件は解決しました。お騒がせしました。

**Comment by uchan-nos** [comment]
@nosochang 
解決したようでなによりです。 @rkarsnk さん、素早いサポートをありがとうございました。

> 行数が全然足りてないのにチェックサムが合うのは釈然としませんが

良いところに気付きましたね。チェックサムは1バイト毎の和なので、0の区間をいくら足してもチェックサムに影響が無いのです。
