### ISSUE TITLE
初版(電子版ver 1.00) P.255のLayerクラスの関数名

### ISSUE THREAD

**Issue by Isa-rentacs** [uchan-nos/os-from-zero#55]
P.255のリスト10.16の後に
> `LayerManager::Draw()`は内部で`Layer::Draw()`に対して描画範囲を指定するようになったので、`Layer::Draw()`側を改造する必要があります。

とありますが、これらは`Layer::DrawTo()`を指しているように思います。

**Comment by uchan-nos** [comment]
ご報告ありがとうございます。
