### ISSUE TITLE
std::functionを使用すると停止する

### ISSUE THREAD

**Issue by CrabPunch** [uchan-nos/os-from-zero#57]
下記issueより分離
#44 

●現象
osbook_day06の
MouseDriver関連にて

usb::HIDMouseDriver::default_observer = MouseObserver;
にてプログラムが停止する問題。

static std::function<ObserverType> default_observer
とstaticのstd::functionへの代入時に止まっている。

std::function自体はstaticでないものであれば
代入しても止まらず、中身の呼び出し動作している。

●回避策
根本的な原因がわかっていないが
std::functionの使用箇所を関数ポインタにした場合は動作する

**Comment by mituha** [comment]
上記を関数ポインタで修正後、7.1(osbook_day07a)へ進んだのですが、マウス動作が行われなくなりました。  
interrupt.hpp の `extern std::array<InterruptDescriptor, 256> idt;` あたりが悪さしてそうな気もして配列に置き換えたら暴走？して再起動を繰り返す状態になってしまっています。  

何らかの環境依存とも思われますが何かわかることはありませんでしょうか？  

私の環境としては、  Windows10のWSL2上のUbuntu-20.04 上でkernelのコンパイルを行っています。  
動作環境として特殊な部分としては、QEMUはWSL2上ではなく、Windows10上で動作させています。

**Comment by CrabPunch** [comment]
@mituha 
私のほうの環境ですとWindow10 WSL2 Ubuntu-18.04LTSとなっています。

関数ポインタの修正方法でのやりかたですと
day07以降でもこちらだと動作自体はしています。

●挙動として怪しいところは
log出力をして動作を確認するかぎりqemuのwindow内にマウスカーソルがないと
portのログのところで停止する場合があります。

qemuが起動してすぐにwindowにマウスでフォーカスを移すと
windowが点灯してすすまなくなる現象はあります。

●
上記の挙動がそちらと同じかはわからないのですが
//extern std::array<InterruptDescriptor, 256> idt; あたりが悪さしてそうな気もして
というのはなにかログなりでそのあたりで意図しない挙動があったということでしょうか？

**Comment by mituha** [comment]
> 関数ポインタの修正方法でのやりかたですと
day07以降でもこちらだと動作自体はしています。  

動きますか… 
ということは原因が異なるかもですね。  

> log出力をして動作を確認するかぎりqemuのwindow内にマウスカーソルがないと
portのログのところで停止する場合があります。

portの列挙部分では特に止まってません。  

> 上記の挙動がそちらと同じかはわからないのですが
//extern std::array<InterruptDescriptor, 256> idt; あたりが悪さしてそうな気もして
というのはなにかログなりでそのあたりで意図しない挙動があったということでしょうか？

osbook_day06 時に、`std::function` の修正だけでは治らず、`std::array` も単純な配列への変更が必要だったためです。  

とりあえず、QEMU側の可能性も考慮して、WSL2上のQEMUでも試してみようと思っています。  
なお、Windows上でのQEMUは、`QEMU emulator version 5.2.0 (v5.2.0-11852-g66075e5998-dirty)` でした。

**Comment by uchan-nos** [comment]
@CrabPunch @mituha 
std::functionへの代入で止まるバージョン（day06相当）のリポジトリ一式をいただけませんか？
こちらで再現するか確認してみようと思います。

**Comment by CrabPunch** [comment]
@uchan-nos 
再現自体はosbook_day06cでも起こりはするので
こちらでコンパイル済みのelfなどをあげたほうがよかったりしますでしょうか？

**Comment by uchan-nos** [comment]
osbook_day06cそのままで発生するのですか？
コンパイル済みelfがあると嬉しいので、それらを含んだリポジトリ一式をzipで圧縮していただけると助かります。

**Comment by CrabPunch** [comment]
@uchan-nos 
再現が確認できた環境のosbook以下をzip圧縮いたしました。
[archive.zip](https://github.com/uchan-nos/os-from-zero/files/6414197/archive.zip)


内容的にはosbook_day06cをcheckoutしたのち
make後
動作確認のためにlogをdebugにして
xHC startingまでlogが流れるものとなっています。

**Comment by uchan-nos** [comment]
ありがとうございます。

いただいたkernel.elfを当方の環境のQEMUで動作させたところ、default_observerへの代入で止まることなく、マウス入力が出来ています。
念の為、いただいたMikanLoaderPkgをビルドしたブートローダといただいたkernel.elfの組み合わせも試して、上手く動くことを確認しました。

QEMUのバージョンは次の通りです。CrabPunchさんの環境と同じでしょうか？

```
$ qemu-system-x86_64 -version
QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.36)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
```

ノートパソコンで直接Ubuntu 18.04を動かしています。バージョンは次の通りです。

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
$ uname -a
Linux uchan-lifebook 5.4.0-62-generic #70~18.04.1-Ubuntu SMP Tue Jan 12 17:18:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

kernel.elfを起動するときのrun_qemu.shの出力を張ります。参考までに。

```
$ ~/osbook/devenv/run_qemu.sh ~/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi ./kernel.elf 
+ [ 2 -lt 1 ]
+ dirname /home/uchan/osbook/devenv/run_qemu.sh
+ DEVENV_DIR=/home/uchan/osbook/devenv
+ EFI_FILE=/home/uchan/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi
+ ANOTHER_FILE=./kernel.elf
+ DISK_IMG=./disk.img
+ MOUNT_POINT=./mnt
+ /home/uchan/osbook/devenv/make_image.sh ./disk.img ./mnt /home/uchan/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi ./kernel.elf
+ [ 4 -lt 3 ]
+ dirname /home/uchan/osbook/devenv/make_image.sh
+ DEVENV_DIR=/home/uchan/osbook/devenv
+ DISK_IMG=./disk.img
+ MOUNT_POINT=./mnt
+ EFI_FILE=/home/uchan/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi
+ ANOTHER_FILE=./kernel.elf
+ [ ! -f /home/uchan/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi ]
+ rm -f ./disk.img
+ qemu-img create -f raw ./disk.img 200M
Formatting './disk.img', fmt=raw size=209715200
+ mkfs.fat -n MIKAN OS -s 2 -f 2 -R 32 -F 32 ./disk.img
mkfs.fat 4.1 (2017-01-24)
+ /home/uchan/osbook/devenv/mount_image.sh ./disk.img ./mnt
+ [ 2 -lt 2 ]
+ dirname /home/uchan/osbook/devenv/mount_image.sh
+ DEVENV_DIR=/home/uchan/osbook/devenv
+ DISK_IMG=./disk.img
+ MOUNT_POINT=./mnt
+ [ ! -f ./disk.img ]
+ mkdir -p ./mnt
+ sudo mount -o loop ./disk.img ./mnt
+ sudo mkdir -p ./mnt/EFI/BOOT
+ sudo cp /home/uchan/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi ./mnt/EFI/BOOT/BOOTX64.EFI
+ [ ./kernel.elf !=  ]
+ sudo cp ./kernel.elf ./mnt/
+ sleep 0.5
+ sudo umount ./mnt
+ /home/uchan/osbook/devenv/run_image.sh ./disk.img
+ [ 1 -lt 1 ]
+ dirname /home/uchan/osbook/devenv/run_image.sh
+ DEVENV_DIR=/home/uchan/osbook/devenv
+ DISK_IMG=./disk.img
+ [ ! -f ./disk.img ]
+ qemu-system-x86_64 -m 1G -drive if=pflash,format=raw,readonly,file=/home/uchan/osbook/devenv/OVMF_CODE.fd -drive if=pflash,format=raw,file=/home/uchan/osbook/devenv/OVMF_VARS.fd -drive if=ide,index=0,media=disk,format=raw,file=./disk.img -device nec-usb-xhci,id=xhci -device usb-mouse -device usb-kbd -monitor stdio
QEMU 2.11.1 monitor - type 'help' for more information
(qemu) qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
```

**Comment by mituha** [comment]
私の方は、上記、`archive\osbook\devenv\mikanos\kernel\kernel.elf`  で確認したところ、やはり、`xHC starting` までで止まります。  

確認した環境としては、WSL2上の、Ubuntu-20.04 での
```
QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.15)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers

mituha@DESKTOP-MJ9PM7D:~$ ./osbook/devenv/run_image.sh ./img/disk.img
+ [ 1 -lt 1 ]
+ dirname ./osbook/devenv/run_image.sh
+ DEVENV_DIR=./osbook/devenv
+ DISK_IMG=./img/disk.img
+ [ ! -f ./img/disk.img ]
+ qemu-system-x86_64 -m 1G -drive if=pflash,format=raw,readonly,file=./osbook/devenv/OVMF_CODE.fd -drive if=pflash,format=raw,file=./osbook/devenv/OVMF_VARS.fd -drive if=ide,index=0,media=disk,format=raw,file=./img/disk.img -device nec-usb-xhci,id=xhci -device usb-mouse -device usb-kbd -monitor stdio
qemu-system-x86_64: warning: dbind: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
QEMU 4.2.1 monitor - type 'help' for more information
```
および、Windows10上の、
```
QEMU emulator version 5.2.0 (v5.2.0-11852-g66075e5998-dirty)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers

QEMU emulator version 2.11.0 (v2.11.0-11693-g21057c841e-dirty)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

cd "C:\Program Files\qemu\"
qemu-system-x86_64.exe -m 1G -drive if=pflash,format=raw,file="D:\home\mituha\repos\GeNJA\img\OVMF_CODE.fd" -drive if=pflash,format=raw,file="D:\home\mituha\repos\GeNJA\img\OVMF_VARS.fd" -hda "D:\home\mituha\repos\GeNJA\img\disk.img" -device nec-usb-xhci,id=xhci -device usb-mouse -device usb-kbd
```
となります。  
Windows上のQEMUのバージョンを下げてみたけど症状変わりませんでした。

**Comment by CrabPunch** [comment]
@uchan-nos  @mituha 
確認ありがとうございます。
こちらの環境ですと

`
 qemu-system-x86_64 -version
QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.36)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
`

`
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

~$ uname -a
Linux DESKTOP-NGVIT1B 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`

`
+ [ 2 -lt 1 ]
+ dirname /home/danan/osbook/devenv/run_qemu.sh
+ DEVENV_DIR=/home/danan/osbook/devenv
+ EFI_FILE=Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi
+ ANOTHER_FILE=/home/danan/osbook/devenv/mikanos/kernel/kernel.elf
+ DISK_IMG=./disk.img
+ MOUNT_POINT=./mnt
+ /home/danan/osbook/devenv/make_image.sh ./disk.img ./mnt Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi /home/danan/osbook/devenv/mikanos/kernel/kernel.elf
+ [ 4 -lt 3 ]
+ dirname /home/danan/osbook/devenv/make_image.sh
+ DEVENV_DIR=/home/danan/osbook/devenv
+ DISK_IMG=./disk.img
+ MOUNT_POINT=./mnt
+ EFI_FILE=Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi
+ ANOTHER_FILE=/home/danan/osbook/devenv/mikanos/kernel/kernel.elf
+ [ ! -f Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi ]
+ rm -f ./disk.img
+ qemu-img create -f raw ./disk.img 200M
Formatting './disk.img', fmt=raw size=209715200
+ mkfs.fat -n MIKAN OS -s 2 -f 2 -R 32 -F 32 ./disk.img
mkfs.fat 4.1 (2017-01-24)
+ /home/danan/osbook/devenv/mount_image.sh ./disk.img ./mnt
+ [ 2 -lt 2 ]
+ dirname /home/danan/osbook/devenv/mount_image.sh
+ DEVENV_DIR=/home/danan/osbook/devenv
+ DISK_IMG=./disk.img
+ MOUNT_POINT=./mnt
+ [ ! -f ./disk.img ]
+ mkdir -p ./mnt
+ sudo mount -o loop ./disk.img ./mnt
+ sudo mkdir -p ./mnt/EFI/BOOT
+ sudo cp Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi ./mnt/EFI/BOOT/BOOTX64.EFI
+ [ /home/danan/osbook/devenv/mikanos/kernel/kernel.elf !=  ]
+ sudo cp /home/danan/osbook/devenv/mikanos/kernel/kernel.elf ./mnt/
+ sleep 0.5
+ sudo umount ./mnt
+ /home/danan/osbook/devenv/run_image.sh ./disk.img
+ [ 1 -lt 1 ]
+ dirname /home/danan/osbook/devenv/run_image.sh
+ DEVENV_DIR=/home/danan/osbook/devenv
+ DISK_IMG=./disk.img
+ [ ! -f ./disk.img ]
+ qemu-system-x86_64 -m 512 -drive if=pflash,format=raw,readonly,file=/home/danan/osbook/devenv/OVMF_CODE.fd -drive if=pflash,format=raw,file=/home/danan/osbook/devenv/OVMF_VARS.fd -drive if=ide,index=0,media=disk,format=raw,file=./disk.img -device nec-usb-xhci,id=xhci -device usb-mouse -device usb-kbd -monitor stdio
QEMU 2.11.1 monitor - type 'help' for more information
(qemu) qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
`
となります。

uchan-nosさんとの違いだと
5.4.0-62-generic 
5.4.72-microsoft-standard-WSL2の違いあたりでしょうか

qemu-system-x86_64 -m 512 の -m512に関しては
当初は1Gだったのですが
TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
が気になっていたのできえないかとサイズまわりを調整していたなごりです。
（マウスが動かなかったtおきのためのものなので1Gでも同様の結果です）

こちらで作成済のelfで発生しないとなると
clangなりビルド環境の問題ではなく実行まわりの環境のなにかということでしょうかね、、

**Comment by uchan-nos** [comment]
default_observer に代入すると止まる、直接的な原因を特定してみたいと思います。

そのために、代入直前の default_observer の値を確認させてください。
代入は、いただいた kernel.elf のアドレス 0x1035b3（call   103700）で行われているようですので、GDB を使ってブレークし、default_observer のメモリ領域（0x135f80 から 48 バイト）を観察してください。

GDB での観察の方法は、まず次の内容のファイル（名前は何でも良いですが、ここでは「gdbinit」としました）を作ります。

```
$ cat gdbinit
set disassembly-flavor intel
target remote localhost:1234
file kernel.elf

b *0x1035b3
c
x /6gx 0x135f80
```

次に、別のターミナルで QEMU を起動させます。このときに QEMU に `-s` を指定します。これで GDB から接続ができるようになります。

```
$ QEMU_OPTS="-s" ~/osbook/devenv/run_qemu.sh ~/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi ./kernel.elf
```

TianoCore のロゴが見えたあたりで GDB を起動させます。

```
$ gdb -x gdbinit
```

gdbinit のスクリプトにより、自動的にブレークし、メモリ領域の値が表示されます。私の環境では次のような出力になりました。

```
$ gdb -x gdbinit
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
《中略》
Breakpoint 1 at 0x1035b3: file /home/danan/osbook/devenv/x86_64-elf/include/c++/v1/functional, line 2329.

Breakpoint 1, 0x00000000001035b3 in std::__1::function<void (signed char, signed char)>::operator=<void (&)(signed char, signed char), void>(void (&)(signed char, signed char)) (
    this=0x135f80 <usb::HIDMouseDriver::default_observer>, __f=<optimized out>)
    at /home/danan/osbook/devenv/x86_64-elf/include/c++/v1/functional:2329
2329	/home/danan/osbook/devenv/x86_64-elf/include/c++/v1/functional: そのようなファイルやディレクトリはありません.
0x135f80 <_ZN3usb14HIDMouseDriver16default_observerE>:	0x0000000000000000	0x0000000000000000
0x135f90 <_ZN3usb14HIDMouseDriver16default_observerE+16>:	0x0000000000000000	0x0000000000000000
0x135fa0 <_ZN3usb14HIDMouseDriver16default_observerE+32>:	0x0000000000000000	0x0000000000000000
```

0x135f80 から 8 バイトの領域はすべて 0 ということが分かりました。CrabPunch さん、mituha さんの場合はどんな数値になるでしょうか。

**Comment by CrabPunch** [comment]
@uchan-nos 
出力形式が上記のものとちがうので
なにかlog的にxml用の出力のものがいるのでしょうか

こちらだとこのような結果となりました。

```
 gdb -x gdbinit
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
warning: Can not parse XML target description; XML support was disabled at compile time
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
gdbinit:2: Error in sourced command file:
Remote 'g' packet reply is too long (expected 312 bytes, got 536 bytes): e0b3b71f00000000de9fb71f00000000e0b3b71f00000000f803ea1f000000000000000000000000c6351000000000002087ea1f000000000083ea1f0000000001000000000000000000000000000000000000000000000000000000000000009881301f0000000078040000000000009c84b61f000000000d000000000000001630b71f000000004600000038000000300000003000000030000000300000003000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007f0300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000801f0000
(gdb)
```

**Comment by uchan-nos** [comment]
> なにかlog的にxml用の出力のものがいるのでしょうか

いえ、そんなことはないです。おそらく GDB と QEMU の接続が上手くいっていないです。
バージョン表示が「GNU gdb (GDB) 8.0.1」となっていて、私の GDB とかなり違いますね。
どうやってインストールした GDB を使っていますか？APT で入れてますか？

APT の GDB を使ったり、QEMU のオプションを見直したり、GDB を起動させるタイミングを調整したりして、なんとか私の出力のようになるまで挑戦してみてください。

**Comment by CrabPunch** [comment]
gdb自体はいれていなかったのでremoveしたとしても存在しなかったため、
下記の手順でinstallをしました。
https://qiita.com/t-tkd3a/items/71aeb4b6d87ae82f0389

//APT の GDB を使ったり、QEMU のオプションを見直したり、GDB を起動させるタイミングを調整したりして、なんとか私の出力のようになるまで挑戦してみてください。

承知しました
まずgdbまわりの環境の整備をすすめてみます。

**Comment by mituha** [comment]
WSL2(Ubuntu)上でのQEMUとgdbの結果です。  

```
mituha@DESKTOP-MJ9PM7D:~$ gdb -x ./kernel/gdbinit
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.

(中略)

0x000000003ea3bd2b in ?? ()
Breakpoint 1 at 0x1035b3: file /home/danan/osbook/devenv/x86_64-elf/include/c++/v1/functional, line 2329.

Breakpoint 1, 0x00000000001035b3 in std::__1::function<void (signed char, signed char)>::operator=<void (&)(signed char, signed char), void>(void (&)(signed char, signed char)) (this=0x135f80 <usb::HIDMouseDriver::default_observer>,
    __f=<optimized out>) at /home/danan/osbook/devenv/x86_64-elf/include/c++/v1/functional:2329
2329    /home/danan/osbook/devenv/x86_64-elf/include/c++/v1/functional: No such file or directory.
0x135f80 <_ZN3usb14HIDMouseDriver16default_observerE>:  0xf70000000000106e      0x040000000000106e
0x135f90 <_ZN3usb14HIDMouseDriver16default_observerE+16>:       0x106ef79f1aa07300      0x106ef70000000000
0x135fa0 <_ZN3usb14HIDMouseDriver16default_observerE+32>:       0x7300040000000000      0x0000106ef79f1ab8
```
こっちの環境では０にはなっていないようです。  
これは、staticな変数のため本来は0(null)が正しいと考えればよいのでしょうか。

**Comment by CrabPunch** [comment]
gdbでのbreak動きました

```
determining executable automatically.  Try using the "file" command.
0x000000000000fff0 in ?? ()
Breakpoint 1 at 0x1035b3: file /home/danan/osbook/devenv/x86_64-elf/include/c++/v1/functional, line 2329.

Breakpoint 1, 0x00000000001035b3 in std::__1::function<void (signed char, signed char)>::operator=<void (&)(signed char, signed char), void>(void (&)(signed char, signed char)) (this=0x135f80 <usb::HIDMouseDriver::default_observer>,
    __f=<optimized out>) at /home/danan/osbook/devenv/x86_64-elf/include/c++/v1/functional:2329
2329        function(_VSTD::forward<_Fp>(__f)).swap(*this);
0x135f80 <_ZN3usb14HIDMouseDriver16default_observerE>:  0xf70000000000106e      0x040000000000106e
0x135f90 <_ZN3usb14HIDMouseDriver16default_observerE+16>:       0x106ef79f1aa07300      0x106ef70000000000
0x135fa0 <_ZN3usb14HIDMouseDriver16default_observerE+32>:       0x7300040000000000      0x0000106ef79f1ab8
```

**Comment by uchan-nos** [comment]
ありがとうございます。

> staticな変数のため本来は0(null)が正しいと考えればよいのでしょうか。

基本的にはそういうことになります。（基本的、というのは、デフォルトコンストラクタによって 0 でない値で初期化される静的変数もあるからです）

osbook_day04d で、静的変数を 0 クリアするようにブートローダを変更しているのですが、ブートローダをビルドし直しましたか？

**Comment by CrabPunch** [comment]
@uchan-nos 
失礼いたしました、たしかにブートローダーのビルドが抜けておりました。
ブートローダービルド後

```
determining executable automatically.  Try using the "file" command.
0x000000000000fff0 in ?? ()
Breakpoint 1 at 0x1035b3: file /home/danan/osbook/devenv/x86_64-elf/include/c++/v1/functional, line 2329.

Breakpoint 1, 0x00000000001035b3 in std::__1::function<void (signed char, signed char)>::operator=<void (&)(signed char, signed char), void>(void (&)(signed char, signed char)) (this=0x135f80 <usb::HIDMouseDriver::default_observer>,
    __f=<optimized out>) at /home/danan/osbook/devenv/x86_64-elf/include/c++/v1/functional:2329
2329        function(_VSTD::forward<_Fp>(__f)).swap(*this);
0x135f80 <_ZN3usb14HIDMouseDriver16default_observerE>:  0x0000000000000000      0x0000000000000000
0x135f90 <_ZN3usb14HIDMouseDriver16default_observerE+16>:       0x0000000000000000      0x0000000000000000
0x135fa0 <_ZN3usb14HIDMouseDriver16default_observerE+32>:       0x0000000000000000      0x0000000000000000

```
と０クリアが確認されました。

また
std::functionが使用されている箇所も正常動作していることが確認できました。
ありがとうございます

**Comment by mituha** [comment]
こちらもブートローダーをリビルド後、同様に動きました。  
上記 kernel.elf でのマウス動作と、gdbでの0クリアを確認しました。

* ローダー部のソースは osbook_day04d 相当だった
    + ブートローダー自体がこの時点のビルドかは不明
    + 下記エラーの発生を見逃してビルド完了のつもりだった可能性もある。
* リビルド時、RegisterFilterLib のエラー
    + edk2のバージョンによるもの
    + https://twitter.com/uchan_nos/status/1380457288578727945
* mikanos-build を最新版に更新
    + 開発ツール更新
* リビルドしたブートローダーでの上記 kernel.elf での動作を確認

自分の環境での動作も順次確認していきたいと思います。  
ありがとうごさいました。

**Comment by CrabPunch** [comment]
@mituha さんのほうの環境でも問題なさそうだったら
こちら閉じようかと思います

**Comment by mituha** [comment]
@CrabPunch 自分の環境で問題ないことを確認しました。  
閉じて問題ないと思います。  

しかし、こんな原因に良く二人も嵌って同症状が出たものです。  
一人だとまだ解決に至っていない気がします。
@uchan-nos @CrabPunch  ありがとうごさいました。

**Comment by CrabPunch** [comment]
@mituha 
報告ありがとうございます

同じく一人だと解決にいたらず
回避策で無理やり進んでまたはまっていたかもしれません。

補足としてGDBがうまく動かなかった件の対応は
・expat追加　https://blog.techlab-xe.net/%E3%82%AF%E3%83%AD%E3%82%B9%E5%90%91%E3%81%91%E3%81%AEgdb%E3%82%92%E7%94%A8%E6%84%8F%E3%81%99%E3%82%8B/
・gdbinitをkernelにおいた

・remoteのport指定をqemu-systemに追加した
の３点です、同時にやってしまったので全部必要かどれか１つでよかったかまでは絞ってはいません。

なにはともあれ
@uchan-nos 
@mituha 
ありがとうございました。
