### ISSUE TITLE
terminal.cpp の sizeof のコード

### ISSUE THREAD

**Issue by alpha-netzilla** [uchan-nos/os-from-zero#59]
リスト20.7のterminal.cpp内で以下のコードを拝見いたしました。
```
auto argbuf = reinterpret_cast<char*>(args_frame_addr.value + sizeof(char**) * argv_len);
int argbuf_len = 4096 - sizeof(char**) * argv_len;
```
sizeof(char **)の箇所ですが、sizeof(char *)ではないでしょうか？

**Comment by uchan-nos** [comment]
その通りですね。

ただ、どちらも「ポインタに対するsizeof」で結果は等しくなるので、重要なバグとはみなさず、
https://github.com/uchan-nos/os-from-zero/blob/main/mikanos-bugs.md には追記しません。
あしからず。

**Comment by uchan-nos** [comment]
@alpha-netzilla 
最新版にもこのバグは残っているので、mikanos リポジトリの方にプルリクをいただけたら取り込みます。
