### ISSUE TITLE
undefined referencce to 'gEfiLoadedImageProtocolGuid' がでてビルドに失敗するようになった

### ISSUE THREAD

**Issue by ndifix** [uchan-nos/os-from-zero#6]
mikanosのコードを参考にしながら全てのファイルを自分で書いています。
day2 のメモリマップをファイルに保存するところまで書くとEDK II のbuild でエラーが出たので共有します。
`in function 'OpenRootDir': path/to/Main.c: undefined referencce to 'gEfiLoadedImageProtocolGuid'`
が出ましたが `Loader.inf` の [Protocols] に `gEfiLoadedImageProtocolGuid` を追記することで解消されました。

mikanosのコードではここが追加されていますが、本で言及がないので注意が必要かもしれません。

**Comment by uchan-nos** [comment]
ご報告ありがとうございます＆本書を読んでいただき、そして実験までしていただき、ありがとうございます。

本書全体を通して、完全な差分を紙面に載せているわけではありません。
したがって、この件について本文で言及はしないままにさせていただきます。
