### ISSUE TITLE
【質問】コラム2.2 ポインタのポインタ において、`memmap_file` の向き先のメモリ領域はどこに確保される？

### ISSUE THREAD

**Issue by magurotuna** [uchan-nos/os-from-zero#62]
https://github.com/uchan-nos/mikanos/blob/d4048a3a0eda64c6c533bcdba0e2f494d17c3b06/MikanLoaderPkg/Main.c#L289-L292

上記部分のコードに関して コラム2.2 で詳しく説明がされているかと思います。
以下のように解釈をしたのですが、自分の解釈は正しいでしょうか？

- `root_dir->Open()` の中では、`memmap_file` が示すアドレス自体が書き換えられる。つまり、図2.8でいうところの `0xd800` というアドレスが書き換わる。
- `memmap_file` の新しい向き先のメモリ領域は、`root_dir->Open()` の中で確保される。このとき確保される場所はヒープ領域である（OSが無い世界でヒープ領域という概念は存在する？？）
- ヒープ領域に確保されたら、使い終わったら解放する必要がある。その解放を行う責任は `root_dir->Open()` を呼び出した側にあり、プログラマが責任をもって明示的に処理しなければならない
- 解放処理を行っているのが https://github.com/uchan-nos/mikanos/blob/d4048a3a0eda64c6c533bcdba0e2f494d17c3b06/MikanLoaderPkg/Main.c#L302 の行である

OSがない世界でもヒープ領域という概念を念頭に置いても良いのか、というのが特に気になっています。
よろしくお願いします。

**Comment by uchan-nos** [comment]
かね正しいと思います。

OS が無くても、UEFI BIOS はあるので、UEFI BIOS が管理するメモリ領域から確保されます。

**Comment by magurotuna** [comment]
ありがとうございます。腑に落ちました :smiley:
