### ISSUE TITLE
【誤植】P.586 リスト25.3のキャプション

### ISSUE THREAD

**Issue by komori-n** [uchan-nos/os-from-zero#64]
（初版第1刷です）

> リスト25.3 NextPathElement()はパスを/で区切った最初の要素を取得する（terminal.cpp）

些細な指摘で大変恐縮ですが、タグ osbook_day25a では
`NextPathElement()`はterminal.cppではなくfat.cppにて定義されています。

**Comment by uchan-nos** [comment]
報告ありがとうございます。
