### ISSUE TITLE
誤字報告 p54 4億->40億

### ISSUE THREAD

**Issue by fukuseki** [uchan-nos/os-from-zero#66]
誤字報告です。以下の4億は、2の32乗なら40億が正しいのではないでしょうか。

初版第1刷 p54
実の世界との違いは、番地の範囲がとても大きい（32 ビット CPU では 0 から **4 億**程度まである）ことでしょうか

**Comment by uchan-nos** [comment]
ご報告ありがとうございます。その通りです。
