### ISSUE TITLE
【誤植】49ページの付録の表記ミス

### ISSUE THREAD

**Issue by Sorakime** [uchan-nos/os-from-zero#7]
こんにちは。
49ページにて表記ミスらしきものがありましたからここにて指摘させていただきます。
49ページの中央あたりの「説明は『付録A EDK IIファイル説明』」の「付録A」のところが間違っていると思います。
付録Aを見に行きましたが、「開発環境のインストール」となっており、EDK IIのページではなかったです。正しくは「付録C
EDK IIのファイル説明」とするべきだと思うます。

**Comment by uchan-nos** [comment]
ご報告ありがとうございました。正誤情報へ記載させていただきました！
