### ISSUE TITLE
[質問] osbook_day07a の割込みのデバッグについて

### ISSUE THREAD

**Issue by rkarsnk** [uchan-nos/os-from-zero#73]
`osbook_day07a` でIDTと割込みハンドラを実装し、割込み検知によるマウスカーソルの動作を行なおうとしていますが、割込みを検知できておらず、正常に動作しません。

gdbで`IntHandlerXHCI()`にブレークポイントを設定しても、ブレークせず。
デバッグの方針としては、どこから手をつければいいでしょうか？

以下のスクリーンショットでは、Log()出力を複数追加して、割込みに関する情報を出力しています。

![qemu_saintos07a](https://user-images.githubusercontent.com/26945036/119788119-d476cb80-bf0c-11eb-8151-aa0d4cab9e5c.png)

https://github.com/rkarsnk/SaintOS/blob/2276d88bccd07881bd2fb90be1f6e401166e13fc/src/kernel/xhc.cpp#L1-L10

**Comment by uchan-nos** [comment]
> デバッグの方針としては、どこから手をつければいいでしょうか？

私なら、まず絶対に発生するはずの割り込みを起こしてみて、割り込みハンドラが起動するかを見ますね。
例えば UD 命令というものがあって、これは UD 例外を起こすための命令なので、絶対に UD 例外が発生します。
UD 例外のハンドラ内で何らかの表示をしてフリーズするようにしておけば、検知が可能です。

これでハンドラが起動しない（おそらく、トリプルフォルトで PC が強制再起動するでしょう）なら、
IDT などの記述ミスや、IDT の先頭アドレスが IDTR に設定できてない、というようなミスが考えられます。

**Comment by rkarsnk** [comment]
IDTの設定までは正常にできていたので、MSIの設定が誤っているのではと思い、Log()関数を埋めこみながらソースコードと動作を追いかけたところ、以下のコードに誤りを発見しました。

```
    msi_cap.msg_addr = msg_addr;
    msi_cap.msg_data = msg_addr;   <--- 代入する変数が違う
```
https://github.com/rkarsnk/SaintOS/blob/2276d88bccd07881bd2fb90be1f6e401166e13fc/src/kernel/pci.cpp#L132-L159

正しく修正したところ、正常に割込みハンドラが動作するようになりました。
ご協力ありがとうございます。

解決したので、クローズします。

**Comment by uchan-nos** [comment]
おめでとうございます！
