### ISSUE TITLE
「質問」p.50のコマンド `ln -s $HOME/workspace/mikanos/MikanLoaderPkg ./` がエラーになってしまう

### ISSUE THREAD

**Issue by kankan822** [uchan-nos/os-from-zero#74]
Ubuntu20.04.2LTS

$ git checkout osbook_day02aを実行しても、$HOME/workspace/mikanos以下にday02aの
ソースコードが配置されていないようなのですが、これはどのように解決したらよいのでしょうか…解決策が見つけれず質問させてもらいました。よろしくお願いいたします。

![2021-05-29_03-23](https://user-images.githubusercontent.com/84988850/120027329-2fecaa80-c02e-11eb-8c65-5839f5b1c94b.png)

**Comment by uchan-nos** [comment]
ln コマンドのエラーの直接的な原因は、すでに MikanLoaderPkg というファイルがあるのにも関わらず、
MikanLoaderPkg という名前でシンボリックリンクを作成しようとしているからです。

「$HOME/workspace/mikanos 以下に MikanLoaderPkg が無いこと」が原因ではなく、
「$HOME/edk2 に MikanLoaderPkg があること」がエラーの原因です。

$HOME/edk2 で ls コマンドを実行してみると MikanLoaderPkg というファイルがあることが分かると思います。

さて、

> $ git checkout osbook_day02aを実行しても、$HOME/workspace/mikanos以下にday02aのソースコードが配置されていないよう

これはどのように確認したのでしょうか？

**Comment by kankan822** [comment]
右のGUIで、このディレクトリの中にosbook_day02aなるものができると思っていたので、配置されたいないと思ってしまったのですが、そういう認識ではないようですね。初歩的なことで大変申し訳ありません。。。
![2021-05-29_03-23](https://user-images.githubusercontent.com/84988850/120073097-de95f700-c0d1-11eb-9033-709516b995eb.png)

$HOME/workspace/mikanos以下にMain.c等ファイルが配置されるという認識と捉えれば良いのかと思っています。それによりday02aのソースコードは配置されているようなのですが、進めていくとbuildできるファイル/ディレクトリがないようなのですが。
これも何か自分は勘違いしているのでしょうか。
初歩的な内容等で大変申し訳ありませんが教えて頂きたくお願いします。

**Comment by uchan-nos** [comment]
右側の GUI に表示されているファイル構成で正しいです。
osbook_day02a のファイル構成はもともと https://github.com/uchan-nos/mikanos/tree/osbook_day02a こうなっています。

$HOME/edk2 で ls した結果、「MikanLoaderPkg」が赤色になっているのが原因と思います。
ls -l してみるともっと詳しく分かると思いますが、おそらく、MikanLoaderPkg が存在しないパスを指してしまっているのでしょう。

`ln -s $HOME/workspace/mikanos/MikanLoaderPkg ./` を実行する際に `-f` オプションを加えてみてください。
つまり `ln -f -s $HOME/...` とするわけです。

`-f` は force オプションといって、同じ名前で既存のファイルがあっても、無視して上書きします。

再度 ls したときに MikanLoaderPkg が緑色の表示になれば OK です。

**Comment by uchan-nos** [comment]
後から質問を探す人が分かりやすいようにタイトルを変更させていただきました。

**Comment by kankan822** [comment]
出来ました！！
教えて頂いた通りに試してみると、目的のファイルが出力できていました。
完璧に理解出来ていない部分も多々ありますが、じっくり本とわからない用語等と調べて読み進んでいきたいと思います。
教えていただ本当にありがとうございました。
![2021-05-29_03-23](https://user-images.githubusercontent.com/84988850/120074582-7eef1a00-c0d8-11eb-845e-da5b94625397.png)
