### ISSUE TITLE
Hello World表示での工程で詰まりました。

### ISSUE THREAD

**Issue by ShinichiroIsshiki** [uchan-nos/os-from-zero#75]
![スクリーンショット (58)](https://user-images.githubusercontent.com/59560071/120432358-ca454900-c3b4-11eb-9afd-29a9b47adfe7.png)
私の環境がWindowsPCのため、WSLで書籍の34ページのコマンドを実行した際、ファイルが見つからないというエラーがでました。解決法をご教授願います。

**Comment by ShigeakiAsai** [comment]
#16 と同じではないかと思います。

**Comment by uchan-nos** [comment]
@ShinichiroIsshiki その後解決しましたでしょうか？

**Comment by uchan-nos** [comment]
特に反応がありませんので閉じますが、まだ追加で質問したい場合はリオープンしていただいて構いません。
