### ISSUE TITLE
付録A開発環境のインストールで開発ツールのインストールができない。

### ISSUE THREAD

**Issue by supermappin** [uchan-nos/os-from-zero#76]
使用環境：MacOSX(big sur)上のVirtual Box上で、Ubuntuのコマンドラインを使用。

以下ご質問です。

・P716 付録A 開発環境のインストールに関して、開発環境を整える方法の記載がある以下のURLにおいて
https://github.com/uchan-nos/mikanos-build

「開発ツールの導入」の項目で以下のコマンドの記載があるのですが
$ sudo apt install ansible
$ cd $HOME/osbook/devenv
$ ansible-playbook -K -i ansible_inventory ansible_provision.yml

$ sudo apt install ansible　のコマンドを入力すると、
ansibleというソフトウェアは問題なくインストールされたものの

次の
$ cd $HOME/osbook/devenv　のコマンドを入力すると
「そのようなファイルやディレクトリはありません」
と表示されてしまいました。

その状態のまま、
$ ansible-playbook -K -i ansible_inventory ansible_provision.yml
のコマンドを入力すると
「ERROR! the playbook: ansible_provision.yml could not be found」
と表示されてしまいます。

「開発ツールの導入」の項目の前に行う
「リポジトリのダウンロード」の項目に記載されてる
以下のコマンドは、正常に行われたと思います。
$ sudo apt update
$ sudo apt install git
$ cd $HOME
$ git clone https://github.com/uchan-nos/mikanos-build.git osbook

至らない点がわからず、何卒ご教授のほうよろしくお願いいたします。

**Comment by supermappin** [comment]
進捗ありました。

osbook/devenv　のファイルを見つけることができました。
cdコマンドでこのファイルの場所に移動した後で

$ ansible-playbook -K -i ansible_inventory ansible_provision.yml
上記のコマンドをしたところ以下の画面のような結果が表示されました。

![スクリーンショット 2021-06-05 3 04 00](https://user-images.githubusercontent.com/26266421/120845477-d9421c00-c5ab-11eb-8d5b-0967a9166e98.png)

この後に、セットアップが上手くいけば iasl というコマンドがインストールされ，$HOME/edk2 というディレクトリが生成されているはずなのですが

iaslのコマンドは実行できず、cdコマンドでHOMEに移動した後にlsコマンドを使ってもedk2というファイルを確認することができません。

なぜセットアップが失敗しているのかわからず、至らない点をご教授いただければ誠に幸いです。

**Comment by uchan-nos** [comment]
ansible-playbook コマンドの実行中にエラーが出ている（sudo パスワード関連）のが上手くいっていない原因だと思います。
このエラーがなぜ表示されるのか分かりません。もしかしたら入力したパスワードが間違っていたりするかもしれません。

**Comment by takotakot** [comment]
@supermappin  inventory と inbentory のタイプミスでしょう。画像を貼り付けたことが良かったですね。

**Comment by supermappin** [comment]
大文字と小文字で違うのですね。勉強になります。
問題としては、ご指摘いただいたコードを修正し、必要だったのかどうかわかりませんが、githubのSSHの暗号鍵を設定したらうまくいきました。

ありがとうございました！

**Comment by uchan-nos** [comment]
解決したようなのでクローズします。
