### ISSUE TITLE
『ゼロからのOS自作入門』P44のコードが実行されない。

### ISSUE THREAD

**Issue by supermappin** [uchan-nos/os-from-zero#77]
『ゼロからのOS自作入門』P44に

$ $HOME/osbook/devenv/run_qemu.sh hello.efi

のコードの記載があり、入力を試みたのですが実行されません。
以下画像のように思いつく限りの入力を試したのですがうまくいかず
コマンドラインの仕様に関して、私は何か根本的な思い違いをしているような気がしております。
至らない点、ご指摘いただけますと誠に幸いです。よろしくお願いいたします。
![スクリーンショット_2021-06-06_1_13_33](https://user-images.githubusercontent.com/26266421/120898469-f89d7f80-c665-11eb-8329-3390ce363f19.png)

**Comment by takotakot** [comment]
`$` は変数開始を示します。本来は `$HOME` までで、ユーザのホームディレクトリ、つまり、`/home/maroty` であることを示します。
大文字・小文字は区別されます。

以下の2行は同一の意味です。

```
$HOME/osbook
/home/maroty/osbook
```

何も設定しない限り、`$maroty` や `$run_quemu` という変数は空です。

行頭の `$` は不要です。

再度見直してみてください。

**Comment by supermappin** [comment]
＞＞takotakot

$HOMEの変数部分を/home/maroty/に変更して実行したところ、問題解決されました。
ありがとうございました。

**Comment by supermappin** [comment]
>>takotakot

ご回答ありがとうございます。$HOMEの変数部分を/home/maroty/に変更して記述するとファイルの実行することができました。

**Comment by uchan-nos** [comment]
解決したようなのでクローズします
