### ISSUE TITLE
『ゼロからのOS自作入門』P44のコード実行において、hello.efiが見つからない。

### ISSUE THREAD

**Issue by supermappin** [uchan-nos/os-from-zero#78]
『ゼロからのOS自作入門』P44に記載の
以下のコードを実行すると添付画像の表示がされ、QEMUが立ち上がりません。

hello.efiのファイルが見つからないことが問題だと思うのですが、
開発ツールの導入は完了できています。

何卒ご教授いただけますと幸いです。

$ $HOME/osbook/devenv/run_qemu.sh hello.efi

![スクリーンショット 2021-06-06 22 17 12](https://user-images.githubusercontent.com/26266421/120925894-a451d880-c715-11eb-8e87-07809f2749f5.png)

**Comment by uchan-nos** [comment]
おっしゃる通り hello.efi が無いことが原因ですね。

カレントディレクトリ（pwd コマンドで表示されるディレクトリ）に hello.efi ファイルを準備してください。
p.43 の手順の中の lld-link コマンドにより、カレントディレクトリに hello.efi が出力されることを期待しています。
（lld-link コマンドのオプション `/out:hello.efi` により、hello.efi ファイルができるはずなのです）

あるいは、hello.efi ファイルがある場所までのパス（path）を指定してください。
/path/to/hello.efi にあるのなら
`/home/maroty/osbook/devenv/run_qemu.sh /path/to/hello.efi` というように。

**Comment by supermappin** [comment]
ご回答ありがとうございます。

p.43 の手順を実行した後に、再度コマンドを入力したところQEMU立ち上がってHello World表示されました。表示されると苦労報われた感じで感動しました。

![スクリーンショット 2021-06-06 23 24 55](https://user-images.githubusercontent.com/26266421/120928605-3eb71980-c720-11eb-9c24-fc920dc0bb8f.png)

**Comment by takotakot** [comment]
@supermappin 解決したら close しましょう。
