### ISSUE TITLE
C言語での2進数表記の可否

### ISSUE THREAD

**Issue by onein528** [uchan-nos/os-from-zero#80]
C言語での、2進数表記は可能です。

![image](https://user-images.githubusercontent.com/62196528/121668165-fdd75000-cae5-11eb-8481-92ae9ede651e.png)

`0b`又は、`0B`接頭辞をリテラルの先頭に追加することで二進数を表記できます。ですが整数リテラルのみです。その場合で不可としたのならば、このissueは削除していただいて構いません。

`0b10`は、10進数で2となります。

勘違いだと思います。C言語が浅い方が筆者なのでしょうか。

[このサイトを見ると分かります。](https://cpprefjp.github.io/lang/cpp14/binary_literals.html)

**Comment by onein528** [comment]
間違えました。本当にすみません。

**Comment by takotakot** [comment]
折角なので: https://yohhoy.hatenadiary.jp/entry/20210228/p1
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2549.pdf

**Comment by onein528** [comment]
知っています。ほかのOSの本を見ていました。ところ2018年に改訂された本にまだこう書いてあったからです。なのでその本のサポートを探していると、間違ったサポートに行きついてしまい、きちんと確認していませんでした。

ISO/IEC 9899:1999と20xを持っていますので把握しています。
