### ISSUE TITLE
P53 $ build でのエラー

### ISSUE THREAD

**Issue by supermappin** [uchan-nos/os-from-zero#81]
P53の
$ build 
を実行すると

MikanLoaderPkg.dsc　への絶対パスかワークスペースへの相対パスを指定してくださいと表示されます。

Conf/Target.txtのAcTIVE_PLATFORMを以下画像のように設定はしたのですが、原因がわからず、ご教授いただければ幸いです。

![スクリーンショット 2021-06-12 22 25 22](https://user-images.githubusercontent.com/26266421/121777471-3bfb6f00-cbcd-11eb-81d9-a4066a63d02f.png)
![スクリーンショット 2021-06-12 22 17 00](https://user-images.githubusercontent.com/26266421/121777474-3ef65f80-cbcd-11eb-83a7-f68745988d1d.png)
![スクリーンショット 2021-06-12 22 21 47](https://user-images.githubusercontent.com/26266421/121777475-4158b980-cbcd-11eb-8faa-d057b1ec30ed.png)

**Comment by ShigeakiAsai** [comment]
lsコマンドの結果にあるMikanLoaderPkgの文字色が赤色ですので、
MIkanLoaderPkgのシンボリックリンクの作成(P50)に失敗しているのだろうと思われます。

文字色が赤い件はこちらが参考になると思います。
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q10159233075

あと、uchan-nosさんがLinuxの基本的なコマンドに関しての説明を追加して
くださいましたので、そちらもぜひご覧になられては良いかと思います。
https://github.com/uchan-nos/os-from-zero/wiki/Basic-Linux-Commands

**Comment by takotakot** [comment]
#74 こちらもどうぞ。
