### ISSUE TITLE
p.51 build が Failed となってしまう

### ISSUE THREAD

**Issue by techvaderJP** [uchan-nos/os-from-zero#84]
環境は Windows 10 上の WSL2 で、Ubuntu 18.04 になります。
p.50 までの手順を順番に実施しており、特に詰まることなく進んできたのですが、p.51 の build コマンドで failed となってしまいました。
build 成功時に出力されるはずの、$HOME/edk2/Build/MikanLoaderx64/DEBUG_CLANG38/X64/Loader.efi のファイルは出力されていませんでした。

詳細なエラーの出し方がわからず、解決策をご存じの方がいらっしゃいましたらご教示いただけますと幸いです。
```
:~/edk2$ build
Build environment: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-Ubuntu-18.04-bionic
Build start time: 21:04:58, Jun.23 2021

WORKSPACE        = /home/myadmin/edk2
EDK_TOOLS_PATH   = /home/myadmin/edk2/BaseTools
CONF_PATH        = /home/myadmin/edk2/Conf
PYTHON_COMMAND   = /usr/bin/python3.6


Processing meta-data .
Architecture(s)  = IA32
Build target     = DEBUG
Toolchain        = VS2015x86

Active Platform          = /home/myadmin/edk2/EmulatorPkg/EmulatorPkg.dsc
.

- Failed -
Build end time: 21:04:59, Jun.23 2021
Build total time: 00:00:02
```

**Comment by uchan-nos** [comment]
こちらの質問と同じ原因だと思いますので、読んでみてください。
https://github.com/uchan-nos/mikanos-build/issues/10

**Comment by techvaderJP** [comment]
ありがとうございます！
こちら同じ原因でした。 Conf/target.txt を表2.1 の設定に合わせて修正したところ、ビルドに成功し、Loader.efi が作成できました。
こちらの issue をクローズとさせていただきます。
