### ISSUE TITLE
ハローワールドの実機での表示のついて

### ISSUE THREAD

**Issue by oragahatake** [uchan-nos/os-from-zero#85]
初めて質問させて頂きます。
p31のハローワールドの表示でつま付いています。

東芝のdynabook satellite b551/c 
型番PB551CBBN77B51
のpcにubuntu20.04.1LTS
を入れて、p30下のサイトからバイナリーファイルをダウンロードして、名前をBOOTX64.EFIに名前を変更後、USBメモリをさして、p30のコマンドを実行しました。

USBメモリにBOOTX64.EFIがあることを確認し、PCを再起動したのですが、ハローワールドが表示されず、ubuntuが立ち上がってしまいました。

このPCにはセキュアブートがありませんでした。

また、osがwindows10の、富士通のセキュアブートがあるPCにセキュアブートDisabledに設定後、USBメモリをさして、起動したのですが、windowsが立ち上がってしまいました。

どうしてこのようになるのかわかりません。
ハローワールドが表示されるようにしたいのですが、御知見ありましたらご教示頂けないでしょうか？

宜しくお願い致します。

**Comment by uchan-nos** [comment]
起動可能なOSが複数ある場合、どれを優先するかはUEFIの設定で決まります。
お使いのパソコンのUEFIの設定でUSBメモリより内蔵ディスクの優先度が高いのだと思います。
起動時にDeleteあるいはF2を押すことでUEFIの設定画面に入れますので、そこで「起動順（Boot Order）」のような設定項目を探して、USBメモリが優先されるようにしてみてください。

**Comment by oragahatake** [comment]
早急にご回答頂いてありがとうございました。
ブートオーダーで、USBからの起動を選択し、起動しました。

すると、添付ファイルのような表示になるのですが、どこかで操作手順を間違っているのでしょうか？

御知見ありましたらご教示頂けないでしょうか？
![DSC_0005_HORIZON](https://user-images.githubusercontent.com/41527868/123642966-dced5980-d85e-11eb-800e-5ceaa1b1bce9.JPG)

**Comment by oragahatake** [comment]
写真が切れていましたので、再送致します。
大変申し訳ありません。
![Uploading Screenshot_20210628-223806~2.png…]()

**Comment by oragahatake** [comment]
早急にご回答頂いてありがとうございました。
ブートオーダーでUSBから起動するように設定し、PCを起動したところ、添付ファイルのような表示になりました。
何か手順が間違っているでしょうか？

度々申し訳ありませんが、御知見あればご教示頂けないでしょうか？
宜しくお願い致します。
![Screenshot_20210628-223806~2](https://user-images.githubusercontent.com/41527868/123647026-b3363180-d862-11eb-8d03-fcba5b907b4e.png)

**Comment by uchan-nos** [comment]
考えられる原因としては、お使いの機種が実は UEFI に対応していない、ということです。

dynabook Satellite B551/C の発売は 2011 だそうで、その頃はまだレガシー BIOS を搭載した機種も市場で売られていました。
[BIOSとUEFIの歴史 - syuu1228's blog](https://syuu1228.hatenablog.com/entry/20130102/1357096671) によれば 2013 年の段階で「新しい仕組みである『UEFI』への移行が進みつつあります。」だそうです。

「富士通のセキュアブートがあるPC」の方は、セキュアブートがあるということと、Windows 10 が搭載されているということで、きっと UEFI に対応していると思います。

こちらの機種で起動順を変えても上手くいきませんか？

**Comment by oragahatake** [comment]
ご回答頂いてありがとうございます。

富士通のPCで、ハローワールドを見る事ができました。

30日でできる os自作入門で、フロッピーがなくて出来なかった実機での動作を見れて、とても嬉しいです。

ありがとうございました。
