### ISSUE TITLE
xHClの正式名称について(誤植)

### ISSUE THREAD

**Issue by nnabeyang** [uchan-nos/os-from-zero#86]
p140
>xHClはeXtended Host Controller Interfaceの略で...

どちらも正しいとかあるかもしれず、自信はないのですが、正しくは`eXtensible Host Controller Interface`の略のように思います。実機でマウスを動かせるか調べているときに気付きました。kindle版を使っています。

**Comment by uchan-nos** [comment]
報告ありがとうございます。
そうですね。「eXtensible」が正しいと思います。
