### ISSUE TITLE
P.73 正誤の補足、ほか

### ISSUE THREAD

**Issue by bladenyan** [uchan-nos/os-from-zero#87]
P.73 のコード表記に対して正誤表(第３版)が出ておりますが、
正：$HOME/ … /mikanos
の後に git checkout osbook_day03a とすると、 mikanos の中に kernel ディレクトリが作られるようですね。
このため、次行となる clang++ -02 … でコンパイルをはじめる前に、

cd kernel

を追記してあげた方が親切かも知れません。
愚直に行を追って作業すると、「ファイルが無ぇ」と言われます。

あと、第３版の正誤表ページのタイトル(<title>タグの表記)が「第２版」のままで紛らわしいです。
https://zero.osdev.jp/errata/first_3suri_all.html

ついでに、どこまで読者を拾い上げるのかにもよりますが、ソース表記で慣例とされる行の右端に記されるバックスラッシュについても言及しておいた方が、言語を知らない人には分かりやすいと思います。

**Comment by uchan-nos** [comment]
Closeされていて気付きませんでした。
2刷のままになっているタイトルを修正しました。
https://github.com/uchan-nos/os-from-zero/commit/f894a220974ca0b272eb7390098e17ef42fffa19
