### ISSUE TITLE
[質問] 9.2 osbook_day09a caddr_t 型の解決

### ISSUE THREAD

**Issue by rkarsnk** [uchan-nos/os-from-zero#90]
osbook_day09aで、newlib_supportの修正に伴い、memory_manager.cppで `extern "C" caddr_t program_break` が宣言されています。

`memory_manager.{cpp|hpp}` のいずれにも `<sys/types.h>` がインクルードされていませんが、`caddr_t`の型はどのヘッダファイルが解決しているのでしょうか？

**Comment by uchan-nos** [comment]
ちょっと、ヘッダファイルの依存関係をたどる方法が思いつかなかったので、確定させることはできませんでした。

clang++ を `-E` オプションで実行してプリプロセスの結果を見ると、sys/types.h が始めて登場する直前に stddef.h とか stdio.h が読み込まれているようなので、それらの中で include されているんでしょうかね。

**Comment by rkarsnk** [comment]
わかりました。
コンパイル時にエラーが出たので、memory_manager.hppに、`<sys/types.h>` を明記して対処しました。
いったん、クローズします。
