### ISSUE TITLE
ピクセル描画とmaka入門について

### ISSUE THREAD

**Issue by BD-sheres** [uchan-nos/os-from-zero#92]
第４章のピクセル描画とmaka入門のp.102からp.106にあるプログラムについて質問です。
p.100のプログラムは実行と起動が問題なくできましたがp.102からp.106の部分がエラーが起きて実行できません。
具体的にいうと
makeとコンソールで入力すると
```
ld.lld: error: duplicate symbol: KernelMain

defined at main.cpp:68
main.o:(KernelMain)
defined at asmfunc.asm
asmfunc.o:(.text+0x7C)
make: *** [Makefile:27: kernel.elf] エラー 1
```
とでます。
多分僕の知識不足だと思いますがどうしたら実行できますか？

**Comment by ShigeakiAsai** [comment]
こんばんは。
ld.llddがエラーを検出しているようですね。
エラーの内容が「KernelMainというシンボルが重複しています」という内容に読み取れます。
> defined at main.cpp:68
> main.o:(KernelMain)
こちらは目的通りと思うのですが、
> defined at asmfunc.asm
> asmfunc.o:(.text+0x7C)
こちらは勝手に(？)出てしまったように見受けられます。

asmfunc.oのファイル名から、アセンブラ(asm)あたりが関係しそうですので、
  while (1) __asm__("hlt");
のところとかが関係するかもしれないと思います。

**Comment by BD-sheres** [comment]
ご意見を聞いてプログラムを4.2のところまでプログラムを戻し、makaとコマンドを入力しても同じエラーがでました。
なので多分指摘頂いた部分（while (1) asm("hlt");）がおかしいと思うのですが具体的にどうしたら実行できると思いますか？

**Comment by uchan-nos** [comment]
> エラーの内容が「KernelMainというシンボルが重複しています」という内容に読み取れます。

これはその通りですね。
続くエラーメッセージを読むと、main.cpp と asmfunc.asm の両方で KernelMain というシンボルが定義されている、ということが分かります。
関数というのは 1 箇所だけで定義する必要があるので、main.cpp か asmfunc.asm のどちらかだけで KernelMain を定義しなければなりません。

asmfunc.asm の中で KernelMain を定義するのは、本書 p.187 でやることなので、その前の段階では asmfunc.asm に KernelMain は無いはずです。
確認してくださいませ。

`while (1) asm("hlt");` の部分は関係ないと思います。

**Comment by BD-sheres** [comment]
ありがとうございます。
できました。変なのインポートしてました。
大変ご迷惑をおかけしました。

**Comment by BD-sheres** [comment]
わかりました。具体的にasmfunc.asmどのように記述したらいいですか？
自分もここかなぁーというところは消したのですがわけわからないところのファイルのエラーが出てしまったので直せません。

**Comment by uchan-nos** [comment]
p.102 に相当するタグは osbook_day04c ですので、その時点のソースコードを参照してください。
osbook_day04c の内容→ https://github.com/uchan-nos/mikanos/tree/osbook_day04c/kernel

今確認したら、そもそも osbook_day04c の時点では asmfunc.asm は使用されてませんね。

**Comment by BD-sheres** [comment]
返信ありがとうございます。
タグの使い方がわかりそれに本の読む速度が一気に上がりました。

**Comment by ShigeakiAsai** [comment]
こんにちは
私のコメント
> asmfunc.oのファイル名から、アセンブラ(asm)あたりが関係しそうですので、
> while (1) asm("hlt");
> のところとかが関係するかもしれないと思います。
で適当なことを言ってしまいました。
混乱させてしまいましたことお詫びいたします。

**Comment by BD-sheres** [comment]
いえいえこちらこそ。
解答してくださって本当にありがとうございます。

**Comment by uchan-nos** [comment]
解決したようなのでクローズ
