### ISSUE TITLE
(質問)$ qemu-img create -f raw disk.img 200M を実行したが、$ qemu-imgが見つからないと言われた件

### ISSUE THREAD

**Issue by Hika5426** [uchan-nos/os-from-zero#93]
$ qemu-img create -f raw disk.img 200M

Command 'qemu-img' not found, but can be installed with:

sudo apt install qemu-utils
となりました。
また、その後、$sudo apt install qemu-utilsも行いましたが、notfoundが出て出来ないようです。どうすればいいですか？

**Comment by uchan-nos** [comment]
正確なエラーメッセージを確認したいので、
コマンドを実行しようとしてnotfoundが表示された画面のスクリーンショットを添付してください。

（スクリーンショットは、Windows 10であれば「Win+Shift+S」、Linuxであれば「Print Screen」というキーで撮影可能です）

**Comment by Hika5426** [comment]
![画像①](https://user-images.githubusercontent.com/88386569/128040663-a45a02b0-b71a-4993-913f-443b07aed488.PNG)
![画像②](https://user-images.githubusercontent.com/88386569/128040705-3043cc2a-c0bb-421d-8d15-f02f00d830eb.PNG)

**Comment by Hika5426** [comment]
上に、スクリーンショットを出しました。

**Comment by uchan-nos** [comment]
ありがとうございます。
スクリーンショットのおかげで、WSL でやっていること、apt install がエラーになっていることがはっきり分かりました。
apt intall のエラーを解決していきましょう。

一発で解決する方法は分からないですが、いくつか試して見て欲しい手順があります。
以下のコマンドを実行してから、改めて sudo apt install qemu-utils をやってみてもらえませんか。
（実行したコマンドとその結果をすべて貼っていただくか、スクリーンショットを撮っていただけると大変助かります）

まず、WSL 内の時計を修正します。
Windows のスリープに伴って WSL 内の時計がずれることがあり、大きくずれていると apt に支障が出ます。

    $ date
    $ sudo hwclock -s
    $ date

APT データベースを更新します。

    $ sudo apt update

あらためて qemu-utils をインストールします。

    $ sudo apt install qemu-utils

**Comment by Hika5426** [comment]
分かりずらい不適切な質問をしてすみません。それから、丁寧で早い回答もありがとうございます。上記のコマンドをやってみた結果が以下になります。

**Comment by Hika5426** [comment]
![実行結果①](https://user-images.githubusercontent.com/88386569/128110301-d7975c7b-bfb8-42d7-98ea-acd6066908d3.PNG)
![実行結果②](https://user-images.githubusercontent.com/88386569/128110308-bebf25d8-a226-48f7-856d-60aa9d93d73e.PNG)
![実行結果③](https://user-images.githubusercontent.com/88386569/128110313-8d6cd59d-b864-44d2-b209-c347757faf86.PNG)

**Comment by Hika5426** [comment]
aptコマンド(Windows 10のLinux互換環境WSLでUbuntuを使っている場合、新たにパッケージをインストールしたり、既存のパッケージを最新版の状態に更新したりするために利用)するものと、APT(aptコマンドなどを含むパッケージ管理ツール？)。今回のこの原因は、qemu-utilsというパッケージをAPTに入れられないことから、WSLの時計の修正と、APTのデータベースを更新することで、できるようにしたということでしょうか？

**Comment by Hika5426** [comment]
すいません。また、少し先に進めたら、エラーが発生したので回答お願いします。自分が行った流れとしては、自分はUSBを持っていないので、1.4のエミュレータでのやり方を行いました。上の回答によって、1行目のqemu-img create -f raw disk.img 200Mが出来るようになったのですが、そこからちょっと先に進めて、6行目のsudo cp BOOTX64.EFIを行った結果、cannot stat 'BOOTX64.EFI': No such file or directoryエラーが発生しました。そこからcdコマンドを利用して、BOOT上にBOOTX64.EFIが存在しないことが分かったが、どうすればいいのかわからず手が止まってしまっています。また、BOOTX64.EFIはC:\Users\r201902975lt\Downloads上に存在します。下に、上記の実行の流れのスクリーンショットを貼ってあります。
![実行結果](https://user-images.githubusercontent.com/88386569/128142177-5b643bcd-5a2f-41af-9fff-c407fc7f3678.PNG)

**Comment by uchan-nos** [comment]
> 分かりずらい不適切な質問をしてすみません。

ちょっと情報が足りなかっただけで、不適切じゃないですよ。適切な質問です！
今後とも臆せずに質問してくださいませ。

さて、ご質問の件ですが、

**Comment by Hika5426** [comment]
資料を一通り読み終えました。カレントディレクトリ(自分の場合は、/home/hikaru)で、lsと実行しても、実際、BOOTX64.EFI が存在しませんでした。そうすると、/home/hikaruにBOOTX64.EFIを追加する必要があるということだと思うのですが、windowsのC:\Users\r201902975lt\Downloads上にあるBOOTX64.EFIを/home/hikaruに持ってくるには、mvコマンドを行えばいいということでしょうか？

**Comment by uchan-nos** [comment]
> windowsのC:\Users\r201902975lt\Downloads上にあるBOOTX64.EFIを/home/hikaruに持ってくるには、mvコマンドを行えばいいということでしょうか？

はい、その通りです。mv か、あるいは cp でも可です。（移動するかコピーするかの違い）

WSL 上で Windows のファイルにアクセスするには、C ドライブが `/mnt/c` で見えることを利用します。
BOOTX64.EFI をカレントディレクトリに移動するには次のようにします。

    $ mv /mnt/c/Users/r201902975lt/Downloads/BOOTX64.EFI ./

**Comment by Hika5426** [comment]
返信遅れてしまってすいません。やってみて、カレントディレクトリに移動できました。ありがとうございます。

**Comment by Hika5426** [comment]
すいません。質問です。そこからほんの少し先に進めて、qemu-system-x86_64を行って、そこでCommand 'qemu-system-x86_64' not found, but can be installed with～～とでできたので、qemu-system-x86_64のインストールを行いました。(インストール終了後、パソコンのアップデートにより、再起動したため残っていませんごめんなさい)そこから先が、スクリーンショットで、エラーが発生したところです。解消法を教えてください。

**Comment by Hika5426** [comment]
![キャプチャ](https://user-images.githubusercontent.com/88386569/128525719-6e735ed2-8b23-4a29-ad88-3160f42f858e.PNG)

**Comment by uchan-nos** [comment]
全般的に開発ツールが足りていないようです。
https://github.com/uchan-nos/mikanos-build
の手順に従って開発環境のセットアップをしてください。

**Comment by Hika5426** [comment]
セットアップを行ってみました。$ ansible-playbook -K -i ansible_inventory ansible_provision.ymlを最初にやった際に、TASK [clone EDK II repository]というところで時間を掛けてもずっと返答がなかったため、強制終了と再起動を行いました。iasl -vや ls $HOME/edk2が正常に動作したことから、大丈夫だと思ったのですが、標準ライブラリのライセンスについて～からcd $HOME/osbook/devenv/x86_64-elfをすると、存在しないと書かれています。これは、大丈夫でしょうか。以下、再起動後に行ったもののスクリーンショット。
![①](https://user-images.githubusercontent.com/88386569/128726055-1597b81a-c9cd-41d8-82f7-1fdecafba966.PNG)
![②](https://user-images.githubusercontent.com/88386569/128726070-2bf1b7ba-38e2-4a9e-be23-b38e24e0c277.PNG)
![③](https://user-images.githubusercontent.com/88386569/128726080-3155aa4b-e1ce-4863-8a2f-2baf2460db46.PNG)

**Comment by uchan-nos** [comment]
> 標準ライブラリのライセンスについて～からcd $HOME/osbook/devenv/x86_64-elfをすると、存在しないと書かれています。これは、大丈夫でしょうか。

大丈夫ではありません。必要なファイルですから。

> 時間を掛けてもずっと返答がなかったため

とありますが、数分以上かかることもあります。どのくらい待ちましたか？

念のため $HOME/edk2 を全部削除してから ansible-playbook を再度実行してみてください。
削除は以下のコマンドで可能です。

    $ rm -rf $HOME/edk2

**Comment by Hika5426** [comment]
やってみました。また、出来ないところが出てきました。mikanosを＄HOME上に置きました。そして、$HOME/edk2上にmikanos/MikanLoaderPkgに対するリンクを張るln -s /path/to/mikanos/MikanLoaderPkg ./を行い、 ls MikanLoaderPkg/Main.cをした結果、ls: cannot access 'MikanLoaderPkg/Main.c': No such file or directoryと出てきました。リンクとmikanosを何度か削除してやり直したのですが、結果は変わりませんでした。
![①](https://user-images.githubusercontent.com/88386569/129468690-205d1626-3ea8-400c-9f25-1577c973fb33.PNG)
![②](https://user-images.githubusercontent.com/88386569/129468696-2c1f33f4-b7aa-4e8b-b395-dd54d72b1a8c.PNG)
![③](https://user-images.githubusercontent.com/88386569/129468700-220f5894-00eb-46dc-bf7c-e096dc4f0877.PNG)
![④](https://user-images.githubusercontent.com/88386569/129468701-9b602245-2773-49c6-82bf-2332f178ee5d.PNG)
![⑤](https://user-images.githubusercontent.com/88386569/129468702-f98068c7-c618-4829-bf14-8ffd66e5b993.PNG)

**Comment by uchan-nos** [comment]
それはリンク先のパスが間違っているからです。
https://github.com/uchan-nos/mikanos-build の説明にこうあります。

> /path/to/mikanos は先ほど git clone でダウンロードした mikanos ディレクトリへのパスを指定します。

Hika5426 さんは git clone を $HOME 以下に行いましたので、次のように指定する必要があります。

    $ ln -s $HOME/mikanos/MikanLoaderPkg ./

**Comment by Hika5426** [comment]
出来ました。次に、edksetup.sh ファイルを読み込むと，環境変数が設定される他に Conf/target.txt が自動的に生成されます。 このファイルをエディタで開き，次の項目を修正します。とありますが、エディタでtarget.xtを開くとは、カレントディレクトリをConfにして、open target.txtを行えばいいということでしょうか。

**Comment by uchan-nos** [comment]
どんな方法でも良いですが、target.txt を開いて、編集して、保存してください。

> エディタでtarget.xtを開くとは、カレントディレクトリをConfにして、open target.txtを行えばいいということでしょうか。

カレントディレクトリを Conf にして、まではその通りですが、
WSL には open コマンドがありませんので、その方法は使えません。

例えば、メモ帳を使って編集する場合、カレントディレクトリを Conf にした状態で、次のコマンドでできると思います。

    $ notepad.exe target.txt

**Comment by uchan-nos** [comment]
特に追加質問はなさそうなのでクローズします
