### ISSUE TITLE
wslがwindows insider で最新のwindows10に更新してもダウンロードできません。

### ISSUE THREAD

**Issue by woodstock3** [uchan-nos/os-from-zero#94]
wslがwindows insider で最新のwindows10に更新してもダウンロードできません。
現在のwindows10のバージョンは「バージョン Dev(OSビルド21354.1）です。
コマンドプロンプト、パワーシェル両方を管理者権限で実行してみましたが、
手動インストール,簡略化されたインストールいずれも実行できませんでした。
簡略化されたインストールの場合は以下のようになります。
パワーシェルはwindows insiderのインストールで、文字化けするため症状が記述できません。

Microsoft Windows [Version 10.0.21354.1]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>wsl --install
'wsl' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。

C:\WINDOWS\system32>

解決方法がありましたら、お願い致します。

**Comment by woodstock3** [comment]
ちなみに『OS自作入門　30日でできる！operating system/川合秀美』の本はwindows環境で作成できますか？

**Comment by uchan-nos** [comment]
私は Windows Insider を持っていないので WSL がインストールできない問題については分かりません。

> ちなみに『OS自作入門　30日でできる！operating system/川合秀美』の本はwindows環境で作成できますか？

川合秀実著の「30日でできる! OS自作入門」のことであれば、Windows 環境で開発できると思います。
（最新の Windows での動作を確認したわけではないです。すみません。）

**Comment by woodstock3** [comment]
了解しました。とりあえずそちらで試してみようかなと思っています。
