### ISSUE TITLE
osbook_day02bのbuildでエラー

### ISSUE THREAD

**Issue by todori** [uchan-nos/os-from-zero#97]
day02bのコードをビルドすると、次のようなエラーが発生します。
解決方法を教えていただけないでしょうか？

-----------------------------------------------------------------------

Build environment: Linux-4.15.0-153-generic-x86_64-with-Ubuntu-18.04-bionic
Build start time: 22:22:59, Aug.15 2021

WORKSPACE        = /home/user/edk2
EDK_TOOLS_PATH   = /home/user/edk2/BaseTools
CONF_PATH        = /home/user/edk2/Conf
PYTHON_COMMAND   = /usr/bin/python3.6

Processing meta-data .
Architecture(s)  = X64
Build target     = DEBUG
Toolchain        = CLANG38

Active Platform          = /home/user/edk2/MikanLoaderPkg/MikanLoaderPkg.dsc
 done!
Building ... /home/user/edk2/MdePkg/Library/UefiApplicationEntryPoint/UefiApplicationEntryPoint.inf [X64]
make: 'tbuild' に対して行うべき事はありません.
Building ... /home/user/edk2/MdePkg/Library/UefiLib/UefiLib.inf [X64]
make: 'tbuild' に対して行うべき事はありません.
Building ... /home/user/edk2/MdePkg/Library/UefiDevicePathLib/UefiDevicePathLib.inf [X64]
make: 'tbuild' に対して行うべき事はありません.
Building ... /home/user/edk2/MdePkg/Library/UefiRuntimeServicesTableLib/UefiRuntimeServicesTableLib.inf [X64]
make: 'tbuild' に対して行うべき事はありません.
Building ... /home/user/edk2/MdePkg/Library/BasePrintLib/BasePrintLib.inf [X64]
make: 'tbuild' に対して行うべき事はありません.
Building ... /home/user/edk2/MdePkg/Library/UefiMemoryAllocationLib/UefiMemoryAllocationLib.inf [X64]
make: 'tbuild' に対して行うべき事はありません.
Building ... /home/user/edk2/MdePkg/Library/UefiBootServicesTableLib/UefiBootServicesTableLib.inf [X64]
make: 'tbuild' に対して行うべき事はありません.
Building ... /home/user/edk2/MdePkg/Library/BaseDebugLibNull/BaseDebugLibNull.inf [X64]
make: 'tbuild' に対して行うべき事はありません.
Building ... /home/user/edk2/MdePkg/Library/BaseLib/BaseLib.inf [X64]
Building ... /home/user/edk2/MdePkg/Library/BasePcdLibNull/BasePcdLibNull.inf [X64]
make: 'tbuild' に対して行うべき事はありません.
Building ... /home/user/edk2/MdePkg/Library/BaseMemoryLib/BaseMemoryLib.inf [X64]
make: 'tbuild' に対して行うべき事はありません.
make: 'tbuild' に対して行うべき事はありません.
Building ... /home/user/edk2/MikanLoaderPkg/Loader.inf [X64]
"clang" -o /home/user/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/MikanLoaderPkg/Loader/DEBUG/Loader.dll -nostdlib -Wl,-n,-q,--gc-sections -z common-page-size=0x40 -Wl,--entry,_ModuleEntryPoint -u _ModuleEntryPoint -Wl,-Map,/home/user/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/MikanLoaderPkg/Loader/DEBUG/Loader.map,--whole-archive -flto -Wl,-Oz -Wl,-melf_x86_64 -Wl,--oformat=elf64-x86-64 -Wl,-pie -mcmodel=small -Wl,--start-group,@/home/user/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/MikanLoaderPkg/Loader/OUTPUT/static_library_files.lst,--end-group -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -ffunction-sections -fdata-sections -DSTRING_ARRAY_NAME=LoaderStrings -Wno-parentheses-equality -Wno-tautological-compare -Wno-tautological-constant-out-of-range-compare -Wno-empty-body -Wno-unused-const-variable -Wno-varargs -Wno-unknown-warning-option -fno-stack-protector -mms-bitfields -Wno-address -Wno-shift-negative-value -Wno-unknown-pragmas -Wno-incompatible-library-redeclaration -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -msoft-float -mno-implicit-float -ftrap-function=undefined_behavior_has_been_optimized_away_by_clang -funsigned-char -fno-ms-extensions -Wno-null-dereference -m64 "-DEFIAPI=__attribute__((ms_abi))" -mno-red-zone -mcmodel=small -fpie -Oz -flto -target x86_64-pc-linux-gnu -g -Wl,--defsym=PECOFF_HEADER_SIZE=0x228 -Wl,--script=/home/user/edk2/BaseTools/Scripts/GccBase.lds -**Wno-error -O3**
/usr/bin/ld: **error: Failed to link module /home/user/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/MdePkg/Library/BaseMemoryLib/BaseMemoryLib/OUTPUT/BaseMemoryLib.lib.llvm.88992.MemLibGuid.c: Invalid record
clang: error: linker command failed with exit code 1 (use -v to see invocation)**
**GNUmakefile:341: recipe for target '/home/user/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/MikanLoaderPkg/Loader/DEBUG/Loader.dll' failed
make: *** [/home/user/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/MikanLoaderPkg/Loader/DEBUG/Loader.dll] Error 1**

build.py...
 : **error 7000: Failed to execute command
	make tbuild [/home/user/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/MikanLoaderPkg/Loader]**

build.py...
 : **error F002: Failed to build module
	/home/user/edk2/MikanLoaderPkg/Loader.inf [X64, CLANG38, DEBUG]**

- Failed -
Build end time: 22:23:00, Aug.15 2021
Build total time: 00:00:01

**Comment by uchan-nos** [comment]
うーん、よく分かりませんね……

> Processing meta-data .
> Architecture(s) = X64
> Build target = DEBUG
> Toolchain = CLANG38

あたりを見るに、設定は合っていると思います。

一つ試せるとしたら Build ディレクトリ以下を削除してから再ビルドすることくらいですかね。

    $ cd $HOME/edk2
    $ rm -rf Build
    $ build

**Comment by todori** [comment]
ありがとうございます。
$HOME/edk2/Buildを削除すると無事にbuildができました。
