### ISSUE TITLE
P.30　sumコマンドでの応答について

### ISSUE THREAD

**Issue by Oryzae-O** [uchan-nos/os-from-zero#98]
p33で紹介されていた「Binary Editor Bz」のBzでp29をバイナリファイルを作成し,p30のsumコマンドを使用してBOOTX64.EFIのチェックサムを行おうとしたのですが,このような返答をされました．
![2021-08-19 (6)](https://user-images.githubusercontent.com/82478436/130021353-adb37aec-b7a2-493b-bada-842296ae582e.png)
補足としましては,このファイルはデスクトップ上に保存してあり,Bzで開くように設定してあります.
![2021-08-19 (7)](https://user-images.githubusercontent.com/82478436/130026219-3e881742-7362-4ee7-9384-5276dc886de2.png)
また，p35でのsudo cpコマンドでもBOOTX64.EFIが見つからないと言われました.
![2021-08-19 (8)](https://user-images.githubusercontent.com/82478436/130027292-f0457ce8-b770-4147-8e48-0d7657af1be5.png)
どうすればよいのかご教授して頂けるとハネて喜びます.

**Comment by PickledChair** [comment]
WSL上ではWindowsのパスを直接使うことはできません。
`wslpath` コマンドで、WSL側で扱えるパスに変換すると、WSL側からもWindows側のファイルを参照することができます。
今回の場合は、

```
$ cp `wslpath -u 'C:\Users\4894a\Desktop\BOOTX64.EFI'` .
```

というコマンドをWSL側で実行すると、WSL側の作業ディレクトリに `BOOTX64.EFI` がコピーされるはずです。

**Comment by PickledChair** [comment]
`\`（バックスラッシュ）は`¥`（円記号）で読み替えてください💦

**Comment by Oryzae-O** [comment]
PickledChair さんご丁寧にありがとうございます.
ご指導どおりに入力してみたところBOOTX64.EFIが無事WSL側にコピーされました.
その後幾度が試行していく間に開発環境の整備が不十分だったことに気づき,なんとかQEMU上でHello world!を出すことができました.重ねて感謝申し上げます.
![2021-08-20 (3)](https://user-images.githubusercontent.com/82478436/130197809-b72046cf-9ba3-45d1-97a6-763c85318321.png)
しかしながら,環境を整えている間に別の問題が発生したので,別のスレッジを出そうと思います.
もしよければ,また御指導のほど,よろしくお願い致します.

**Comment by PickledChair** [comment]
ハローワールド達成おめでとうございます。お疲れ様でした！

**Comment by Oryzae-O** [comment]
Closed
